/**
 * CEST goods descriptions, as the annexes of Convênio ICMS 142/18 word them, each at the index of
 * its code in `CEST_CODES` (`cest.ts`).
 *
 * Packed by `packTexts` (scripts/lookup-table.ts), which `unpackTexts` reads.
 *
 * Generated by `node ./scripts/cest.ts`. Do not edit by hand.
 *
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/convenios/2018/CV142_18
 * Convênio ICMS 142/18, the consolidated text and its annexes.
 */
export const CEST_DESCRIPTIONS =
	'0Catalisadores em colmeia cerâmica ou metálica para conversão catalítica de gases de escape de veículos e outros catalisadores\n\
0Tubos e seus acessórios (por exemplo, juntas, cotovelos, flanges, uniões), de plásticos\n\
0Protetores de caçamba\n\
0Reservatórios de óleo\n\
0Frisos, decalques, molduras e acabamentos\n\
0Correias de transmissão de borracha vulcanizada, de matérias têxteis, mesmo impregnadas, revestidas ou recobertas, de plástico, ou estratificadas com plástico ou reforçadas com metal ou com outras matérias\n\
0Juntas, gaxetas e outros elementos com função semelhante de vedação\n\
0Partes de veículos automóveis, tratores e máquinas autopropulsadas\n\
0Tapetes, revestimentos, mesmo confeccionados, batentes, buchas e coxins\n\
1ecidos impregnados, revestidos, recobertos ou estratificados, com plástico\n\
0Mangueiras e tubos semelhantes, de matérias têxteis, mesmo com reforço ou acessórios de outras matérias\n\
0Encerados e toldos\n\
0Capacetes e artefatos de uso semelhante, de proteção, para uso em motocicletas, incluídos ciclomotores\n\
0Guarnições de fricção (por exemplo, placas, rolos, tiras, segmentos, discos, anéis, pastilhas), não montadas, para freios, embreagens ou qualquer outro mecanismo de fricção, à base de amianto, de outras substâncias minerais ou de celulose, mesmo combinadas com têxteis ou outras matérias\n\
0Vidros de dimensões e formatos que permitam aplicação automotiva\n\
0Espelhos retrovisores\n\
0Lentes de faróis, lanternas e outros utensílios\n\
0Cilindro de aço para GNV (gás natural veicular)\n\
0Recipientes para gases comprimidos ou liquefeitos, de ferro fundido, ferro ou aço, exceto o descrito no item 18.0\n\
0Molas e folhas de molas, de ferro ou aço\n\
0Obras moldadas, de ferro fundido, ferro ou aço, exceto as do código 7325.91.00\n\
0Peso de chumbo para balanceamento de roda\n\
5para balanceamento de roda e outros utensílios de estanho\n\
0Fechaduras e partes de fechaduras\n\
0Chaves apresentadas isoladamente\n\
0Dobradiças, guarnições, ferragens e artigos semelhantes de metais comuns\n\
0Triângulo de segurança\n\
0Motores de pistão alternativo dos tipos utilizados para propulsão de veículos do Capítulo 87\n\
9os tipos utilizados para propulsão de veículos automotores\n\
0Partes reconhecíveis como exclusiva ou principalmente destinadas aos motores das posições 8407 ou 8408\n\
0Motores hidráulicos\n\
0Bombas para combustíveis, lubrificantes ou líquidos de arrefecimento, próprias para motores de ignição por centelha ou por compressão\n\
7de vácuo\n\
0Compressores e turbocompressores de ar\n\
0Partes das bombas, compressores e turbocompressores dos CEST 01.032.00, 01.033.00 e 01.034.00\n\
0Máquinas e aparelhos de ar condicionado\n\
0Aparelhos para filtrar óleos minerais nos motores de ignição por centelha ou por compressão\n\
0Filtros a vácuo\n\
0Partes dos aparelhos para filtrar ou depurar líquidos ou gases\n\
0Extintores, mesmo carregados\n\
0Filtros de entrada de ar para motores de ignição por centelha ou por compressão\n\
0Depuradores por conversão catalítica de gases de escape\n\
0Macacos\n\
0Partes para macacos do CEST 01.043.00\n\
7reconhecíveis como exclusiva ou principalmente destinadas às máquinas agrícolas ou rodoviárias\n\
z ou principalmente destinadas às máquinas agrícolas ou rodoviárias\n\
0Válvulas redutoras de pressão\n\
9para transmissão óleo-hidráulicas ou pneumáticas\n\
9solenoides\n\
0Rolamentos\n\
0Árvores de transmissão (incluídas as árvores de “cames” e virabrequins) e manivelas; mancais e “bronzes”; engrenagens e rodas de fricção; eixos de esferas ou de roletes; redutores, multiplicadores, caixas de transmissão e variadores de velocidade, incluídos os conversores de torque; volantes e polias, incluídas as polias para cadernais; embreagens e dispositivos de acoplamento, incluídas as juntas de articulação\n\
0Juntas metaloplásticas; jogos ou sortidos de juntas de composições diferentes, apresentados em bolsas, envelopes ou embalagens semelhantes; juntas de vedação mecânicas (selos mecânicos)\n\
0Acoplamentos, embreagens, variadores de velocidade e freios, eletromagnéticos\n\
2umuladores elétricos de chumbo, do tipo utilizado para o arranque dos motores de pistão, exceto os classificados no CEST 01.053.01\n\
zo tipo utilizado para o arranque dos motores de pistão e de capacidade inferior ou igual a 20 Ah e tensão inferior ou igual a 12 V\n\
1parelhos e dispositivos elétricos de ignição ou de arranque para motores de ignição por centelha ou por compressão (por exemplo, magnetos, dínamos-magnetos, bobinas de ignição, velas de ignição ou de aquecimento, motores de arranque); geradores (dínamos e alternadores, por exemplo) e conjuntores-disjuntores utilizados com estes motores\n\
blétricos de iluminação ou de sinalização (exceto os da posição 8539), limpadores de para-brisas, degeladores e desembaçadores (desembaciadores) elétricos e suas partes\n\
0Telefones móveis do tipo dos utilizados em veículos automóveis\n\
0Alto-falantes, amplificadores elétricos de audiofrequência e partes\n\
1parelhos elétricos de amplificação de som para veículos automotores\n\
ade reprodução de som\n\
atransmissores (emissores) de radiotelefonia ou radiotelegrafia (rádio receptor/transmissor)\n\
areceptores de radiodifusão que só funcionem com fonte externa de energia combinados com um aparelho de gravação ou de reprodução de som, do tipo utilizado em veículos automóveis\n\
0Outros aparelhos receptores de radiodifusão que só funcionem com fonte externa de energia, do tipo utilizado em veículos automóveis\n\
hvideofônicos de gravação ou de reprodução, mesmo incorporando um receptor de sinais videofônicos, dos tipos utilizados exclusivamente em veículos automotores\n\
0Antenas\n\
0Circuitos impressos\n\
0Interruptores e seccionadores e comutadores\n\
0Fusíveis e corta-circuitos de fusíveis\n\
0Disjuntores\n\
0Relés\n\
0Partes reconhecíveis como exclusivas ou principalmente destinados aos aparelhos dos CEST 01.065.00, 01.066.00, 01.067.00 e 01.068.00\n\
0Faróis e projetores, em unidades seladas\n\
0Lâmpadas e tubos de incandescência, exceto de raios ultravioleta ou infravermelhos\n\
0Cabos coaxiais e outros condutores elétricos coaxiais\n\
0Jogos de fios para velas de ignição e outros jogos de fios\n\
0Carroçarias para os veículos automóveis das posições 8701 a 8705, incluídas as cabinas\n\
0Partes e acessórios dos veículos automóveis das posições 8701 a 8705\n\
5 e acessórios de motocicletas (incluídos os ciclomotores)\n\
0Engates para reboques e semirreboques\n\
0Medidores de nível; Medidores de vazão\n\
0Aparelhos para medida ou controle da pressão\n\
0Contadores, indicadores de velocidade e tacômetros, suas partes e acessórios\n\
0Amperímetros\n\
1parelhos digitais, de uso em veículos automóveis, para medida e indicação de múltiplas grandezas tais como: velocidade média, consumos instantâneo e médio e autonomia (computador de bordo)\n\
0Controladores eletrônicos\n\
0Relógios para painéis de instrumentos e relógios semelhantes\n\
0Assentos e partes de assentos\n\
1cendedores\n\
0Tubos de borracha vulcanizada não endurecida, mesmo providos de seus acessórios\n\
0Juntas de vedação de cortiça natural e de amianto\n\
0Papel-diagrama para tacógrafo, em disco\n\
0Fitas, tiras, adesivos, autocolantes, de plástico, refletores, mesmo em rolos; placas metálicas com película de plástico refletora, próprias para colocação em carrocerias, para-choques de veículos de carga, motocicletas, ciclomotores, capacetes, bonés de agentes de trânsito e de condutores de veículos, atuando como dispositivos refletivos de segurança rodoviários\n\
0Cilindros pneumáticos\n\
0Bomba elétrica de lavador de para-brisa\n\
6de assistência de direção hidráulica\n\
0Motoventiladores\n\
0Filtros de pólen do ar-condicionado\n\
0“Máquina” de vidro elétrico de porta\n\
0Motor de limpador de para-brisa\n\
0Bobinas de reatância e de autoindução\n\
1aterias de chumbo e de níquel-cádmio\n\
0Aparelhos de sinalização acústica (buzina)\n\
0Instrumentos para regulação de grandezas não elétricas\n\
0Analisadores de gases ou de fumaça (sonda lambda)\n\
0Perfilados de borracha vulcanizada não endurecida\n\
0Artefatos de pasta de fibra de uso automotivo\n\
0Tapetes/carpetes – náilon\n\
7 de matérias têxteis sintéticas\n\
0Forração interior capacete\n\
0Outros para-brisas\n\
0Moldura com espelho\n\
0Corrente transmissão\n\
0Outras correntes de transmissão\n\
0Condensador tubular metálico\n\
0Trocadores de calor\n\
0Partes de aparelhos mecânicos de pulverizar ou dispersar\n\
0Macacos manuais para veículos\n\
0Caçambas, pás, ganchos e tenazes para máquinas rodoviárias\n\
0Geradores de corrente alternada de potência não superior a 75 kva\n\
0Aparelhos elétricos para alarme de uso automotivo\n\
0Bússolas\n\
0Indicadores de temperatura\n\
0Partes de indicadores de temperatura\n\
aaparelhos de medida ou controle\n\
0Termostatos\n\
0Instrumentos e aparelhos para regulação\n\
0Pressostatos\n\
1eças para reboques e semirreboques, exceto os itens classificados no CEST 01.077.00\n\
0Geradores de ar quente a combustível líquido, com capacidade superior ou igual a 1.500 kcal/h, mas inferior ou igual a 10.400 kcal/h, do tipo dos utilizados em veículos automóveis\n\
0Outras peças, partes e acessórios para veículos automotores não relacionados nos demais itens deste anexo\n\
0Aperitivos, amargos, bitter e similares\n\
0Batida e similares\n\
1ebida ice\n\
0Cachaça e aguardentes\n\
2tuaba e similares\n\
1onhaque, brandy e similares\n\
2oler\n\
0Gim (gin) e genebra\n\
0Jurubeba e similares\n\
0Licores e similares\n\
0Pisco\n\
0Rum\n\
0Saquê\n\
1teinhaeger\n\
0Tequila\n\
0Uísque\n\
0Vermute e similares\n\
1odka\n\
0Derivados de vodka\n\
0Arak\n\
1guardente vínica / grappa\n\
0Sidra e similares\n\
1angrias e coquetéis\n\
0Vinhos de uvas frescas, incluindo os vinhos enriquecidos com álcool; mostos de uvas\n\
0Outras bebidas alcoólicas não especificadas nos itens anteriores\n\
0Água mineral, gasosa ou não, ou potável, naturais, em embalagem de vidro descartável\n\
zável, naturais, adicionadas de sais, em embalagem de vidro descartável\n\
zável, naturais, em copo plástico descartável\n\
zável, naturais, adicionadas de sais, em copo plástico descartável\n\
zável, naturais, em jarra descartável\n\
zável, naturais, adicionadas de sais, em jarra descartável\n\
zável, naturais, em demais embalagens descartáveis\n\
zável, naturais, adicionadas de sais, em demais embalagens descartáveis\n\
0Outras águas minerais, gasosa ou não, ou potável, naturais; exceto as classificadas no CEST 03.003.00, 03.003.01, 03.005.00, 03.005.01 a 03.005.05, 03.024.00 e 03.025.00\n\
0Água aromatizada artificialmente, exceto os refrescos e refrigerantes\n\
0Outras águas minerais, gasosa ou não, ou potável, naturais, inclusive gaseificadas ou aromatizadas artificialmente, exceto os refrescos e refrigerantes\n\
0Refrigerante em vidro descartável\n\
gembalagem pet\n\
glata\n\
0Demais refrigerantes, exceto os classificados no CEST 03.010.00, 03.010.01, 03.010.02 e 03.011.01\n\
0Espumantes sem álcool\n\
0Xarope ou extrato concentrado destinados ao preparo de refrigerante em máquina “pré-mix” ou “post-mix”, exceto o classificado no CEST 03.012.01\n\
0Cápsula de refrigerante\n\
0Bebidas energéticas em lata\n\
nembalagem PET\n\
nvidro\n\
8hidroeletrolíticas\n\
0Cerveja em garrafa de vidro retornável\n\
sdescartável\n\
malumínio\n\
blata\n\
bbarril\n\
bembalagem PET\n\
boutras embalagens\n\
8sem álcool em garrafa de vidro retornável\n\
zdro descartável\n\
xalumínio\n\
mlata\n\
mbarril\n\
membalagem PET\n\
moutras embalagens\n\
1hope\n\
0Água mineral em embalagens retornáveis com capacidade igual ou superior a 10 (dez) e inferior a 20 (vinte) litros\n\
zeis com capacidade igual ou superior a 20 (vinte) litros\n\
0Charutos, cigarrilhas e cigarros, de tabaco ou dos seus sucedâneos\n\
0Tabaco para fumar, mesmo contendo sucedâneos de tabaco em qualquer proporção\n\
0Cimento\n\
0Álcool etílico não desnaturado, com um teor alcoólico em volume igual ou superior a 80% vol - Com um teor de água igual ou inferior a 1 % vol (álcool etílico anidro combustível)\n\
z um teor alcoólico em volume igual ou superior a 80% vol - Outros (álcool etílico hidratado combustível)\n\
0Gasolina automotiva A, exceto Premium\n\
kC, exceto Premium\n\
kA Premium\n\
kC Premium\n\
9de aviação\n\
0Querosenes, exceto de aviação\n\
9 de aviação\n\
0Óleo diesel A, exceto S10 e Marítimo\n\
cB, exceto S10 (mistura obrigatória)\n\
ys autorizativas)\n\
z experimentais)\n\
cA S10\n\
cB S10 (mistura obrigatória)\n\
qs autorizativas)\n\
sexperimentais)\n\
5Diesel Marítimo\n\
0Outros óleos combustíveis, exceto os classificados no CEST 06.006.10 e 06.006.11\n\
0Óleo combustível derivado de xisto\n\
hpesado\n\
4s lubrificantes\n\
0Outros óleos de petróleo ou de minerais betuminosos (exceto óleos brutos) e preparações não especificadas nem compreendidas noutras posições, que contenham, como constituintes básicos, 70% ou mais, em peso, de óleos de petróleo ou de minerais betuminosos, exceto os que contenham biodiesel, exceto os resíduos de óleos e exceto as graxas lubrificantes\n\
0Graxa lubrificante\n\
0Resíduos de óleos\n\
0Gás de petróleo e outros hidrocarbonetos gasosos, exceto GLP, GLGN, Gás Natural e Gás de xisto\n\
4liquefeito de petróleo em botijão de 13 Kg (GLP)\n\
r(GLP), exceto em botijão de 13 Kg\n\
rem botijão de 13 Kg (GLGNn)\n\
r(GLGNn), exceto em botijão de 13 Kg\n\
rem botijão de 13 Kg (GLGNi)\n\
r(GLGNi), exceto em botijão de 13 Kg\n\
rem botijão de 13 kg (Misturas)\n\
r(Misturas), exceto em botijão de 13 Kg\n\
4Natural Liquefeito\n\
cGasoso\n\
4de xisto\n\
0Coque de petróleo e outros resíduos de óleo de petróleo ou de minerais betuminosos\n\
0Biodiesel e suas misturas, que não contenham ou que contenham menos de 70%, em peso, de óleos de petróleo ou de óleos minerais betuminosos\n\
0Preparações lubrificantes, exceto as contendo, como constituintes de base, 70% ou mais, em peso, de óleos de petróleo ou de minerais betuminosos\n\
0Óleos de petróleo ou de minerais betuminosos (exceto óleos brutos) e preparações não especificadas nem compreendidas noutras posições, que contenham, como constituintes básicos, 70% ou mais, em peso, de óleos de petróleo ou de minerais betuminosos, que contenham biodiesel, exceto os resíduos de óleos\n\
0Naftas, exceto a Nafta petroquímica\n\
0Energia elétrica\n\
0Ferramentas de borracha vulcanizada não endurecida\n\
b, armações e cabos de ferramentas, de madeira\n\
0Mós e artefatos semelhantes, sem armação, para moer, desfibrar, triturar, amolar, polir, retificar ou cortar; pedras para amolar ou para polir, manualmente, e suas partes, de pedras naturais, de abrasivos naturais ou artificiais aglomerados ou de cerâmica, mesmo com partes de outras matérias\n\
0Pás, alviões, picaretas, enxadas, sachos, forcados e forquilhas, ancinhos e raspadeiras; machados, podões e ferramentas semelhantes com gume; tesouras de podar de todos os tipos; foices e foicinhas, facas para feno ou para palha, tesouras para sebes, cunhas e outras ferramentas manuais para agricultura, horticultura ou silvicultura\n\
0Folhas de serras de fita\n\
0Lâminas de serras máquinas\n\
0Serras manuais e outras folhas de serras (incluídas as fresas-serras e as folhas não dentadas para serrar), exceto as classificadas nos CEST 08.005.00 e 08.006.00\n\
0Limas, grosas, alicates (mesmo cortantes), tenazes, pinças, cisalhas para metais, corta-tubos, corta-pinos, saca-bocados e ferramentas semelhantes, manuais, exceto as pinças para sobrancelhas classificadas na posição 8203.20.90\n\
0Chaves de porcas, manuais (incluídas as chaves dinamométricas); chaves de caixa intercambiáveis, mesmo com cabos\n\
0Ferramentas manuais (incluídos os diamantes de vidraceiro) não especificadas nem compreendidas em outras posições, lamparinas ou lâmpadas de soldar (maçaricos) e semelhantes; tornos de apertar, sargentos e semelhantes, exceto os acessórios ou partes de máquinas-ferramentas; bigornas; forjas-portáteis; mós com armação, manuais ou de pedal\n\
cde pelo menos duas das posições 8202 a 8205, acondicionadas em sortidos para venda a retalho\n\
froscar interior ou exteriormente; de mandrilar ou de brochar; e de fresar\n\
0Outras ferramentas intercambiáveis para ferramentas manuais, mesmo mecânicas, ou para máquinas-ferramentas (por exemplo, de embutir, estampar, puncionar, furar, tornear, aparafusar), incluídas as fieiras de estiragem ou de extrusão, para metais, e as ferramentas de perfuração ou de sondagem, exceto forma ou gabarito de produtos em epoxy e as classificadas no CEST 08.012.00\n\
0Facas e lâminas cortantes, para máquinas ou para aparelhos mecânicos\n\
0Plaquetas ou pastilhas intercambiáveis\n\
0Outras plaquetas, varetas, pontas e objetos semelhantes para ferramentas, não montados, de ceramais (“cermets”), exceto as classificadas no CEST 08.015.00\n\
0Facas de lâmina cortante ou serrilhada, incluídas as podadeiras de lâmina móvel, e suas lâminas, exceto as de uso doméstico\n\
0Tesouras e suas lâminas\n\
0Ferramentas pneumáticas, hidráulicas ou com motor (elétrico ou não elétrico) incorporado, de uso manual, exceto o descrito no CEST 08.019.01\n\
0Moto-serras portáteis de corrente, com motor incorporado, não elétrico, de uso agrícola\n\
0Instrumentos e aparelhos de geodesia, topografia, agrimensura, nivelamento, fotogrametria, hidrografia, oceanografia, hidrologia, meteorologia ou de geofísica, exceto bussolas; telêmetros\n\
dde desenho, de traçado ou de cálculo; metros, micrômetros, paquímetros, calibres e semelhantes; partes e acessórios\n\
0Termômetros, suas partes e acessórios\n\
0Pirômetros, suas partes e acessórios\n\
0Lâmpadas elétricas\n\
betrônicas\n\
0Reatores para lâmpadas ou tubos de descargas\n\
0“Starter”\n\
0Lâmpadas de LED (diodos emissores de luz)\n\
0Cal\n\
0Argamassas\n\
0Outras argamassas\n\
0Silicones em formas primárias, para uso na construção\n\
0Revestimentos de PVC e outros plásticos; forro, sancas e afins de PVC, para uso na construção\n\
0Tubos, e seus acessórios (por exemplo, juntas, cotovelos, flanges, uniões), de plásticos, para uso na construção\n\
0Revestimento de pavimento de PVC e outros plásticos\n\
0Chapas, folhas, tiras, fitas, películas e outras formas planas, autoadesivas, de plásticos, mesmo em rolos, para uso na construção\n\
0Veda rosca, lona plástica para uso na construção, fitas isolantes e afins\n\
0Telha de plástico, mesmo reforçada com fibra de vidro\n\
0Cumeeira de plástico, mesmo reforçada com fibra de vidro\n\
1hapas, laminados plásticos em bobina, para uso na construção, exceto os descritos no CEST 10.010.00 e 10.011.00\n\
0Banheiras, boxes para chuveiros, pias, lavatórios, bidês, sanitários e seus assentos e tampas, caixas de descarga e artigos semelhantes para usos sanitários ou higiênicos, de plásticos\n\
0Artefatos de higiene/toucador de plástico, para uso na construção\n\
0Caixa d’água, inclusive sua tampa, de plástico, mesmo reforçadas com fibra de vidro\n\
0Outras telhas, cumeeira e caixa d’água, inclusive sua tampa, de plástico, mesmo reforçadas com fibra de vidro\n\
0Artefatos para apetrechamento de construções, de plásticos, não especificados nem compreendidos em outras posições, incluindo persianas, sancas, molduras, apliques e rosetas, caixilhos de polietileno e outros plásticos, exceto os descritos nos CEST 10.015.00 e 10.016.00\n\
0Portas, janelas e seus caixilhos, alizares e soleiras\n\
2stigos, estores (incluídas as venezianas) e artefatos semelhantes e suas partes\n\
0Outras obras de plástico, para uso na construção\n\
0Papel de parede e revestimentos de parede semelhantes; papel para vitrais\n\
0Telhas de concreto\n\
0Caixas d’água, tanques e reservatórios e suas tampas, telhas, calhas, cumeeiras e afins, de fibrocimento, cimento-celulose ou semelhantes, contendo ou não amianto\n\
0Tijolos, placas (lajes), ladrilhos e outras peças cerâmicas de farinhas siliciosas fósseis (“kieselghur”, tripolita, diatomita, por exemplo) ou de terras siliciosas semelhantes\n\
ze peças cerâmicas semelhantes, para uso na construção, refratários, que não sejam de farinhas siliciosas fósseis nem de terras siliciosas semelhantes\n\
7 para construção, tijoleiras, tapa-vigas e produtos semelhantes, de cerâmica\n\
1elhas, elementos de chaminés, condutores de fumaça, ornamentos arquitetônicos, de cerâmica, e outros produtos cerâmicos para uso na construção\n\
1ubos, calhas ou algerozes e acessórios para canalizações, de cerâmica\n\
0Ladrilhos e placas de cerâmica, exclusivamente para pavimentação ou revestimento\n\
0Cubos, pastilhas e artigos semelhantes de cerâmica, mesmo com suporte, exceto os descritos CEST 10.030.00\n\
0Pias, lavatórios, colunas para lavatórios, banheiras, bidês, sanitários, caixas de descarga, mictórios e aparelhos fixos semelhantes para usos sanitários, de cerâmica\n\
0Artefatos de higiene/toucador de cerâmica\n\
0Vidro vazado ou laminado, em chapas, folhas ou perfis, mesmo com camada absorvente, refletora ou não, mas sem qualquer outro trabalho\n\
6estirado ou soprado, em folhas, mesmo com camada absorvente, refletora ou não, mas sem qualquer outro trabalho\n\
6flotado e vidro desbastado ou polido em uma ou em ambas as faces, em chapas ou em folhas, mesmo com camada absorvente, refletora ou não, mas sem qualquer outro trabalho\n\
5s temperados\n\
7laminados\n\
7isolantes de paredes múltiplas\n\
0Blocos, placas, tijolos, ladrilhos, telhas e outros artefatos, de vidro prensado ou moldado, mesmo armado, para uso na construção; cubos, pastilhas e outros artigos semelhantes\n\
1arras próprias para construções, exceto vergalhões\n\
0Outras barras próprias para construções, exceto vergalhões\n\
4os vergalhões\n\
0Vergalhões\n\
0Outros vergalhões\n\
0Fios de ferro ou aço não ligados, não revestidos, mesmo polidos; cordas, cabos, tranças (entrançados), lingas e artefatos semelhantes, de ferro ou aço, não isolados para usos elétricos\n\
0Outros fios de ferro ou aço, não ligados, galvanizados com teor de carbono superior ou igual a 0,6%, em peso\n\
zgados, galvanizados\n\
0Acessórios para tubos (inclusive uniões, cotovelos, luvas ou mangas), de ferro fundido, ferro ou aço\n\
0Portas e janelas, e seus caixilhos, alizares e soleiras de ferro fundido, ferro ou aço\n\
0Material para andaimes, para armações (cofragens) e para escoramentos, (inclusive armações prontas, para estruturas de concreto armado ou argamassa armada), eletrocalhas e perfilados de ferro fundido, ferro ou aço, próprios para construção, exceto treliças de aço\n\
0Treliças de aço\n\
1elhas metálicas\n\
0Caixas diversas (tais como caixa de correio, de entrada de água, de energia, de instalação) de ferro fundido, ferro ou aço; próprias para a construção\n\
0Arame farpado, de ferro ou aço, arames ou tiras, retorcidos, mesmo farpados, de ferro ou aço, dos tipos utilizados em cercas\n\
0Telas metálicas, grades e redes, de fios de ferro ou aço\n\
0Correntes de rolos, de ferro fundido, ferro ou aço\n\
0Outras correntes de elos articulados, de ferro fundido, ferro ou aço\n\
0Correntes de elos soldados, de ferro fundido, de ferro ou aço\n\
0Tachas, pregos, percevejos, escápulas, grampos ondulados ou biselados e artefatos semelhantes, de ferro fundido, ferro ou aço, mesmo com a cabeça de outra matéria, exceto cobre\n\
0Parafusos, pinos ou pernos, roscados, porcas, tira-fundos, ganchos roscados, rebites, chavetas, contrapinos ou troços, arruelas (anilhas) (incluindo as de pressão) e artigos semelhantes, de ferro fundido, ferro ou aço\n\
2lha de ferro ou aço, exceto os de uso doméstico classificados na posição NCM 7323.10.00\n\
0Esponjas, esfregões, luvas e artefatos semelhantes para limpeza, polimento e usos semelhantes, de ferro ou aço, exceto os de uso doméstico classificados na posição NCM 7323.10.00\n\
0Artefatos de higiene ou de toucador, e suas partes, de ferro fundido, ferro ou aço, incluídas as pias, banheiras, lavatórios, cubas, mictórios, tanques e afins de ferro fundido, ferro ou aço, para uso na construção\n\
0Outras obras moldadas, de ferro fundido, ferro ou aço, para uso na construção\n\
0Abraçadeiras\n\
0Barras de cobre\n\
0Tubos de cobre e suas ligas, para instalações de água quente e gás, para uso na construção\n\
0Acessórios para tubos (por exemplo, uniões, cotovelos, luvas ou mangas) de cobre e suas ligas, para uso na construção\n\
0Tachas, pregos, percevejos, escápulas e artefatos semelhantes, de cobre, ou de ferro ou aço com cabeça de cobre, parafusos, pinos ou pernos, roscados, porcas, ganchos roscados, rebites, chavetas, cavilhas, contrapinos, arruelas (incluídas as de pressão), e artefatos semelhantes, de cobre\n\
0Artefatos de higiene/toucador de cobre, para uso na construção\n\
0Manta de subcobertura aluminizada\n\
0Tubos de alumínio e suas ligas, para refrigeração e ar condicionado, para uso na construção\n\
0Acessórios para tubos (por exemplo, uniões, cotovelos, luvas ou mangas), de alumínio, para uso na construção\n\
0Construções e suas partes (por exemplo, pontes e elementos de pontes, torres, pórticos ou pilones, pilares, colunas, armações, estruturas para telhados, portas e janelas, e seus caixilhos, alizares e soleiras, balaustradas), de alumínio, exceto as construções pré-fabricadas da posição 9406; chapas, barras, perfis, tubos e semelhantes, de alumínio, próprios para construções\n\
0Artefatos de higiene/toucador de alumínio, para uso na construção\n\
0Outras obras de alumínio, próprias para construções, incluídas as persianas\n\
7guarnições, ferragens e artigos semelhantes de metais comuns, para construções, inclusive puxadores\n\
0Fechaduras e ferrolhos (de chave, de segredo ou elétricos), de metais comuns, incluídas as suas partes fechos e armações com fecho, com fechadura, de metais comuns chaves para estes artigos, de metais comuns; exceto os de uso automotivo\n\
0Dobradiças de metais comuns, de qualquer tipo\n\
0Tubos flexíveis de metais comuns, mesmo com acessórios, para uso na construção\n\
0Fios, varetas, tubos, chapas, eletrodos e artefatos semelhantes, de metais comuns ou de carbonetos metálicos, revestidos exterior ou interiormente de decapantes ou de fundentes, para soldagem (soldadura) ou depósito de metal ou de carbonetos metálicos fios e varetas de pós de metais comuns aglomerados, para metalização por projeção\n\
0Torneiras, válvulas (incluídas as redutoras de pressão e as termostáticas) e dispositivos semelhantes, para canalizações, caldeiras, reservatórios, cubas e outros recipientes\n\
0Espelhos de vidro, mesmo emoldurados, exceto os de uso automotivo\n\
0Água sanitária, branqueador e outros alvejantes\n\
0Sabões, desinfetantes e sanitizantes, todos em pó, flocos, palhetas, grânulos ou outras formas semelhantes, para lavar roupas\n\
zs, todos líquidos para lavar roupas\n\
0Detergentes em pó, flocos, palhetas, grânulos ou outras formas semelhantes, inclusive adicionados de propriedades desinfetantes ou sanitizantes\n\
clíquidos, exceto para lavar roupa\n\
a líquido para lavar roupa, inclusive adicionados de propriedades desinfetantes ou sanitizantes\n\
0Outros agentes orgânicos de superfície (exceto sabões); preparações tensoativas, preparações para lavagem (incluídas as preparações auxiliares para lavagem) e preparações para limpeza (inclusive multiuso e limpadores), mesmo contendo sabão, exceto os produtos descritos nos CEST 11.001.00, 11.004.00, 11.005.00 e 11.006.00; em embalagem de conteúdo inferior ou igual a 50 litros ou 50 kg\n\
0Amaciante/suavizante\n\
0Esponjas para limpeza\n\
0Álcool etílico para limpeza\n\
0Esponjas e palhas de aço; esponjas para limpeza, polimento ou uso semelhantes; todas de uso doméstico\n\
0Sacos de lixo de conteúdo igual ou inferior a 100 litros\n\
0Transformadores, bobinas de reatância e de auto indução, inclusive os transformadores de potência superior a 16 KVA, classificados nas posições 8504.33.00 e 8504.34.00; exceto os demais transformadores da subposição 8504.3, os reatores para lâmpadas elétricas de descarga classificados no código 8504.10.00, os carregadores de acumuladores do código 8504.40.10, os equipamentos de alimentação ininterrupta de energia (UPS ou “no break”), no código 8504.40.40 e os de uso automotivo\n\
0Aquecedores elétricos de água, incluídos os de imersão, chuveiros ou duchas elétricos, torneiras elétricas, resistências de aquecimento, inclusive as de duchas e chuveiros elétricos e suas partes; exceto outros fornos, fogareiros (incluídas as chapas de cocção), grelhas e assadeiras, classificados na posição 8516.60.00\n\
1parelhos para interrupção, seccionamento, proteção, derivação, ligação ou conexão de circuitos elétricos (por exemplo, interruptores, comutadores, corta-circuitos, para-raios, limitadores de tensão, eliminadores de onda, tomadas de corrente e outros conectores, caixas de junção), para tensão superior a 1.000V, exceto os de uso automotivo\n\
zamento, proteção, derivação, ligação ou conexão de circuitos elétricos (por exemplo, interruptores, comutadores, relés, corta-circuitos, eliminadores de onda, plugues e tomadas de corrente, suportes para lâmpadas e outros conectores, caixas de junção), para uma tensão não superior a 1.000V; conectores para fibras ópticas, feixes ou cabos de fibras ópticas; exceto “starter” classificado na subposição 8536.50 e os de uso automotivo\n\
0Partes reconhecíveis como exclusiva ou principalmente destinadas aos aparelhos das posições 8535 e 8536\n\
0Cabos, tranças e semelhantes, de cobre, não isolados para usos elétricos, exceto os de uso automotivo\n\
0Fios, cabos (incluídos os cabos coaxiais) e outros condutores, isolados ou não, para usos elétricos (incluídos os de cobre ou alumínio, envernizados ou oxidados anodicamente), mesmo com peças de conexão, inclusive fios e cabos elétricos, para tensão não superior a 1000V, para uso na construção; fios e cabos telefônicos e para transmissão de dados; cabos de fibras ópticas, constituídos de fibras embainhadas individualmente, mesmo com condutores elétricos ou munidos de peças de conexão; cordas, cabos, tranças e semelhantes, de alumínio, não isolados para uso elétricos; exceto os de uso automotivo\n\
0Isoladores de qualquer matéria, para usos elétricos\n\
0Peças isolantes inteiramente de matérias isolantes, ou com simples peças metálicas de montagem (suportes roscados, por exemplo) incorporadas na massa, para máquinas, aparelhos e instalações elétricas; tubos isoladores e suas peças de ligação, de metais comuns, isolados interiormente\n\
0Medicamentos de referência - positiva, exceto para uso veterinário\n\
tnegativa, exceto para uso veterinário\n\
vutra, exceto para uso veterinário\n\
dgenérico - positiva, exceto para uso veterinário\n\
onegativa, exceto para uso veterinário\n\
qutra, exceto para uso veterinário\n\
dsimilar - positiva, exceto para uso veterinário\n\
nnegativa, exceto para uso veterinário\n\
putra, exceto para uso veterinário\n\
0Outros tipos de medicamentos - positiva, exceto para uso veterinário\n\
vnegativa, exceto para uso veterinário\n\
xutra, exceto para uso veterinário\n\
0Preparações químicas contraceptivas de referência, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas - positiva\n\
z de referência, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas - negativa\n\
z genérico, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas – positiva\n\
z genérico, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas – negativa\n\
z similar, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas – positiva\n\
z similar, à base de hormônios, de outros produtos da posição 29.37 ou de espermicidas – negativa\n\
2ovitaminas e vitaminas, naturais ou reproduzidas por síntese (incluídos os concentrados naturais), bem como os seus derivados utilizados principalmente como vitaminas, misturados ou não entre si, mesmo em quaisquer soluções - neutra\n\
2eparações opacificantes (contrastantes) para exames radiográficos e reagentes de diagnóstico concebidos para serem administrados ao paciente - positiva\n\
zantes) para exames radiográficos e reagentes de diagnóstico concebidos para serem administrados ao paciente - negativa\n\
0Antissoro, outras frações do sangue, produtos imunológicos modificados, mesmo obtidos por via biotecnológica, exceto para uso veterinário - positiva\n\
z, produtos imunológicos modificados, mesmo obtidos por via biotecnológica, exceto para uso veterinário - negativa\n\
0Vacinas e produtos semelhantes, exceto para uso veterinário - positiva\n\
zeto para uso veterinário - negativa\n\
0Curativos (pensos) adesivos e outros artigos com uma camada adesiva, impregnados ou recobertos de substâncias farmacêuticas - Lista Positiva\n\
zs artigos com uma camada adesiva, impregnados ou recobertos de substâncias farmacêuticas - Lista Negativa\n\
0Algodão, atadura, esparadrapo, gazes, pensos, sinapismos, e outros, acondicionados para venda a retalho para usos medicinais, cirúrgicos ou dentários, não impregnados ou recobertos de substâncias farmacêuticas - Lista Neutra\n\
0Luvas cirúrgicas e luvas de procedimento - neutra\n\
0Preservativo – neutra\n\
0Seringas, mesmo com agulhas - neutra\n\
0Agulhas para seringas - neutra\n\
0Contraceptivos (dispositivos intrauterinos - DIU) - neutra\n\
0Objetos de vidro para serviço de mesa ou de cozinha\n\
1utros copos, exceto de vitrocerâmica\n\
1bjetos para serviço de mesa (exceto copos) ou de cozinha, exceto de vitrocerâmica\n\
0Lonas plásticas, exceto as para uso na construção\n\
0Artefatos de higiene/toucador de plástico, exceto os para uso na construção\n\
0Serviços de mesa e outros utensílios de mesa ou de cozinha, de plástico, não descartáveis\n\
zs de mesa ou de cozinha, de plástico, descartáveis\n\
0Artigos para serviço de mesa ou de cozinha, de porcelana, inclusive os descartáveis - estojos\n\
zcozinha, de porcelana, inclusive os descartáveis - avulsos\n\
zcozinha, de cerâmica\n\
0Velas para filtros\n\
0Filtros descartáveis para coar café ou chá\n\
0Bandejas, travessas, pratos, xícaras ou chávenas, taças, copos e artigos semelhantes, de papel ou cartão\n\
0Papel para cigarro\n\
1neus novos, dos tipos utilizados em automóveis de passageiros (incluídos os veículos de uso misto - camionetas e os automóveis de corrida)\n\
zm caminhões (inclusive para os fora-de-estrada), ônibus, aviões, máquinas de terraplenagem, de construção e conservação de estradas, máquinas e tratores agrícolas, pá-carregadeira\n\
b para motocicletas\n\
0Outros tipos de pneus novos, exceto os itens classificados no CEST 16.005.00\n\
0Pneus novos de borracha dos tipos utilizados em bicicletas\n\
6recauchutados\n\
1rotetores de borracha, exceto os itens classificados no CEST 16.007.01\n\
m para bicicletas\n\
0Câmaras de ar de borracha, exceto os itens classificados no CEST 16.009.00\n\
p dos tipos utilizados em bicicletas\n\
1hocolate branco, em embalagens de conteúdo inferior ou igual a 1 kg, exceto os classificados no CEST 17.005.00\n\
zconteúdo superior a 1 kg e inferior ou igual a 2 kg, exceto os classificados no CEST 17.005.00\n\
1oberturas de chocolate branco e outros produtos de confeitaria com manteiga de cacau, em embalagens de conteúdo inferior ou igual a 1 kg, exceto os classificados no CEST 17.008.00\n\
ztros produtos de confeitaria com manteiga de cacau, em embalagens de conteúdo superior a 1 kg e inferior ou igual a 2 kg, exceto os classificados no CEST 17.008.00\n\
1hocolates, em tabletes, barras ou paus, recheados, em recipientes ou embalagens imediatas de conteúdo inferior ou igual a 1 kg\n\
zpaus, recheados, em recipientes ou embalagens de conteúdo superior a 1 kg e inferior ou igual a 2 kg\n\
0Outras preparações alimentícias que contenham cacau, em tabletes, barras ou paus, recheados, em recipientes ou embalagens imediatas de conteúdo inferior ou igual a 1 kg\n\
z contenham cacau, em tabletes, barras ou paus, recheados, em recipientes ou embalagens de conteúdo superior a 1 kg e inferior ou igual a 2 kg\n\
0Chocolates, em tabletes, barras ou paus, não recheados, em recipientes ou embalagens imediatas de conteúdo inferior ou igual a 2 kg\n\
0Outras preparações alimentícias que contenham cacau, em tabletes, barras ou paus, não recheados, em recipientes ou embalagens imediatas de conteúdo inferior ou igual a 2 kg\n\
0Chocolates e outras preparações alimentícias contendo cacau, em embalagens de conteúdo inferior ou igual a 1 kg, exceto os classificados nos CEST 17.005.01, 17.006.00, 17.006.02, 17.007.00 e 17.109.00\n\
zmentícias contendo cacau, em embalagens de conteúdo superior a 1 kg e inferior ou igual a 2 kg, exceto os classificados nos CEST 17.005.01, 17.006.00, 17.006.02 e 17.007.00\n\
0Ovos de páscoa de chocolate branco\n\
r\n\
0Achocolatados em pó, em embalagens de conteúdo inferior ou igual a 1 kg, exceto os classificados no CEST 17.006.02\n\
0Cacau em pó, com adição de açúcar ou de outros edulcorantes, em embalagens de conteúdo inferior ou igual a 1kg\n\
0Achocolatados em pó, em cápsulas\n\
0Caixas de bombons contendo cacau, em embalagens de conteúdo inferior ou igual a 1 kg\n\
0Bombons, inclusive à base de chocolate branco sem cacau\n\
9balas, caramelos, confeitos, pastilhas e outros produtos de confeitaria, contendo cacau\n\
0Sucos de frutas ou de produtos hortícolas; mistura de sucos\n\
0Água de coco\n\
0Leite em pó, blocos ou grânulos, exceto creme de leite\n\
0Farinha láctea\n\
0Leite modificado para alimentação de crianças\n\
0Preparações para alimentação infantil à base de farinhas, grumos, sêmolas ou amidos e outros\n\
0Leite “longa vida” (UHT - “Ultra High Temperature”), em recipiente de conteúdo inferior ou igual a 2 litros\n\
zgh Temperature”), em recipiente de conteúdo superior a 2 litros e inferior ou igual a 5 litros\n\
6em recipiente de conteúdo inferior ou igual a 1 litro\n\
wsuperior a 1 litro e inferior ou igual a 5 litros\n\
6do tipo pasteurizado em recipiente de conteúdo inferior ou igual a 1 litro\n\
ziente de conteúdo superior a 1 litro e inferior ou igual a 5 litros\n\
0Creme de leite, em recipiente de conteúdo inferior ou igual a 1 kg\n\
znteúdo superior a 1 kg\n\
0Outros cremes de leite, em recipiente de conteúdo inferior ou igual a 1kg\n\
zte de conteúdo superior a 1kg\n\
0Leite condensado, em recipiente de conteúdo inferior ou igual a 1 kg\n\
zconteúdo superior a 1 kg\n\
0Iogurte e leite fermentado em recipiente de conteúdo inferior ou igual a 2 litros, exceto o item classificado no CEST 17.022.00\n\
ziente de conteúdo superior a 2 litros, exceto o item classificado no CEST 17.022.00\n\
0Coalhada\n\
0Requeijão e similares, em recipiente de conteúdo inferior ou igual a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
ze de conteúdo superior a 1 kg\n\
0Queijos, exceto os dos CEST 17.024.01, 17.024.02, 17.024.03, 17.024.04 e 17.024.05\n\
6 muçarela\n\
8inas frescal\n\
7ricota\n\
7petitsuisse\n\
7cremoso (“cream cheese”)\n\
0Manteiga, em embalagem de conteúdo inferior ou igual a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
zsuperior a 1 kg\n\
8 de garrafa\n\
2rgarina e creme vegetal em recipiente de conteúdo inferior ou igual a 500 g, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
p, em recipiente de conteúdo superior a 500 g e inferior ou igual a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
ziente de conteúdo superior a 1 kg\n\
0Outras margarinas e cremes vegetais em recipiente de conteúdo inferior a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
0Gorduras e óleos vegetais e respectivas frações, parcial ou totalmente hidrogenados, interesterificados, reesterificados ou elaidinizados, mesmo refinados, mas não preparados de outro modo, em recipiente de conteúdo inferior ou igual a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
zivas frações, parcial ou totalmente hidrogenados, interesterificados, reesterificados ou elaidinizados, mesmo refinados, mas não preparados de outro modo, em recipiente de conteúdo superior a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
0Doces de leite\n\
0Produtos à base de cereais, obtidos por expansão ou torrefação\n\
0Salgadinhos diversos, exceto os classificados no CEST 17.031.01 e 17.031.02\n\
mderivados de farinha de trigo\n\
0Biscoitos de polvilho\n\
1atata frita, inhame e mandioca fritos\n\
0Amendoim e castanhas tipo aperitivo, em embalagem de conteúdo inferior ou igual a 1 kg\n\
z, em embalagem de conteúdo superior a 1 kg\n\
0Catchup em embalagens imediatas de conteúdo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
1ondimentos e temperos compostos, incluindo molho de pimenta e outros molhos, em embalagens imediatas de conteúdo inferior ou igual a 1 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 3 g\n\
0Molhos de soja preparados em embalagens imediatas de conteúdo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
0Farinha de mostarda em embalagens de conteúdo inferior ou igual a 1 kg\n\
0Mostarda preparada em embalagens imediatas de conteúdo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
1aionese em embalagens imediatas de conteúdo inferior ou igual a 650 g, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
0Tomates preparados ou conservados, exceto em vinagre ou em ácido acético, em embalagens de conteúdo inferior ou igual a 1 kg\n\
0Molhos de tomate em embalagens imediatas de conteúdo inferior ou igual a 1 kg\n\
0Barra de cereais\n\
g contendo cacau\n\
0Farinha de trigo especial, em embalagem inferior ou igual a 1 kg\n\
zagem superior a 1 kg e inferior a 5 kg\n\
zagem igual a 5 kg\n\
zagem superior a 5 kg e inferior ou igual a 25 kg\n\
zagem superior a 25 kg e inferior ou igual a 50 kg\n\
hcomum, em embalagem igual a 5 kg\n\
zm superior a 5 kg e inferior ou igual a 25 kg\n\
zm superior a 25 kg e inferior ou igual a 50 kg\n\
hdoméstica especial, em embalagem superior a 5 kg e inferior e igual a 10 kg\n\
rcom fermento, em embalagem superior a 5 kg e inferior e igual a 10 kg\n\
hespecial, em embalagem superior a 50 Kg\n\
hcomum, em embalagem inferior ou igual a 1 kg\n\
zm superior a 1 kg e inferior a 5 Kg\n\
zm superior a 50 kg\n\
hdoméstica especial, em embalagem inferior ou igual a 1 kg\n\
z, em embalagem superior a 1 kg e inferior a 5 Kg\n\
z, em embalagem igual a 5 Kg\n\
z, em embalagem superior a 10 Kg\n\
rcom fermento, em embalagem inferior ou igual a 1 kg\n\
zento, em embalagem superior a 1 kg e inferior a 5 Kg\n\
zento, em embalagem igual a 5 Kg\n\
zento, em embalagem superior a 10 Kg\n\
0Outras farinhas de trigo, em embalagem inferior ou igual a 1 kg\n\
zgem superior a 1 kg e inferior a 5 Kg\n\
zgem igual a 5 Kg\n\
zgem superior a 5 Kg e inferior ou igual a 25 kg\n\
zgem superior a 25 Kg e inferior ou igual a 50 kg\n\
zgem superior a 50 Kg\n\
0Farinha de mistura de trigo com centeio (méteil)\n\
0Misturas e preparações para bolos, em embalagem inferior 5 kg\n\
zem embalagem igual a 5 kg\n\
zem embalagem superior a 5 kg e inferior ou igual a 25 Kg\n\
zem embalagem superior a 25 kg e inferior ou igual a 50 Kg\n\
zem embalagem superior a 50 Kg\n\
spães com menos de 80% de farinha de trigo na sua composição final, em embalagem inferior a 5 kg\n\
zm menos de 80% de farinha de trigo na sua composição final, em embalagem igual a 5 kg\n\
zm menos de 80% de farinha de trigo na sua composição final, em embalagem superior a 5 kg e inferior ou igual a 25 Kg\n\
zm menos de 80% de farinha de trigo na sua composição final, em embalagem superior a 25 kg e inferior ou igual a 50 Kg\n\
zm menos de 80% de farinha de trigo na sua composição final, em embalagem superior a 50 Kg\n\
zm, no mínimo, 80% de farinha de trigo na sua composição final, em embalagem inferior a 5 kg\n\
zm, no mínimo, 80% de farinha de trigo na sua composição final, em embalagem igual a 5 kg\n\
zm, no mínimo, 80% de farinha de trigo na sua composição final, em embalagem superior a 5 kg e inferior ou igual a 25 Kg\n\
zm, no mínimo, 80% de farinha de trigo na sua composição final, em embalagem superior a 25 kg e inferior ou igual a 50 Kg\n\
zm, no mínimo, 80% de farinha de trigo na sua composição final, em embalagem superior a 50 Kg\n\
castas para a preparação de produtos de padaria, pastelaria e da indústria de bolachas e biscoitos, da posição 19.05, exceto os previstos nos CEST 17.046.00 a 17.046.14 e 17.046.16\n\
creparações com, no mínimo, 80% de farinha de trigo na sua composição final, exceto as descritas nos CEST 17.046.10 a 17.046.15\n\
1assas alimentícias tipo instantânea, exceto as descritas no CEST 17047.01\n\
za, derivadas de farinha de trigo\n\
j, cozidas ou recheadas (de carne ou de outras substâncias) ou preparadas de outro modo, exceto as descritas nos CEST 17.047.00, 17.048.01, e 17.048.02\n\
0Cuscuz\n\
0Massas alimentícias recheadas (mesmo cozidas ou preparadas de outro modo)\n\
kdo tipo comum, não cozidas, nem recheadas, nem preparadas de outro modo, não derivadas do trigo\n\
ssêmola, não cozidas, nem recheadas, nem preparadas de outro modo, não derivadas do trigo\n\
sgrano duro, não cozidas, nem recheadas, nem preparadas de outro modo, que contenham ovos\n\
0Outras massas alimentícias do tipo comum, não cozidas, nem recheadas, nem preparadas de outro modo, que não contenham ovos, derivadas de farinha de trigo\n\
zsêmola, não cozidas, nem recheadas, nem preparadas de outro modo, que não contenham ovos, derivadas do trigo\n\
zgrano duro, não cozidas, nem recheadas, nem preparadas de outro modo, que não contenham ovos\n\
0Massas alimentícias do tipo comum, não cozidas, nem recheadas, nem preparadas de outro modo, que contenham ovos, derivadas de farinha de trigo\n\
ssêmola, não cozidas, nem recheadas, nem preparadas de outro modo, que contenham ovos, derivadas do trigo\n\
0Pães industrializados, inclusive de especiarias, exceto panetones e bolo de forma\n\
0Bolo de forma, inclusive de especiarias\n\
0Panetones\n\
0Biscoitos e bolachas derivados de farinha de trigo; (exceto dos tipos “cream cracker”, “água e sal”, “maisena”, “maria” e outros de consumo popular que não sejam adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominação comercial)\n\
zarinha de trigo dos tipos “maisena” e “maria” e outros de consumo popular que não sejam adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominação comercial, exceto o CEST 17.053.02\n\
zarinha de trigo dos tipos "cream cracker" e "água e sal" de consumo popular\n\
lnão derivados de farinha de trigo; (exceto dos tipos "cream cracker", "água e sal", "maisena" e "maria" e outros de consumo popular que não sejam adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominação comercial)\n\
zde farinha de trigo dos tipos "maisena" e "maria" e outros de consumo popular que não sejam adicionados de cacau, nem recheados, cobertos ou amanteigados, independentemente de sua denominação comercial, exceto o CEST 17.054.02\n\
zde farinha de trigo dos tipos "cream cracker" e "água e sal" de consumo popular\n\
lderivados de farinha de trigo dos tipos “cream cracker” e “água e sal”\n\
lnão derivados de farinha de trigo dos tipos “cream cracker” e “água e sal”\n\
0Outras bolachas, exceto casquinhas para sorvete e os biscoitos e bolachas relacionados nos CEST 17.056.00 e 17.056.01\n\
0“Waffles” e “wafers” - sem cobertura\n\
ncom cobertura\n\
0Torradas, pão torrado e produtos semelhantes torrados\n\
0Outros pães de forma\n\
b, exceto o classificado no CEST 17.062.03\n\
7bolos industrializados e produtos de panificação não especificados anteriormente, incluindo as pizzas; exceto os classificados nos CEST 17.062.02 e 17.062.03\n\
0Casquinhas para sorvete\n\
0Pão francês até 200g\n\
4denominado knackebrot\n\
0Demais pães industrializados\n\
0Óleo de soja refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
8amendoim refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
0Azeites de oliva, em recipientes com capacidade inferior a 2 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 20 mililitros\n\
zm capacidade igual ou superior a 2 litros e inferior ou igual a 5 litros\n\
zm capacidade superior a 5 litros\n\
0Outros óleos e respectivas frações, obtidos exclusivamente a partir de azeitonas, mesmo refinados, mas não quimicamente modificados, e misturas desses óleos ou frações com óleos ou frações da posição 15.09, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
0Óleo de girassol em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
8algodão refinado em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
8canola, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
8linhaça refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
8milho refinado, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
0Outros óleos refinados, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
0Misturas de óleos refinados, para consumo humano, em recipientes com capacidade inferior ou igual a 5 litros, exceto as embalagens individuais de conteúdo inferior ou igual a 15 mililitros\n\
0Outros óleos vegetais comestíveis não especificados anteriormente\n\
0Enchidos (embutidos) e produtos semelhantes, de carne, miudezas ou sangue; exceto salsicha, linguiça e mortadela\n\
0Salsicha e linguiça, exceto as descritas nos CEST 17.077.01\n\
am lata\n\
0Mortadela\n\
0Outras preparações e conservas de carne, miudezas ou de sangue, exceto as descritas nos CEST 17.079.01, 17.079.02, 17.079.03, 17.079.04, 17.079.05, 17.079.06, 17.079.07 e 17.079.08\n\
zarne, de miudezas ou de sangue, de aves da posição 01.05: de peruas e de perus, exceto as descritas no CEST 17.079.08\n\
zarne, de miudezas ou de sangue, de aves da posição 01.05: de galos e de galinhas, com conteúdo de carne ou de miudezas superior ou igual a 57 %, em peso, não cozidas, exceto as descritas no CEST 17.079.08\n\
zarne, de miudezas ou de sangue, de aves da posição 01.05: de galos e de galinhas, com conteúdo de carne ou de miudezas superior ou igual a 57 %, em peso, cozidas, exceto as descritas no CEST 17.079.08\n\
zarne, de miudezas ou de sangue, da espécie suína: pernas e respectivos pedaços\n\
zarne, de miudezas ou de sangue, da espécie suína: outras, incluindo as misturas, exceto os descritos no CEST 17.079.07\n\
zarne, de miudezas ou de sangue, da espécie bovina\n\
0Apresuntado\n\
0Carnes de aves inteiras e com peso unitário superior a 3 kg, temperadas\n\
0Preparações e conservas de peixes; caviar e seus sucedâneos preparados a partir de ovas de peixe; exceto os descritos nos CEST 17.080.01 e 17.081.00\n\
0Outras preparações e conservas de atuns\n\
0Sardinha em conserva\n\
0Crustáceos, moluscos e outros invertebrados aquáticos, preparados ou em conservas\n\
1arne de gado bovino, ovino e bufalino e produtos comestíveis resultantes da matança desse gado submetidos à salga, secagem ou desidratação, exceto os descritos no CEST 17.083.01\n\
1harque e jerkedbeef\n\
1arne de gado bovino, ovino e bufalino e demais produtos comestíveis resultantes da matança desse gado frescos, refrigerados ou congelados\n\
5s de animais das espécies caprina, frescas, refrigeradas ou congeladas\n\
7e demais produtos comestíveis frescos, resfriados, congelados, salgados ou salmourados resultantes do abate de caprinos\n\
zs frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de aves, exceto os descritos no CEST 17.087.02\n\
zs frescos, resfriados, congelados, salgados, em salmoura, simplesmente temperados, secos ou defumados, resultantes do abate de suínos\n\
7de aves inteiras e com peso unitário superior a 3 kg\n\
0Produtos hortícolas, cozidos em água ou vapor, congelados, em embalagens de conteúdo inferior ou igual a 1 kg\n\
za ou vapor, congelados, em embalagens de conteúdo superior a 1 kg\n\
0Frutas, não cozidas ou cozidas em água ou vapor, congeladas, mesmo adicionadas de açúcar ou de outros edulcorantes, em embalagens de conteúdo inferior ou igual a 1 kg\n\
zgua ou vapor, congeladas, mesmo adicionadas de açúcar ou de outros edulcorantes, em embalagens de conteúdo superior a 1 kg\n\
0Produtos hortícolas, frutas e outras partes comestíveis de plantas, preparados ou conservados em vinagre ou em ácido acético, em embalagens de conteúdo inferior ou igual a 1 kg\n\
zs partes comestíveis de plantas, preparados ou conservados em vinagre ou em ácido acético, em embalagens de conteúdo superior a 1 kg\n\
0Outros produtos hortícolas preparados ou conservados, exceto em vinagre ou em ácido acético, congelados, com exceção dos produtos da posição 20.06, em embalagens de conteúdo inferior ou igual a 1 kg\n\
zos ou conservados, exceto em vinagre ou em ácido acético, congelados, com exceção dos produtos da posição 20.06, em embalagens de conteúdo superior a 1 kg\n\
zos ou conservados, exceto em vinagre ou em ácido acético, não congelados, com exceção dos produtos da posição 20.06, excluídos batata, inhame e mandioca fritos, em embalagens de conteúdo inferior ou igual a 1 kg\n\
zos ou conservados, exceto em vinagre ou em ácido acético, não congelados, com exceção dos produtos da posição 20.06, excluídos batata, inhame e mandioca fritos, em embalagens de conteúdo superior a 1 kg\n\
0Produtos hortícolas, frutas, cascas de frutas e outras partes de plantas, conservados com açúcar (passados por calda, glaceados ou cristalizados), em embalagens de conteúdo inferior ou igual a 1 kg\n\
z de frutas e outras partes de plantas, conservados com açúcar (passados por calda, glaceados ou cristalizados), em embalagens de conteúdo superior a 1 kg\n\
0Doces, geleias, “marmelades”, purês e pastas de frutas, obtidos por cozimento, com ou sem adição de açúcar ou de outros edulcorantes, em embalagens de conteúdo inferior ou igual a 1 kg, exceto as embalagens individuais de conteúdo inferior ou igual a 10 g\n\
z e pastas de frutas, obtidos por cozimento, com ou sem adição de açúcar ou de outros edulcorantes, em embalagens de conteúdo superior a 1 kg\n\
0Frutas e outras partes comestíveis de plantas, preparadas ou conservadas de outro modo, com ou sem adição de açúcar ou de outros edulcorantes ou de álcool, não especificadas nem compreendidas em outras posições, excluídos os amendoins e castanhas tipo aperitivo, da posição 2008.1, em embalagens de conteúdo inferior ou igual a 1 kg\n\
zde plantas, preparadas ou conservadas de outro modo, com ou sem adição de açúcar ou de outros edulcorantes ou de álcool, não especificadas nem compreendidas em outras posições, excluídos os amendoins e castanhas tipo aperitivo, da posição 2008.1, em embalagens superior a 1 kg\n\
0Café torrado e moído, em embalagens de conteúdo inferior ou igual a 2 kg, exceto os classificados nos CEST 17.096.04 e 17.096.05\n\
z de conteúdo superior a 2 kg\n\
em grão, em embalagens de conteúdo inferior ou igual a 2 kg\n\
z de conteúdo superior a 2 kg\n\
e moído, em cápsulas, exceto os descritos no CEST 17.096.05\n\
5descafeinado torrado e moído, em cápsulas\n\
1há, mesmo aromatizado\n\
0Mate\n\
0Açúcar refinado, em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
zonteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
zonteúdo superior a 5 kg\n\
f adicionado de aromatizante ou de corante em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
ztizante ou de corante em embalagens de conteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
ztizante ou de corante em embalagens de conteúdo superior a 5 kg\n\
7cristal, em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
znteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
znteúdo superior a 5 kg\n\
e adicionado de aromatizante ou de corante, em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
zizante ou de corante, em embalagens de conteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
zizante ou de corante, em embalagens de conteúdo superior a 5 kg\n\
0Outros tipos de açúcar, em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
zns de conteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
zns de conteúdo superior a 5 kg\n\
m adicionado de aromatizante ou de corante, em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
ze aromatizante ou de corante, em embalagens de conteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
ze aromatizante ou de corante, em embalagens de conteúdo superior a 5 kg\n\
7açúcares em embalagens de conteúdo inferior ou igual a 2 kg, exceto as embalagens contendo envelopes individualizados (sachês) de conteúdo inferior ou igual a 10 g\n\
f, em embalagens de conteúdo superior a 2 kg e inferior ou igual a 5 kg\n\
zonteúdo superior a 5 kg\n\
0Milho para pipoca (micro-ondas)\n\
0Extratos, essências e concentrados de café e preparações à base destes extratos, essências ou concentrados ou à base de café, em embalagens de conteúdo inferior ou igual a 500 g, exceto os classificados no CEST 17.107.01\n\
zde café e preparações à base destes extratos, essências ou concentrados ou à base de café, em cápsulas\n\
zde chá ou de mate e preparações à base destes extratos, essências ou concentrados ou à base de chá ou de mate, em embalagens de conteúdo inferior ou igual a 500 g, exceto as bebidas prontas à base de mate ou chá e os itens classificados no CEST 17.108.01\n\
zde chá ou de mate e preparações à base destes extratos, essências ou concentrados ou à base de chá ou de mate, em cápsulas\n\
0Preparações em pó para cappuccino e similares, em embalagens de conteúdo inferior ou igual a 500 g\n\
0Refrescos e outras bebidas prontas para beber, à base de chá e mate\n\
rnão alcoólicas, exceto os refrigerantes e as demais bebidas nos CEST 03.007.00 e 17.110.00\n\
0Néctares de frutas e outras bebidas não alcoólicas prontas para beber, exceto bebidas hidroeletrolíticas e energéticos\n\
0Bebidas prontas à base de mate ou chá\n\
qcafé\n\
8alimentares prontas à base de soja, leite ou cacau, inclusive os produtos denominados bebidas lácteas\n\
0Sementes de anis (erva-doce), badiana (anis-estrelado), funcho, coentro, cominho ou alcaravia; bagas de zimbro; fruta seca, misturas de fruta seca ou de fruta de casa rija; quando acondicionadas em saquinhos, especialmente, para a preparação de infusões ou de tisanas (“chás”)\n\
0Outras preparações em blocos ou em barras, com peso superior a 2kg, ou no estado líquido, em pasta, em pó, grânulos ou formas semelhantes, em recipientes ou embalagens imediatas de conteúdo superior a 2kg\n\
0Tinta guache\n\
0Espiral - perfil para encadernação, de plástico e outros materiais classificados nas posições 3901 a 3914\n\
0Outros espirais - perfil para encadernação, de plástico e outros materiais classificados nas posições 3901 a 3914\n\
0Artigos de escritório e artigos escolares de plástico e outros materiais classificados nas posições 3901 a 3914, exceto estojos\n\
0Maletas e pastas para documentos e de estudante, e artefatos semelhantes\n\
0Baús, malas e maletas para viagem\n\
0Prancheta de plástico\n\
0Bobina para fax\n\
0Papel seda\n\
0Bobina para máquina de calcular, PDV ou equipamentos similares\n\
0Cartolina escolar e papel cartão, brancos e coloridos, cortados em folhas em que um lado seja inferior ou igual a 500 mm e o outro inferior ou igual a 700 mm, quando não dobradas, e peso igual ou superior a 120g/m²; recados autoadesivos (LP note); papéis de presente; todos cortados em tamanho pronto para uso escolar e doméstico\n\
0Papel fotográfico, exceto: (i) os papéis fotográficos emulsionados com haleto de prata tipo brilhante, matte ou lustre, em rolo e, com largura igual ou superior a 102 mm e comprimento inferior ou igual a 350 m, (ii) os papéis fotográficos emulsionados com haleto de prata tipo brilhante ou fosco, em folha e com largura igual ou superior a 152 mm e comprimento inferior ou igual a 307 mm, (iii) papel de qualidade fotográfica com tecnologia “Thermo-autochrome”, que submetido a um processo de aquecimento seja capaz de formar imagens por reação química e combinação das camadas cyan, magenta e amarela\n\
6almaço\n\
6hectográfico\n\
6celofane e tipo celofane\n\
6impermeável\n\
6crepon\n\
6fantasia\n\
5-carbono, papel autocopiativo (exceto os vendidos em rolos de diâmetro igual ou superior a 60 cm e os vendidos em folhas de formato igual ou superior a 60 cm de altura e igual ou superior a 90 cm de largura) e outros papéis para cópia ou duplicação (incluídos os papéis para estênceis ou para chapas ofsete), estênceis completos e chapas ofsete, de papel, em folhas, mesmo acondicionados em caixas\n\
0Envelopes, aerogramas, bilhetes-postais não ilustrados e cartões para correspondência, de papel ou cartão, caixas, sacos e semelhantes, de papel ou cartão, contendo um sortido de artigos para correspondência\n\
0Livros de registro e de contabilidade, blocos de notas, de encomendas, de recibos, de apontamentos, de papel para cartas, agendas e artigos semelhantes\n\
0Cadernos\n\
1lassificadores, capas para encadernação (exceto as capas para livros) e capas de processos\n\
0Formulários em blocos tipo “manifold”, mesmo com folhas intercaladas de papel-carbono\n\
0Álbuns para amostras ou para coleções\n\
0Pastas para documentos, outros artigos escolares, de escritório ou de papelaria, de papel ou cartão e capas para livros, de papel ou cartão\n\
0Cartões postais impressos ou ilustrados, cartões impressos com votos ou mensagens pessoais, mesmo ilustrados, com ou sem envelopes, guarnições ou aplicações (conhecidos como cartões de expressão social - de época/sentimento)\n\
2netas esferográficas\n\
9 marcadores, com ponta de feltro ou com outras pontas porosas\n\
8tinteiro\n\
0Outras canetas; sortidos de canetas\n\
0Papel cortado “cutsize” (tipo A3, A4, ofício I e II, carta e outros)\n\
7amurça\n\
6laminado e papel espelho\n\
0Henna (embalagens de conteúdo inferior ou igual a 200 g)\n\
usuperior a 200 g)\n\
0Vaselina\n\
0Amoníaco em solução aquosa (amônia)\n\
0Peróxido de hidrogênio, em embalagens de conteúdo inferior ou igual a 500 ml\n\
0Lubrificação íntima\n\
0Óleos essenciais (desterpenados ou não), incluídos os chamados “concretos” ou “absolutos”; resinoides; oleorresinas de extração; soluções concentradas de óleos essenciais em gorduras, em óleos fixos, em ceras ou em matérias análogas, obtidas por tratamento de flores através de substâncias gordas ou por maceração; subprodutos terpênicos residuais da desterpenação dos óleos essenciais; águas destiladas aromáticas e soluções aquosas de óleos essenciais, em embalagens de conteúdo inferior ou igual a 500 ml\n\
0Perfumes (extratos)\n\
0Águas-de-colônia\n\
0Produtos de maquilagem para os lábios\n\
0Sombra, delineador, lápis para sobrancelhas e rímel\n\
0Outros produtos de maquilagem para os olhos\n\
0Preparações para manicuros e pedicuros, incluindo removedores de esmalte à base de acetona\n\
1ós, incluídos os compactos\n\
0Cremes de beleza, cremes nutritivos e loções tônicas\n\
0Outros produtos de beleza ou de maquilagem preparados e preparações para conservação ou cuidados da pele, exceto as preparações solares e antissolares\n\
0Preparações solares e antissolares\n\
0Xampus para o cabelo\n\
0Preparações para ondulação ou alisamento, permanentes, dos cabelos\n\
0Laquês para o cabelo\n\
0Outras preparações capilares, incluindo máscaras e finalizadores\n\
0Condicionadores\n\
0Tintura para o cabelo\n\
0Dentifrícios\n\
0Fios utilizados para limpar os espaços interdentais (fios dentais)\n\
0Outras preparações para higiene bucal ou dentária\n\
0Preparações para barbear (antes, durante ou após)\n\
0Desodorantes (desodorizantes) corporais líquidos, exceto os classificados no CEST 20.027.01\n\
0Loções e óleos desodorantes hidratantes líquidos\n\
0Antiperspirantes líquidos\n\
0Outros desodorantes (desodorizantes) corporais, exceto os classificados no CEST 20.029.01\n\
4as loções e óleos desodorantes hidratantes\n\
4os antiperspirantes\n\
0Sais perfumados e outras preparações para banhos\n\
0Outros produtos de perfumaria preparados\n\
jtoucador preparados\n\
0Soluções para lentes de contato ou para olhos artificiais\n\
1abões de toucador em barras, pedaços ou figuras moldados, exceto CEST 20.034.01\n\
0Lenços umedecidos\n\
0Outros sabões, produtos e preparações, em barras, pedaços ou figuras moldados\n\
0Sabões de toucador sob outras formas\n\
0Produtos e preparações orgânicos tensoativos para lavagem da pele, na forma de líquido ou de creme, acondicionados para venda a retalho, mesmo contendo sabão\n\
0Bolsa para gelo ou para água quente\n\
0Chupetas e bicos para mamadeiras e para chupetas, de borracha\n\
zpara chupetas, de silicone\n\
0Malas e maletas de toucador\n\
0Papel higiênico - folha simples\n\
odupla, tripla e quádrupla\n\
0Lenços (incluídos os de maquilagem) e toalhas de mão\n\
0Papel toalha de uso institucional do tipo comercializado em rolos igual ou superior a 80 metros e do tipo comercializado em folhas intercaladas\n\
0Toalhas e guardanapos de mesa\n\
8de cozinha (papel toalha de uso doméstico)\n\
0Fraldas, exceto os descritos no CEST 20.048.01\n\
7 de fibras têxteis\n\
0Tampões higiênicos\n\
0Absorventes higiênicos externos\n\
0Hastes flexíveis (uso não medicinal)\n\
0Sutiã descartável, assemelhados e papel para depilação\n\
0Pinças para sobrancelhas\n\
0Espátulas (artigos de cutelaria)\n\
0Utensílios e sortidos de utensílios de manicuros ou de pedicuros (incluídas as limas para unhas)\n\
0Termômetros, inclusive o digital\n\
0Escovas e pincéis de barba, escovas para cabelos, para cílios ou para unhas e outras escovas de toucador de pessoas, incluídas as que sejam partes de aparelhos, exceto escovas de dentes\n\
8de dentes, incluídas as escovas para dentaduras\n\
0Pincéis para aplicação de produtos cosméticos\n\
0Sortidos de viagem, para toucador de pessoas para costura ou para limpeza de calçado ou de roupas\n\
0Pentes, travessas para cabelo e artigos semelhantes; grampos (alfinetes) para cabelo; pinças (pinceguiches), onduladores, bobes (rolos) e artefatos semelhantes para penteados, e suas partes, exceto os classificados na posição 8516 e suas partes\n\
0Borlas ou esponjas para pós ou para aplicação de outros cosméticos ou de produtos de toucador\n\
0Mamadeiras\n\
0Aparelhos e lâminas de barbear\n\
1lgodão hidrófilo, não estéril, destinado à higiene pessoal\n\
0Fogões de cozinha de uso doméstico e suas partes\n\
0Combinações de refrigeradores e congeladores (“freezers”), munidos de portas exteriores separadas\n\
0Refrigeradores do tipo doméstico, de compressão\n\
0Outros refrigeradores do tipo doméstico\n\
0Congeladores (“freezers”) horizontais tipo arca, de capacidade não superior a 800 litros\n\
qverticais tipo armário, de capacidade não superior a 900 litros\n\
0Outros móveis (arcas, armários, vitrines, balcões e móveis semelhantes) para a conservação e exposição de produtos, que incorporem um equipamento para a produção de frio\n\
0Mini adega e similares\n\
1áquinas para produção de gelo\n\
0Partes dos refrigeradores, congeladores, mini adegas e similares, máquinas para produção de gelo e bebedouros descritos nos CEST 21.002.00, 21.003.00, 21.004.00, 21.005.00, 21.006.00, 21.007.00, 21.008.00, 21.009.00 e 21.013.00\n\
0Secadoras de roupa de uso doméstico\n\
0Outras secadoras de roupas e centrífugas de uso doméstico\n\
0Bebedouros refrigerados para água\n\
0Partes das secadoras de roupas e centrífugas de uso doméstico e dos aparelhos para filtrar ou depurar água, descritos nos CEST 21.011.00 e 21.012.00 e 21.098.00\n\
0Máquinas de lavar louça do tipo doméstico e suas partes\n\
9que executem pelo menos duas das seguintes funções: impressão, cópia ou transmissão de telecópia (fax), capazes de ser conectadas a uma máquina automática para processamento de dados ou a uma rede\n\
0Outras impressoras, máquinas copiadoras e telecopiadores (fax), mesmo combinados entre si, capazes de ser conectados a uma máquina automática para processamento de dados ou a uma rede\n\
0Partes e acessórios de máquinas e aparelhos de impressão por meio de blocos, cilindros e outros elementos de impressão da posição 8442; e de outras impressoras, máquinas copiadoras e telecopiadores (fax), mesmo combinados entre si\n\
0Máquinas de lavar roupa, mesmo com dispositivos de secagem, de uso doméstico, de capacidade não superior a 10 kg, em peso de roupa seca, inteiramente automáticas\n\
0Outras máquinas de lavar roupa, mesmo com dispositivos de secagem, de uso doméstico, com secador centrífugo incorporado\n\
zmo com dispositivos de secagem, de uso doméstico\n\
0Máquinas de lavar roupa, mesmo com dispositivos de secagem, de uso doméstico, de capacidade superior a 10 kg, em peso de roupa seca\n\
0Partes de máquinas de lavar roupa, mesmo com dispositivos de secagem, de uso doméstico\n\
0Máquinas de secar de uso doméstico de capacidade não superior a 10 kg, em peso de roupa seca\n\
0Outras máquinas de secar de uso doméstico\n\
0Partes de máquinas de secar de uso doméstico\n\
0Máquinas de costura de uso doméstico\n\
9automáticas para processamento de dados, portáteis, de peso não superior a 10 kg, contendo pelo menos uma unidade central de processamento, um teclado e uma tela\n\
0Outras máquinas automáticas para processamento de dados\n\
0Unidades de processamento, de pequena capacidade, exceto as das subposições 8471.41 ou 8471.49, podendo conter, no mesmo corpo, um ou dois dos seguintes tipos de unidades: unidade de memória, unidade de entrada e unidade de saída; baseadas em microprocessadores, com capacidade de instalação, dentro do mesmo gabinete, de unidades de memória da subposição 8471.70, podendo conter múltiplos conectores de expansão (“slots”), e valor FOB inferior ou igual a US$ 12.500,00, por unidade\n\
centrada, exceto as classificadas no código 8471.60.54\n\
0Outras unidades de entrada ou de saída, podendo conter, no mesmo corpo, unidades de memória\n\
0Unidades de memória\n\
0Outras máquinas automáticas para processamento de dados e suas unidades; leitores magnéticos ou ópticos, máquinas para registrar dados em suporte sob forma codificada, e máquinas para processamento desses dados, não especificadas nem compreendidas em outras posições\n\
0Partes e acessórios das máquinas da posição 84.71\n\
0Outros transformadores, exceto os classificados nos códigos 8504.33.00 e 8504.34.00\n\
0Carregadores de acumuladores\n\
0Equipamentos de alimentação ininterrupta de energia (UPS ou “no break”)\n\
0Outros acumuladores\n\
0Aspiradores\n\
1parelhos eletromecânicos de motor elétrico incorporado, de uso doméstico e suas partes\n\
0Enceradeiras\n\
0Chaleiras elétricas\n\
0Ferros elétricos de passar\n\
1ornos de micro-ondas\n\
0Outros fornos; fogareiros (incluídas as chapas de cocção), grelhas e assadeiras, exceto os portáteis\n\
zs as chapas de cocção), grelhas e assadeiras, portáteis\n\
7aparelhos eletrotérmicos de uso doméstico - Cafeteiras\n\
zuso doméstico - Torradeiras\n\
zuso doméstico\n\
0Partes das chaleiras, ferros, fornos e outros aparelhos eletrotérmicos da posição 85.16, descritos nos CEST 21.043.00, 21.044.00, 21.045.00, 21.046.00, 21.047.00, 21.048.00, 21.049.00 e 21.050.00\n\
0Aparelhos telefônicos por fio com unidade auscultador - microfone sem fio\n\
0Telefones inteligentes (“smartphones”) e para redes celulares, excetos por satélite, os de uso automotivo e os classificados nos CEST 21.053.01\n\
zs”) e para redes celulares portáteis, excetos por satélite\n\
0Outros telefones para outras redes sem fio, excetos os de uso automotivo e os classificados nos CEST 21.053.00 e 21.053.01\n\
7aparelhos telefônicos não combinados com outros aparelhos\n\
s\n\
hpara transmissão ou recepção de voz, imagem ou outros dados em rede com fio\n\
0Distribuidores de conexões para rede (“hubs”) e moduladores/demoduladores (“modens”)\n\
0Microfones e seus suportes; alto-falantes, mesmo montados nos seus receptáculos, fones de ouvido (auscultadores), mesmo combinados com microfone e conjuntos ou sortidos constituídos por um microfone e um ou mais alto-falantes, amplificadores elétricos de audiofrequência, aparelhos elétricos de amplificação de som; suas partes e acessórios; exceto os de uso automotivo\n\
0Aparelhos de radiodifusão suscetíveis de funcionarem sem fonte externa de energia. Aparelhos de gravação de som; aparelhos de reprodução de som; aparelhos de gravação e de reprodução de som; partes e acessórios; exceto os de uso automotivo\n\
0Outros aparelhos de gravação de som; aparelhos de reprodução de som; aparelhos de gravação e de reprodução de som; partes e acessórios; exceto os de uso automotivo\n\
0Gravador-reprodutor e editor de imagem e som, em discos, por meio magnético, óptico ou optomagnético, exceto de uso automotivo\n\
0Outros aparelhos videofônicos de gravação ou reprodução, mesmo incorporando um receptor de sinais videofônicos, exceto os de uso automotivo\n\
0Cartões de memória ("memorycards")\n\
8inteligentes ("smartcards"), exceto o item classificado no CEST 21.064.00\n\
oim cards")\n\
1âmeras fotográficas digitais e câmeras de vídeo\n\
0Outros aparelhos receptores para radiodifusão, mesmo combinados num invólucro, com um aparelho de gravação ou de reprodução de som, ou com um relógio, inclusive caixa acústica para Home Theaters classificados na posição 8518\n\
0Monitores e projetores que não incorporem aparelhos receptores de televisão, policromáticos\n\
0Projetores capazes de serem conectados diretamente a uma máquina automática para processamento de dados da posição 84.71 e concebidos para serem utilizados com esta máquina\n\
0Outros monitores capazes de serem conectados diretamente a uma máquina automática para processamento de dados da posição 84.71 e concebidos para serem utilizados com esta máquina, policromáticos\n\
0Aparelhos receptores de televisão, mesmo que incorporem um aparelho receptor de radiodifusão ou um aparelho de gravação ou reprodução de som ou de imagens - Televisores de CRT (tubo de raios catódicos)\n\
zmesmo que incorporem um aparelho receptor de radiodifusão ou um aparelho de gravação ou reprodução de som ou de imagens - Televisores de LCD (Display de Cristal Líquido)\n\
zmesmo que incorporem um aparelho receptor de radiodifusão ou um aparelho de gravação ou reprodução de som ou de imagens - Televisores de Plasma\n\
0Outros aparelhos receptores de televisão não dotados de monitores ou display de vídeo\n\
zvisão não relacionados nos CEST 21.069.00, 21.070.00, 21.071.00 e 21.072.00\n\
0Câmeras fotográficas dos tipos utilizadas para preparação de clichês ou cilindros de impressão\n\
lpara filmes de revelação e copiagem instantâneas\n\
0Aparelhos de diatermia\n\
dmassagem\n\
0Reguladores de voltagem eletrônicos\n\
0Consoles e máquinas de jogos de vídeo, exceto os classificados na subposição 9504.30\n\
0Multiplexadores e concentradores\n\
0Centrais automáticas privadas, de capacidade inferior ou igual a 25 ramais\n\
0Outros aparelhos para comutação\n\
0Roteadores digitais, em redes com ou sem fio\n\
0Aparelhos emissores com receptor incorporado de tecnologia celular\n\
0Outros aparelhos de recepção, conversão e transmissão ou regeneração de voz, imagens ou outros dados, incluindo os aparelhos de comutação e roteamento\n\
0Antenas próprias para telefones celulares portáteis, exceto as telescópicas\n\
1parelhos ou máquinas de barbear, máquinas de cortar o cabelo ou de tosquiar e aparelhos de depilar, e suas partes\n\
0Ventiladores, exceto os de uso agrícola e do CEST 21.088.01\n\
0Microventiladores com área de carcaça inferior a 90 cm²\n\
0Ventiladores de uso agrícola\n\
0Coifas com dimensão horizontal máxima não superior a 120 cm\n\
0Partes de ventiladores ou coifas aspirantes\n\
0Máquinas e aparelhos de ar condicionado contendo um ventilador motorizado e dispositivos próprios para modificar a temperatura e a umidade, incluídos as máquinas e aparelhos em que a umidade não seja regulável separadamente\n\
0Aparelhos de ar-condicionado tipo Split System (sistema com elementos separados) com unidade externa e interna\n\
tcom capacidade inferior ou igual a 30.000 frigorias/hora\n\
zpacidade acima de 30.000 frigorias/hora\n\
0Unidades evaporadoras (internas) de aparelho de ar-condicionado do tipo Split System (sistema com elementos separados), com capacidade inferior ou igual a 30.000 frigorias/hora\n\
9condensadoras (externas) de aparelho de ar-condicionado do tipo Split System (sistema com elementos separados), com capacidade inferior ou igual a 30.000 frigorias/hora\n\
0Aparelhos elétricos para filtrar ou depurar água (purificadores de água refrigerados), exceto os itens classificados no CEST 21.098.01\n\
0Outros aparelhos elétricos para filtrar ou depurar água\n\
0Lavadora de alta pressão e suas partes\n\
0Furadeiras elétricas\n\
0Aparelhos elétricos para aquecimento de ambientes\n\
0Secadores de cabelo\n\
0Outros aparelhos para arranjos do cabelo\n\
0Aparelhos receptores para radiodifusão, mesmo combinados num mesmo invólucro, com um aparelho de gravação ou de reprodução de som, ou com um relógio, exceto os classificados na posição 8527.1, 8527.2 e 8527.9 que sejam de uso automotivo\n\
0Climatizadores de ar\n\
0Outras partes para máquinas e aparelhos de ar-condicionado que contenham um ventilador motorizado e dispositivos próprios para modificar a temperatura e a umidade, incluindo as máquinas e aparelhos em que a umidade não seja regulável separadamente\n\
0Câmeras de televisão\n\
0Balanças de uso doméstico\n\
0Tubos e válvulas, eletrônicos, de cátodo quente, cátodo frio ou fotocátodo (por exemplo, tubos e válvulas, de vácuo, de vapor ou de gás, ampolas retificadoras de vapor de mercúrio, tubos catódicos, tubos e válvulas para câmeras de televisão)\n\
0Aparelhos elétricos para telefonia; outros aparelhos para transmissão ou recepção de voz, imagens ou outros dados, incluídos os aparelhos para comunicação em redes por fio ou redes sem fio, tal como uma rede local (LAN) ou uma rede de área estendida (WAN), incluídas suas partes, exceto os de uso automotivo, os classificados nos códigos NCM/SH 8517.62.51, 8517.62.52 e 8517.62.53 e no código CEST 21.127.00\n\
0Interfones, seus acessórios, tomadas e “plugs”\n\
0Partes reconhecíveis como exclusiva ou principalmente destinadas aos aparelhos das posições 8525 a 8528; exceto as de uso automotivo\n\
0Aparelhos elétricos de sinalização acústica ou visual (por exemplo, campainhas, sirenes, quadros indicadores, aparelhos de alarme para proteção contra roubo ou incêndio); exceto os de uso automotivo e os classificados nas posições 8531.10 e 8531.80.00\n\
nalarme, para proteção contra roubo ou incêndio e aparelhos semelhantes, exceto os de uso automotivo\n\
0Outros aparelhos de sinalização acústica ou visual, exceto os de uso automotivo\n\
0Circuitos impressos, exceto os de uso automotivo\n\
0Diodos emissores de luz (LED), exceto diodos “laser”\n\
0Eletrificadores de cercas eletrônicos\n\
0Aparelhos e instrumentos para medida ou controle da tensão, intensidade, resistência ou da potência, sem dispositivo registrador; exceto os de uso automotivo\n\
1nalisadores lógicos de circuitos digitais, de espectro de frequência, frequencímetros, fasímetros, e outros instrumentos e aparelhos de controle de grandezas elétricas e detecção\n\
0Interruptores horários e outros aparelhos que permitam acionar um mecanismo em tempo determinado, munidos de maquinismo de aparelhos de relojoaria ou de motor síncrono\n\
0Aparelhos de iluminação (incluídos os projetores) e suas partes, não especificados nem compreendidos em outras posições; anúncios, cartazes ou tabuletas e placas indicadoras luminosos, e artigos semelhantes, contendo uma fonte luminosa fixa permanente, e suas partes não especificadas nem compreendidas em outras posições, com exceção dos itens classificados nos CEST 21.123.00, 21.124.00 e 21.125.00\n\
0Lustres e outros aparelhos elétricos de iluminação, próprios para serem suspensos ou fixados no teto ou na parede, exceto os dos tipos utilizados na iluminação pública; e suas partes\n\
0Abajures de cabeceiras, de escritório e lampadários de interior, elétricos e suas partes\n\
0Outras luminárias e aparelhos de iluminação, elétricos, e suas partes\n\
0Microprocessador\n\
0Aparelho emissor com receptor incorporado, digital, com tecnologias de transmissão/recepção sem fio, tela sensível ao toque “smartwatch”\n\
0Ração tipo “pet” para animais domésticos\n\
0Sorvetes de qualquer espécie\n\
0Preparados para fabricação de sorvete em máquina\n\
0Tintas, vernizes\n\
0Xadrez e pós assemelhados, em embalagem de conteúdo inferior ou igual a 1 kg, exceto pigmentos à base de dióxido de titânio classificados no código NCM 3206.11.10\n\
zagem de conteúdo superior a 1 kg, exceto pigmentos à base de dióxido de titânio classificados no código NCM 3206.11.10\n\
0Corantes para aplicação em bases, tintas e vernizes\n\
0Veículos automóveis para transporte de 10 pessoas ou mais, incluindo o motorista, unicamente com motor de pistão, de ignição por compressão (diesel ou semidiesel), com volume interno de habitáculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³\n\
z de 10 pessoas ou mais, incluindo o motorista, unicamente com motor elétrico para propulsão, com volume interno de habitáculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³\n\
0Automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada não superior a 1000 cm³\n\
zpistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 1000 cm³, mas não superior a 1500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluído o condutor, exceto carro celular\n\
0Outros automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 1000 cm³, mas não superior a 1500 cm³, exceto carro celular\n\
0Automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 1500 cm³, mas não superior a 3000 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluído o condutor, exceto carro celular, carro funerário e automóveis de corrida\n\
0Outros automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 1500 cm³, mas não superior a 3000 cm³, exceto carro celular, carro funerário e automóveis de corrida\n\
0Automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 3000 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluído o condutor, exceto carro celular, carro funerário e automóveis de corrida\n\
0Outros automóveis unicamente com motor de pistão alternativo de ignição por centelha (faísca*), de cilindrada superior a 3000 cm³, exceto carro celular, carro funerário e automóveis de corrida\n\
0Automóveis unicamente com motor diesel ou semidiesel, de cilindrada superior a 1500 cm³, mas não superior a 2500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluído o condutor, exceto ambulância, carro celular e carro funerário\n\
0Outros automóveis unicamente com motor diesel ou semidiesel, de cilindrada superior a 1500 cm³, mas não superior a 2500 cm³, exceto ambulância, carro celular e carro funerário\n\
0Automóveis unicamente com motor diesel ou semidiesel, de cilindrada superior a 2500 cm³, com capacidade de transporte de pessoas sentadas inferior ou igual a 6, incluído o condutor, exceto carro celular e carro funerário\n\
0Outros automóveis unicamente com motor diesel ou semidiesel, de cilindrada superior a 2500 cm³, exceto carro celular e carro funerário\n\
0Veículos automóveis para transporte de mercadorias, de peso em carga máxima não superior a 5 toneladas, chassis com motor diesel ou semidiesel e cabina, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
z de mercadorias, de peso em carga máxima não superior a 5 toneladas, com motor diesel ou semidiesel, com caixa basculante, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
z de mercadorias, de peso em carga máxima não superior a 5 toneladas, frigoríficos ou isotérmicos, com motor diesel ou semidiesel, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
0Outros veículos automóveis para transporte de mercadorias, de peso em carga máxima não superior a 5 toneladas, com motor diesel ou semidiesel, exceto carro-forte para transporte de valores e caminhão de peso em carga máxima superior a 3,9 toneladas\n\
0Veículos automóveis para transporte de mercadorias, de peso em carga máxima não superior a 5 toneladas, com motor a explosão, chassis e cabina, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
z de mercadorias, de peso em carga máxima não superior a 5 toneladas, com motor explosão com caixa basculante, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
z de mercadorias, de peso em carga máxima não superior a 5 toneladas, frigoríficos ou isotérmicos com motor explosão, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
0Outros veículos automóveis para transporte de mercadorias, de peso em carga máxima não superior a 5 toneladas, com motor a explosão, exceto carro-forte para transporte de valores e caminhão de peso em carga máxima superior a 3,9 toneladas\n\
0Veículos automóveis para transporte de 10 pessoas ou mais, incluindo o motorista, com motor de pistão, de ignição por compressão (diesel ou semidiesel) e um motor elétrico, com volume interno de habitáculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³\n\
z de 10 pessoas ou mais, incluindo o motorista, com motor de pistão alternativo, de ignição por centelha (faísca) e um motor elétrico, com volume interno de habitáculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³\n\
0Outros veículos automóveis para transporte de 10 pessoas ou mais, incluindo o motorista, com volume interno de habitáculo, destinado a passageiros e motorista, superior a 6 m³, mas inferior a 9 m³\n\
0Automóveis equipados para propulsão, simultaneamente, com um motor de pistão alternativo de ignição por centelha (faísca*) e um motor elétrico, exceto os suscetíveis de serem carregados por conexão a uma fonte externa de energia elétrica, o carro celular e o carro funerário\n\
z, simultaneamente, com um motor de pistão por compressão (diesel ou semidiesel) e um motor elétrico, exceto os suscetíveis de serem carregados por conexão a uma fonte externa de energia elétrica, exceto o carro celular e o carro funerário\n\
z, simultaneamente, com um motor de pistão alternativo de ignição por centelha (faísca*) e um motor elétrico, suscetíveis de serem carregados por conexão a uma fonte externa de energia elétrica, exceto o carro celular e o carro funerário\n\
z, simultaneamente, com um motor de pistão por compressão (diesel ou semidiesel) e um motor elétrico, suscetíveis de serem carregados por conexão a uma fonte externa de energia elétrica, exceto o carro celular e o carro funerário\n\
0Outros veículos, equipados unicamente com motor elétrico para propulsão\n\
f para transportes de mercadorias equipados para propulsão, simultaneamente, com motor de pistão de ignição por compressão (diesel ou semidiesel) e motor elétrico de peso em carga máxima (bruto) não superior a 5 toneladas, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
z mercadorias equipados para propulsão, simultaneamente, com motor de pistão de ignição por centelha (faísca) e motor elétrico de peso em carga máxima (bruto) não superior a 5 toneladas, exceto caminhão de peso em carga máxima superior a 3,9 toneladas\n\
v de mercadorias, unicamente com motor elétrico para propulsão, exceto veículo de peso em carga máxima superior a 3,9 toneladas\n\
0Motocicletas (incluídos os ciclomotores) e outros ciclos equipados com motor auxiliar, mesmo com carro lateral, exceto os classificados no CEST 26.001.01; carros laterais\n\
0Bicicletas e outros ciclos (incluídos os triciclos) com propulsão de motor elétrico auxiliar assistido pela força humana\n\
0Perfumes (extratos)\n\
0Águas-de-colônia\n\
0Produtos de maquiagem para os lábios\n\
0Sombra, delineador, lápis para sobrancelhas e rímel\n\
0Outros produtos de maquiagem para os olhos\n\
0Preparações para manicuros e pedicuros\n\
1ós para maquiagem, incluindo os compactos\n\
0Cremes de beleza, cremes nutritivos e loções tônicas\n\
0Outros produtos de beleza ou de maquiagem preparados e preparações para conservação ou cuidados da pele, exceto as preparações antissolares e os bronzeadores\n\
0Preparações antissolares e os bronzeadores\n\
0Xampus para o cabelo\n\
0Preparações para ondulação ou alisamento, permanentes, dos cabelos\n\
0Outras preparações capilares\n\
0Tintura para o cabelo\n\
0Preparações para barbear (antes, durante ou após)\n\
0Desodorantes (desodorizantes) corporais líquidos, exceto os classificados no CEST 28.016.01\n\
0Loções e óleos desodorantes hidratantes líquidos\n\
0Antiperspirantes líquidos\n\
0Outros desodorantes (desodorizantes) corporais, exceto os classificados no CEST 28.017.01\n\
4as loções e óleos desodorantes hidratantes\n\
4os antiperspirantes\n\
7produtos de perfumaria ou de toucador preparados\n\
4as preparações cosméticas\n\
0Sabões de toucador em barras, pedaços ou figuras moldados, exceto CEST 28.020.01\n\
0Lenços umedecidos\n\
0Outros sabões, produtos e preparações orgânicos tensoativos, inclusive papel, pastas (ouates), feltros e falsos tecidos, impregnados, revestidos ou recobertos de sabão ou de detergentes\n\
0Sabões de toucador sob outras formas\n\
0Produtos e preparações orgânicos tensoativos para lavagem da pele, em forma de líquido ou de creme, acondicionados para venda a retalho, mesmo contendo sabão\n\
0Lenços de papel, incluindo os de desmaquiar\n\
0Toalhas de mão\n\
0Apontadores de lápis para maquiagem\n\
0Espátulas, abre-cartas e raspadeiras\n\
0Lâminas de espátulas, de abre-cartas, de raspadeiras e de apontadores de lápis\n\
0Utensílios e sortidos de utensílios de manicuros ou de pedicuros (incluindo as limas para unhas)\n\
0Escovas e pincéis de barba, escovas para cabelos, para cílios ou para unhas e outras escovas de toucador de pessoas\n\
0Vassouras e escovas, mesmo constituindo partes de máquinas, de aparelhos ou de veículos, vassouras mecânicas de uso manual não motorizadas, pincéis e espanadores; cabeças preparadas para escovas, pincéis e artigos semelhantes; bonecas e rolos para pintura; rodos de borracha ou de matérias flexíveis semelhantes, outros\n\
0Pincéis para aplicação de produtos cosméticos\n\
8e escovas, para artistas e pincéis de escrever\n\
0Vaporizadores de toucador, suas armações e cabeças de armações\n\
0Borlas ou esponjas para pós ou para aplicação de outros cosméticos ou de produtos de toucador\n\
0Malas e maletas de toucador\n\
0Pentes, travessas para cabelo e artigos semelhantes; grampos (alfinetes) para cabelo; pinças (“pinceguiches”), onduladores, bobs (rolos) e artefatos semelhantes para penteados, e suas partes\n\
0Mamadeiras\n\
0Chupetas e bicos para mamadeiras e para chupetas\n\
0Outras plantas e partes, para perfumaria, medicina e semelhantes\n\
0Vestuário e seus acessórios, de plásticos, inclusive luvas\n\
0Estatuetas e outros objetos de ornamentação, de plásticos\n\
0Outras obras de plásticos\n\
0Bolsas de folhas de plástico\n\
amatérias têxteis\n\
aoutras matérias\n\
0Artigos de bolsos/bolsas, de outras matérias\n\
0Outros artefatos, de folhas de plásticos ou matérias têxteis\n\
loutras matérias\n\
0Caixas e cartonagens, dobráveis, de papel/cartão, não ondulados\n\
0Outros sacos, bolsas e cartuchos, de papel ou cartão\n\
0Etiquetas de papel ou cartão, impressas\n\
0Outros impressos publicitários, catálogos comerciais e semelhantes\n\
4as meias de malha de outras matérias têxteis\n\
4os acessórios confeccionados, de vestuário\n\
0Roupas de toucador/cozinha, de tecidos atoalhados de algodão\n\
0Outros artefatos têxteis confeccionados\n\
0Chapéus e outros artefatos de outras matérias, exceto de malha\n\
0Artigos para outras festas, carnaval ou outros divertimentos\n\
0Produtos destinados à higiene bucal\n\
0Outros produtos cosméticos e de higiene pessoal não relacionados em outros itens deste anexo\n\
7artigos destinados a cuidados pessoais não relacionados em outros itens deste anexo\n\
0Acessórios (por exemplo, bijuterias, relógios, óculos de sol, bolsas, mochilas, frasqueiras, carteiras, porta-cartões, porta-documentos, porta-celulares e embalagens presenteáveis (por exemplo, caixinhas de papel), entre outros itens assemelhados)\n\
0Vestuário e seus acessórios; calçados, polainas e artefatos semelhantes, e suas partes\n\
0Outros artigos de vestuário em geral, exceto os relacionados no item anterior\n\
0Artigos de casa\n\
0Produtos das indústrias alimentares e bebidas\n\
ae limpeza e conservação doméstica\n\
0Artigos infantis\n\
0Outros produtos comercializados pelo sistema de marketing direto porta-a-porta a consumidor final não relacionados em outros itens deste anexo';

/**
 * Segment names of Anexo I of Convênio ICMS 142/18, indexed by the 2 digit segment code, which
 * is the first two digits of every CEST of the segment. The keys are built in ascending code
 * order, which is not the order they read in: JavaScript lists the keys of an object that look
 * like array indexes before the rest, so segments 10 to 28 come first and 01 to 09 follow.
 *
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/convenios/2018/CV142_18
 * Anexo I, "Segmentos de mercadorias".
 */
export const CEST_SEGMENTS: Record<string, string> = {
	"10": "Materiais de construção e congêneres",
	"11": "Materiais de limpeza",
	"12": "Materiais elétricos",
	"13": "Medicamentos de uso humano e outros produtos farmacêuticos para uso humano ou veterinário",
	"14": "Papéis, plásticos, produtos cerâmicos e vidros",
	"16": "Pneumáticos, câmaras de ar e protetores de borracha",
	"17": "Produtos alimentícios",
	"19": "Produtos de papelaria",
	"20": "Produtos de perfumaria e de higiene pessoal e cosméticos",
	"21": "Produtos eletrônicos, eletroeletrônicos e eletrodomésticos",
	"22": "Rações para animais domésticos",
	"23": "Sorvetes e preparados para fabricação de sorvetes em máquinas",
	"24": "Tintas e vernizes",
	"25": "Veículos automotores",
	"26": "Veículos de duas e três rodas motorizados",
	"28": "Venda de mercadorias pelo sistema porta a porta",
	"01": "Autopeças",
	"02": "Bebidas alcoólicas, exceto cerveja e chope",
	"03": "Cervejas, chopes, refrigerantes, águas e outras bebidas",
	"04": "Cigarros e outros produtos derivados do fumo",
	"05": "Cimentos",
	"06": "Combustíveis e lubrificantes",
	"07": "Energia elétrica",
	"08": "Ferramentas",
	"09": "Lâmpadas, reatores e “starter”",
};
