/**
 * CFOP official operation descriptions, each at the index of its code in `CFOP_CODES`
 * (`cfop.ts`).
 *
 * Packed by `packTexts` (scripts/lookup-table.ts), which `unpackTexts` reads.
 *
 * Generated by `node ./scripts/cfop.ts`. Do not edit by hand.
 *
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/ajustes/sinief/cfop_cvsn_1-6.24
 * Anexo II of Convênio SINIEF s/nº 1970, the CFOP table in force.
 */
export const CFOP_DESCRIPTIONS =
	"0Compra para industrialização ou produção rural\n\
ccomercialização\n\
cindustrialização de mercadoria recebida anteriormente em consignação industrial\n\
ccomercialização, de mercadoria recebida anteriormente em consignação mercantil\n\
cindustrialização ou produção rural originada de encomenda para recebimento futuro\n\
ccomercialização originada de encomenda para recebimento futuro\n\
7de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem\n\
7para industrialização ou produção rural, em venda à ordem, já recebida do vendedor remetente\n\
ccomercialização, em venda à ordem, já recebida do vendedor remetente\n\
cindustrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente\n\
0Industrialização efetuada por outra empresa\n\
z empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria\n\
0Compra para utilização na prestação de serviço sujeita ao ICMS\n\
z de serviço sujeita ao ISSQN\n\
0Entrada de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização\n\
zabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização\n\
0Transferência para industrialização ou produção rural\n\
jcomercialização\n\
ede energia elétrica para distribuição\n\
epara utilização na prestação de serviço\n\
0Entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo\n\
0Devolução de venda de produção do estabelecimento\n\
mmercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 1.503, 1.504, 1.505 e 1.506\n\
mprodução do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
mmercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
0Anulação de valor relativo à prestação de serviço de comunicação\n\
zção de serviço de transporte\n\
tvenda de energia elétrica\n\
0Devolução de produção do estabelecimento, remetida em transferência\n\
dmercadoria adquirida ou recebida de terceiros, remetida em transferência\n\
dvenda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
dremessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
areferente à fixação de preço de produção do estabelecimento produtor em ato cooperativo\n\
ade fornecimento de produção do estabelecimento em ato cooperativo\n\
tmercadoria adquirida ou recebida de terceiros em ato cooperativo\n\
0Compra de energia elétrica para distribuição ou comercialização\n\
sor estabelecimento industrial\n\
zbelecimento comercial\n\
zbelecimento prestador de serviço de transporte\n\
zbelecimento prestador de serviço de comunicação\n\
zbelecimento de produtor rural\n\
sara consumo por demanda contratada\n\
0Aquisição de serviço de comunicação para execução de serviço da mesma natureza\n\
z por estabelecimento industrial\n\
z por estabelecimento comercial\n\
z por estabelecimento de prestador de serviço de transporte\n\
z por estabelecimento de geradora ou de distribuidora de energia elétrica\n\
z por estabelecimento de produtor rural\n\
otransporte para execução de serviço da mesma natureza\n\
zpor estabelecimento industrial\n\
zpor estabelecimento comercial\n\
zpor estabelecimento de prestador de serviço de comunicação\n\
zpor estabelecimento de geradora ou de distribuidora de energia elétrica\n\
zpor estabelecimento de produtor rural\n\
zpor contribuinte substituto em relação ao serviço de transporte\n\
0Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
ccomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
7de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária\n\
amercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária\n\
0Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
jcomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
mmercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
bmercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Entrada de animal - Sistema de Integração e Parceria Rural\n\
binsumo - Sistema de Integração e Parceria Rural\n\
0Retorno do animal ou da produção - Sistema de Integração e Parceria Rural\n\
8simbólico do animal ou da produção - Sistema de Integração e Parceria Rural\n\
8de insumo não utilizado na produção - Sistema de Integração e Parceria Rural\n\
0Entrada referente à remuneração do produtor no Sistema de Integração e Parceria Rural\n\
8de mercadoria recebida com fim específico de exportação\n\
acorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento\n\
v, inclusive simbólica, de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros\n\
zclusive simbólica, de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento\n\
zclusive simbólica, de mercadorias adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação\n\
0Compra de bem para o ativo imobilizado\n\
0Transferência de bem do ativo imobilizado\n\
0Devolução de venda de bem do ativo imobilizado\n\
0Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento\n\
0Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento\n\
0Compra de material para uso ou consumo\n\
0Transferência de material para uso ou consumo\n\
0Recebimento, por transferência, de crédito de ICMS\n\
zsaldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS\n\
2ssarcimento de ICMS retido por substituição tributária\n\
0Lançamento do crédito relativo à compra de bem para o ativo imobilizado\n\
0Recebimento, por transferência, de saldo devedor de ICMS de outro estabelecimento da mesma empresa\n\
0Compra de combustíveis ou lubrificantes para industrialização subsequente\n\
zntes para comercialização\n\
zntes por consumidor ou usuário final\n\
0Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento\n\
0Transferência de combustíveis ou lubrificantes para industrialização\n\
zbrificantes para comercialização\n\
0Devolução de venda de combustíveis ou lubrificantes destinados à industrialização subsequente\n\
zou lubrificantes destinados à comercialização\n\
zou lubrificantes destinados a consumidor ou usuário final\n\
0Entrada de combustíveis ou lubrificantes para armazenagem\n\
0Retorno de combustíveis ou lubrificantes remetidos para armazenagem\n\
0Entrada para industrialização por encomenda\n\
0Retorno de mercadoria remetida para industrialização por encomenda\n\
0Entrada de mercadoria remetida para industrialização e não aplicada no referido processo\n\
0Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 1.202, 1.503, 1.504, 1.505 e 1.506\n\
0Entrada de mercadoria recebida para depósito em depósito fechado, armazém geral ou outro estabelecimentoda mesma empresa ou de terceiro\n\
0Retorno de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento, da mesma empresa ou de terceiro\n\
8simbólico de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
0Entrada de bem por conta de contrato de comodato ou locação\n\
0Retorno de bem remetido por conta de contrato de comodato ou locação\n\
0Entrada de bonificação, doação ou brinde\n\
bamostra grátis\n\
bmercadoria ou bem recebido para demonstração ou mostruário\n\
0Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento\n\
zdo para exposição ou feira\n\
0Entrada de mercadoria ou bem recebido para conserto ou reparo\n\
0Retorno de mercadoria ou bem remetido para conserto ou reparo\n\
0Entrada de mercadoria recebida em consignação mercantil ou industrial\n\
0Devolução de mercadoria remetida em consignação mercantil ou industrial\n\
asimbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial\n\
0Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados\n\
0Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados\n\
0Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro\n\
0Entrada de mercadoria recebida do vendedor remetente, em venda à ordem\n\
8para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
0Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
0Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação\n\
kpelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço\n\
0Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador\n\
lsujeito ao ISSQN\n\
0Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral\n\
0Outra entrada de mercadoria ou prestação de serviço não especificada\n\
0Compra para industrialização ou produção rural\n\
ccomercialização\n\
cindustrialização de mercadoria recebida anteriormente em consignação industrial\n\
ccomercialização, de mercadoria recebida anteriormente em consignação mercantil\n\
cindustrialização ou produção rural originada de encomenda para recebimento futuro\n\
ccomercialização originada de encomenda para recebimento futuro\n\
7de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem\n\
7para industrialização ou produção rural, em venda à ordem, já recebida do vendedor remetente\n\
ccomercialização, em venda à ordem, já recebida do vendedor remetente\n\
cindustrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente\n\
0Industrialização efetuada por outra empresa\n\
z empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adquirente da mercadoria\n\
0Compra para utilização na prestação de serviço sujeita ao ICMS\n\
z de serviço sujeita ao ISSQN\n\
0Entrada de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização\n\
zabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização\n\
0Transferência para industrialização ou produção rural\n\
jcomercialização\n\
ede energia elétrica para distribuição\n\
epara utilização na prestação de serviço\n\
0Entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo\n\
0Devolução de venda de produção do estabelecimento\n\
mmercadoria adquirida ou recebida de terceiros, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas nos códigos 2.503, 2.504, 2.505 e 2.506\n\
mprodução do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
mmercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
0Anulação de valor relativo à prestação de serviço de comunicação\n\
zção de serviço de transporte\n\
tvenda de energia elétrica\n\
0Devolução de produção do estabelecimento, remetida em transferência\n\
dmercadoria adquirida ou recebida de terceiros, remetida em transferência\n\
dvenda no mercado interno de mercadoria industrializada e insumo importado sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
dremessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
areferente à fixação de preço de produção do estabelecimento produtor, em ato cooperativo\n\
ade fornecimento de produção do estabelecimento em ato cooperativo\n\
tmercadoria adquirida ou recebida de terceiros em ato cooperativo\n\
0Compra de energia elétrica para distribuição ou comercialização\n\
sor estabelecimento industrial\n\
zbelecimento comercial\n\
zbelecimento prestador de serviço de transporte\n\
zbelecimento prestador de serviço de comunicação\n\
zbelecimento de produtor rural\n\
sara consumo por demanda contratada\n\
0Aquisição de serviço de comunicação para execução de serviço da mesma natureza\n\
z por estabelecimento industrial\n\
z por estabelecimento comercial\n\
z por estabelecimento de prestador de serviço de transporte\n\
z por estabelecimento de geradora ou de distribuidora de energia elétrica\n\
z por estabelecimento de produtor rural\n\
otransporte para execução de serviço da mesma natureza\n\
zpor estabelecimento industrial\n\
zpor estabelecimento comercial\n\
zpor estabelecimento de prestador de serviço de comunicação\n\
zpor estabelecimento de geradora ou de distribuidora de energia elétrica\n\
zpor estabelecimento de produtor rural\n\
0Compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
ccomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
7de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária\n\
amercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária\n\
0Transferência para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
jcomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
mmercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
bmercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Entrada de animal - Sistema de Integração e Parceria Rural\n\
binsumo - Sistema de Integração e Parceria Rural\n\
0Retorno do animal ou da produção - Sistema de Integração e Parceria Rural\n\
8simbólico do animal ou da produção - Sistema de Integração e Parceria Rural\n\
8de insumo não utilizado na produção - Sistema de Integração e Parceria Rural\n\
0Entrada referente à remuneração do produtor no Sistema de Integração e Parceria Rural\n\
8de mercadoria recebida com fim específico de exportação\n\
acorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento\n\
v, inclusive simbólica, de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros\n\
zclusive simbólica, de mercadorias remetidas para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento\n\
zclusive simbólica, de mercadorias adquiridas ou recebidas de terceiros, remetidas para formação de lote de exportação\n\
0Compra de bem para o ativo imobilizado\n\
0Transferência de bem do ativo imobilizado\n\
0Devolução de venda de bem do ativo imobilizado\n\
0Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento\n\
0Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento\n\
0Compra de material para uso ou consumo\n\
0Transferência de material para uso ou consumo\n\
0Ressarcimento de ICMS retido por substituição tributária\n\
0Compra de combustíveis ou lubrificantes para industrialização subsequente\n\
zntes para comercialização\n\
zntes por consumidor ou usuário final\n\
0Retorno de remessa de combustíveis ou lubrificantes para venda fora do estabelecimento\n\
0Transferência de combustíveis ou lubrificantes para industrialização\n\
zbrificantes para comercialização\n\
0Devolução de venda de combustíveis ou lubrificantes destinados à industrialização subsequente\n\
zou lubrificantes destinados à comercialização\n\
zou lubrificantes destinados a consumidor ou usuário final\n\
0Entrada de combustíveis ou lubrificantes para armazenagem\n\
0Retorno de combustíveis ou lubrificantes remetidos para armazenagem\n\
0Entrada para industrialização por encomenda\n\
0Retorno de mercadoria remetida para industrialização por encomenda\n\
0Entrada de mercadoria remetida para industrialização e não aplicada no referido processo\n\
0Retorno de remessa para venda fora do estabelecimento, ou qualquer entrada e retorno de remessa efetuada pelo MEI com exceção dos classificados nos códigos 2.202, 2.503, 2.504, 2.505 e 2.506\n\
0Entrada de mercadoria recebida para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
0Retorno de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
8simbólico de mercadoria remetida para depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
0Entrada de bem por conta de contrato de comodato ou locação\n\
0Retorno de bem remetido por conta de contrato de comodato ou locação\n\
0Entrada de bonificação, doação ou brinde\n\
bamostra grátis\n\
bmercadoria ou bem recebido para demonstração ou mostruário\n\
0Retorno de mercadoria ou bem remetido para demonstração, mostruário ou treinamento\n\
zdo para exposição ou feira\n\
0Entrada de mercadoria ou bem recebido para conserto ou reparo\n\
0Retorno de mercadoria ou bem remetido para conserto ou reparo\n\
0Entrada de mercadoria recebida em consignação mercantil ou industrial\n\
0Devolução de mercadoria remetida em consignação mercantil ou industrial\n\
asimbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial\n\
0Entrada de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados\n\
0Retorno de embalagens, bombonas, vasilhames, sacarias, pallets ou assemelhados\n\
0Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro\n\
0Entrada de mercadoria recebida do vendedor remetente, em venda à ordem\n\
8para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
0Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
0Lançamento efetuado pelo tomador do serviço de transporte quando a responsabilidade de retenção do imposto for atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço\n\
0Aquisição de serviço de transporte iniciado em unidade da Federação diversa daquela onde inscrito o prestador\n\
lsujeito ao ISSQN\n\
0Entrada simbólica de mercadoria recebida para depósito em depósito fechado ou armazém geral\n\
0Outra entrada de mercadoria ou prestação de serviço não especificada\n\
0Compra para industrialização ou produção rural\n\
ccomercialização\n\
cutilização na prestação de serviço sujeita ao ICMS\n\
cindustrialização sob o regime de “drawback”\n\
cutilização na prestação de serviço sujeita ao ISSQN\n\
cindustrialização sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Devolução de venda de produção do estabelecimento\n\
mmercadoria adquirida ou recebida de terceiros\n\
0Anulação de valor relativo à prestação de serviço de comunicação\n\
zção de serviço de transporte\n\
tvenda de energia elétrica\n\
0Devolução de venda de produção do estabelecimento sob o regime de “drawback”\n\
jno mercado externo de mercadoria industrializada sob o Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Compra de energia elétrica para distribuição ou comercialização\n\
0Aquisição de serviço de comunicação para execução de serviço da mesma natureza\n\
otransporte para execução de serviço da mesma natureza\n\
zpor estabelecimento industrial\n\
zpor estabelecimento comercial\n\
zpor estabelecimento de prestador de serviço de comunicação\n\
zpor estabelecimento de geradora ou de distribuidora de energia elétrica\n\
zpor estabelecimento de produtor rural\n\
0Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação\n\
0Compra de bem para o ativo imobilizado\n\
0Entrada de produto destinado para uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior\n\
0Devolução de venda de bem do ativo imobilizado\n\
0Compra de material para uso ou consumo\n\
acombustíveis ou lubrificantes para industrialização subsequente\n\
zntes para comercialização\n\
zntes por consumidor ou usuário final\n\
0Entrada de combustíveis ou lubrificantes para consumo final, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior\n\
0Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária\n\
0Outra entrada de mercadoria ou prestação de serviço não especificada\n\
0Venda de produção do estabelecimento\n\
9mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 5.501, 5.502, 5.504 e 5.505\n\
9produção do estabelecimento, efetuada fora do estabelecimento\n\
9mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento\n\
9produção do estabelecimento que não deva por ele transitar\n\
9mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar\n\
9produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
9mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
9produção do estabelecimento remetida anteriormente em consignação industrial\n\
9mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial\n\
9produção do estabelecimento remetida anteriormente em consignação mercantil\n\
9mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil\n\
zcebida de terceiros, recebida anteriormente em consignação mercantil\n\
9produção do estabelecimento originada de encomenda para entrega futura\n\
9mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura\n\
9produção do estabelecimento industrial ou rural, entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem\n\
9mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem\n\
zcebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem\n\
9produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente\n\
9mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente\n\
0Industrialização efetuada para outra empresa\n\
za empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria\n\
0Venda de mercadoria industrializada e de insumo importado sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Transferência de produção do estabelecimento\n\
hmercadoria adquirida ou recebida de terceiros\n\
henergia elétrica\n\
hprodução do estabelecimento para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
hmercadoria adquirida ou recebida de terceiros para depósito em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
0Fornecimento de produção do estabelecimento em ato cooperativo\n\
gmercadoria adquirida ou recebida de terceiros em ato cooperativo\n\
0Devolução de compra para industrialização ou produção rural\n\
pcomercialização, ou qualquer devolução de mercadorias efetuada pelo MEI com exceção das classificadas no código 5.503\n\
0Anulação de valor relativo à aquisição de serviço de comunicação\n\
zção de serviço de transporte\n\
tcompra de energia elétrica\n\
0Devolução de mercadoria recebida em transferência para industrialização ou produção rural\n\
z transferência para comercialização\n\
dcompra para utilização na prestação de serviço\n\
dentrada, inclusive simbólica, de mercadoria com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
areferente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização\n\
zeço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização\n\
ade entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo\n\
0Venda de energia elétrica para distribuição ou comercialização\n\
vestabelecimento industrial\n\
zbelecimento comercial\n\
zbelecimento prestador de serviço de transporte\n\
zbelecimento prestador de serviço de comunicação\n\
zbelecimento de produtor rural\n\
vconsumo por demanda contratada\n\
qa não contribuinte\n\
0Prestação de serviço de comunicação para execução de serviço da mesma natureza\n\
z a estabelecimento industrial\n\
z a estabelecimento comercial\n\
z a estabelecimento de prestador de serviço de transporte\n\
z a estabelecimento de geradora ou de distribuidora de energia elétrica\n\
z a estabelecimento de produtor rural\n\
z a não contribuinte\n\
otransporte para execução de serviço da mesma natureza\n\
za estabelecimento industrial\n\
za estabelecimento comercial\n\
za estabelecimento de prestador de serviço de comunicação\n\
za estabelecimento de geradora ou de distribuidora de energia elétrica\n\
za estabelecimento de produtor rural\n\
za não contribuinte\n\
za contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal\n\
za contribuinte substituto em relação ao serviço de transporte\n\
0Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto\n\
zo de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto\n\
9mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto\n\
zcebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído\n\
0Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
hmercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
pcomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
dbem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária\n\
dmercadoria destinada para uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
bmercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária\n\
banimal - Sistema de Integração e Parceria Rural\n\
binsumo - Sistema de Integração e Parceria Rural\n\
2torno de animal ou da produção - Sistema de Integração e Parceria Rural\n\
8simbólico de animal ou da produção - Sistema de Integração e Parceria Rural\n\
8de insumos não utilizados na produção - Sistema de Integração e Parceria Rural\n\
0Saída referente à remuneração do produtor - Sistema de Integração e Parceria Rural\n\
0Remessa de produção do estabelecimento, com fim específico de exportação\n\
bmercadoria adquirida ou recebida de terceiros, com fim específico de exportação\n\
0Devolução de mercadoria recebida com fim específico de exportação\n\
0Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento\n\
m, adquiridas ou recebidas de terceiros, para formação de lote de exportação\n\
0Venda de bem do ativo imobilizado\n\
0Transferência de bem do ativo imobilizado\n\
0Devolução de compra de bem para o ativo imobilizado\n\
0Remessa de bem do ativo imobilizado para uso fora do estabelecimento\n\
0Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento\n\
dcompra de material para uso ou consumo\n\
0Transferência de material para uso ou consumo\n\
hcrédito de ICMS acumulado\n\
hsaldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS\n\
0Ressarcimento de ICMS retido por substituição tributária\n\
0Transferência de saldo devedor de ICMS de outro estabelecimento da mesma empresa\n\
0Utilização de saldo credor de ICMS para extinção por compensação de débitos fiscais\n\
0Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à industrialização subsequente\n\
ztes de produção do estabelecimento destinados à comercialização\n\
ztes de produção do estabelecimento destinados a consumidor ou usuário final\n\
ztes adquiridos ou recebidos de terceiros destinados à industrialização subsequente\n\
ztes adquiridos ou recebidos de terceiros destinados à comercialização\n\
ztes adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final\n\
0Remessa de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros para venda fora do estabelecimento\n\
0Transferência de combustíveis ou lubrificantes de produção do estabelecimento\n\
zbrificantes adquiridos ou recebidos de terceiro\n\
0Devolução de compra de combustíveis ou lubrificantes adquiridos para industrialização subsequente\n\
z ou lubrificantes adquiridos para comercialização\n\
z ou lubrificantes adquiridos por consumidor ou usuário final\n\
0Remessa para armazenagem de combustíveis ou lubrificantes\n\
2torno de combustíveis ou lubrificantes recebidos para armazenagem\n\
8simbólico de combustíveis ou lubrificantes recebidos para armazenagem\n\
2messa por conta e ordem de terceiros de combustíveis ou lubrificantes recebidos para armazenagem\n\
0Venda de combustíveis ou lubrificantes a consumidor ou usuário final estabelecido em outra unidade da Federação\n\
0Remessa para industrialização por encomenda\n\
2torno de mercadoria utilizada na industrialização por encomenda\n\
mrecebida para industrialização e não aplicada no referido processo\n\
2messa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 5.502 e 5.505\n\
ddepósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
2torno de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
8simbólico de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
2messa de bem por conta de contrato de comodato ou locação\n\
2torno de bem recebido por conta de contrato de comodato ou locação\n\
2messa em bonificação, doação ou brinde\n\
8de amostra grátis\n\
bmercadoria ou bem para demonstração, mostruário ou treinamento\n\
2torno de mercadoria ou bem recebido para demonstração ou mostruário\n\
2messa de mercadoria ou bem para exposição ou feira\n\
yconserto ou reparo\n\
2torno de mercadoria ou bem recebido para conserto ou reparo\n\
2messa de mercadoria em consignação mercantil ou industrial\n\
0Devolução de mercadoria recebida em consignação mercantil ou industrial\n\
asimbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial\n\
0Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados\n\
0Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados\n\
0Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura\n\
0Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado\n\
8para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
2torno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente\n\
0Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação\n\
wbaixa de estoque decorrente de perda, roubo, deterioração\n\
zxa de estoque decorrente do encerramento da atividade do estabelecimento da empresa ou transferência por venda do fundo de comércio\n\
kem decorrência de emissão de documento fiscal relativo à operação ou prestação também acobertada por documento fiscal do varejo\n\
zda responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço\n\
0Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador\n\
lsujeita ao ISSQN\n\
0Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado\n\
0Outra saída de mercadoria ou prestação de serviço não especificada\n\
0Venda de produção do estabelecimento\n\
9mercadoria adquirida ou recebida de terceiros, ou qualquer venda de mercadoria efetuada pelo MEI com exceção das saídas classificadas nos códigos 6.501, 6.502, 6.504 e 6.505\n\
9produção do estabelecimento, efetuada fora do estabelecimento\n\
9mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento\n\
9produção do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
9mercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
9produção do estabelecimento, destinada a não contribuinte\n\
9mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte\n\
9produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
9mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio\n\
9produção do estabelecimento remetida anteriormente em consignação industrial\n\
9mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial\n\
9produção do estabelecimento remetida anteriormente em consignação mercantil\n\
9mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil\n\
zcebida de terceiros, recebida anteriormente em consignação mercantil\n\
9produção do estabelecimento originada de encomenda para entrega futura\n\
9mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura\n\
9produção do estabelecimento industrial ou rural, entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem\n\
9mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem\n\
zcebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem\n\
9produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente\n\
9mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente\n\
0Industrialização efetuada para outra empresa\n\
za empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirente da mercadoria\n\
0Venda de mercadoria industrializada e de insumo importado sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Remessa de produção do estabelecimento, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Fixação de preço de produção do estabelecimento, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
0Transferência de produção do estabelecimento\n\
hmercadoria adquirida ou recebida de terceiros\n\
henergia elétrica\n\
hprodução do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
hmercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
0Fornecimento de produção do estabelecimento em ato cooperativo\n\
gmercadoria adquirida ou recebida de terceiros em ato cooperativo\n\
0Devolução de compra para industrialização ou produção rural\n\
pcomercialização, ou qualquer devolução de mercadoria efetuada pelo MEI com exceção das classificadas no código 6.503\n\
0Anulação de valor relativo à aquisição de serviço de comunicação\n\
zção de serviço de transporte\n\
tcompra de energia elétrica\n\
0Devolução de mercadoria recebida em transferência para industrialização ou produção rural\n\
z transferência para comercialização\n\
dcompra para utilização na prestação de serviço\n\
dentrada, inclusive simbólica, de mercadoria, com previsão de posterior ajuste ou fixação de preço, em ato cooperativo\n\
areferente à fixação de preço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para comercialização\n\
zeço de produção do estabelecimento produtor, inclusive quando remetidas anteriormente com previsão de posterior ajuste ou fixação de preço, em ato cooperativo, para industrialização\n\
ade entrada decorrente do fornecimento de produto ou mercadoria em ato cooperativo\n\
0Venda de energia elétrica para distribuição ou comercialização\n\
vestabelecimento industrial\n\
zbelecimento comercial\n\
zbelecimento prestador de serviço de transporte\n\
zbelecimento prestador de serviço de comunicação\n\
zbelecimento de produtor rural\n\
vconsumo por demanda contratada\n\
qa não contribuinte\n\
0Prestação de serviço de comunicação para execução de serviço da mesma natureza\n\
z a estabelecimento industrial\n\
z a estabelecimento comercial\n\
z a estabelecimento de prestador de serviço de transporte\n\
z a estabelecimento de geradora ou de distribuidora de energia elétrica\n\
z a estabelecimento de produtor rural\n\
z a não contribuinte\n\
otransporte para execução de serviço da mesma natureza\n\
za estabelecimento industrial\n\
za estabelecimento comercial\n\
za estabelecimento de prestador de serviço de comunicação\n\
za estabelecimento de geradora ou de distribuidora de energia elétrica\n\
za estabelecimento de produtor rural\n\
za não contribuinte\n\
za contribuinte ou a não contribuinte quando a mercadoria transportada está dispensada de emissão de nota fiscal\n\
za contribuinte substituto em relação ao serviço de transporte\n\
0Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto\n\
zo de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto\n\
9mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto\n\
ksujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente\n\
0Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
hmercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Devolução de compra para industrialização ou produção rural em operação com mercadoria sujeita ao regime de substituição tributária\n\
pcomercialização em operação com mercadoria sujeita ao regime de substituição tributária\n\
dbem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária\n\
dmercadoria destinada para uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária\n\
0Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária\n\
bmercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária\n\
banimal - Sistema de Integração e Parceria Rural\n\
binsumo - Sistema de Integração e Parceria Rural\n\
2torno de animal ou da produção - Sistema de Integração e Parceria Rural\n\
8simbólico de animal ou da produção - Sistema de Integração e Parceria Rural\n\
8de insumos não utilizados na produção - Sistema de Integração e Parceria Rural\n\
0Saída referente à remuneração do produtor - Sistema de Integração e Parceria Rural\n\
0Remessa de produção do estabelecimento, com fim específico de exportação\n\
bmercadoria adquirida ou recebida de terceiros, com fim específico de exportação\n\
0Devolução de mercadoria recebida com fim específico de exportação\n\
0Remessa de mercadorias para formação de lote de exportação, de produtos industrializados ou produzidos pelo próprio estabelecimento\n\
m, adquiridas ou recebidas de terceiros, para formação de lote de exportação\n\
0Venda de bem do ativo imobilizado\n\
0Transferência de bem do ativo imobilizado\n\
0Devolução de compra de bem para o ativo imobilizado\n\
0Remessa de bem do ativo imobilizado para uso fora do estabelecimento\n\
0Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento\n\
dcompra de material para uso ou consumo\n\
0Transferência de material para uso ou consumo\n\
0Ressarcimento de ICMS retido por substituição tributária\n\
0Venda de combustíveis ou lubrificantes de produção do estabelecimento destinados à industrialização subsequente\n\
ztes de produção do estabelecimento destinados à comercialização\n\
ztes de produção do estabelecimento destinados a consumidor ou usuário final\n\
ztes adquiridos ou recebidos de terceiros destinados à industrialização subsequente\n\
ztes adquiridos ou recebidos de terceiros destinados à comercialização\n\
ztes adquiridos ou recebidos de terceiros destinados a consumidor ou usuário final\n\
0Remessa de combustíveis ou lubrificantes adquiridos ou recebidos de terceiros para venda fora do estabelecimento\n\
0Transferência de combustíveis ou lubrificantes de produção do estabelecimento\n\
zbrificantes adquiridos ou recebidos de terceiro\n\
0Devolução de compra de combustíveis ou lubrificantes adquiridos para industrialização subsequente\n\
z ou lubrificantes adquiridos para comercialização\n\
z ou lubrificantes adquiridos por consumidor ou usuário final\n\
0Remessa para armazenagem de combustíveis ou lubrificantes\n\
2torno de combustíveis ou lubrificantes recebidos para armazenagem\n\
8simbólico de combustíveis ou lubrificantes recebidos para armazenagem\n\
2messa por conta e ordem de terceiros de combustíveis ou lubrificantes recebidos para armazenagem\n\
0Venda de combustíveis ou lubrificantes a consumidor ou usuário final estabelecido em outra unidade da Federação diferente da que ocorrer o consumo\n\
0Remessa para industrialização por encomenda\n\
2torno de mercadoria utilizada na industrialização por encomenda\n\
mrecebida para industrialização e não aplicada no referido processo\n\
2messa para venda fora do estabelecimento, ou qualquer remessa efetuada pelo MEI com exceção das classificadas nos códigos 6.502 e 6.505\n\
ddepósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
2torno de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
8simbólico de mercadoria depositada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro\n\
2messa de bem por conta de contrato de comodato ou locação\n\
2torno de bem recebido por conta de contrato de comodato ou locação\n\
2messa em bonificação, doação ou brinde\n\
8de amostra grátis\n\
bmercadoria ou bem para demonstração, mostruário ou treinamento\n\
2torno de mercadoria ou bem recebido para demonstração ou mostruário\n\
2messa de mercadoria ou bem para exposição ou feira\n\
yconserto ou reparo\n\
2torno de mercadoria ou bem recebido para conserto ou reparo\n\
2messa de mercadoria em consignação mercantil ou industrial\n\
0Devolução de mercadoria recebida em consignação mercantil ou industrial\n\
asimbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial\n\
0Remessa de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados\n\
0Devolução de embalagens, bombonas, vasilhames, sacarias, pallets, containers ou assemelhados\n\
0Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura\n\
0Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem ou em operações com armazém geral ou depósito fechado\n\
8para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente\n\
2torno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente\n\
0Lançamento efetuado em decorrência de emissão de documento fiscal relativo à operação ou prestação também acobertada por documento fiscal do varejo\n\
zda responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de transporte realizado por transportador autônomo ou por transportador não inscrito na unidade da Federação onde iniciado o serviço\n\
0Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador\n\
lsujeita ao ISSQN\n\
0Remessa simbólica de mercadoria depositada em armazém geral ou depósito fechado\n\
0Outra saída de mercadoria ou prestação de serviço não especificada\n\
0Venda de produção do estabelecimento\n\
9mercadoria adquirida ou recebida de terceiros\n\
9produção do estabelecimento armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
9mercadoria adquirida ou recebida de terceiros armazenada em depósito fechado, armazém geral ou outro estabelecimento da mesma empresa ou de terceiro, que não deva por ele transitar\n\
9produção do estabelecimento sob o regime de “drawback”\n\
zo ao mercado externo de mercadoria industrializada sob o amparo do Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Devolução de compra para industrialização ou produção rural\n\
pcomercialização\n\
0Anulação de valor relativo à aquisição de serviço de comunicação\n\
zção de serviço de transporte\n\
tcompra de energia elétrica\n\
0Devolução de compra para utilização na prestação de serviço\n\
js para industrialização sob o regime de “drawback”\n\
zlização sob o regime de Regime Aduaneiro Especial de Entreposto Industrial sob Controle Informatizado do Sistema Público de Escrituração Digital (Recof-Sped)\n\
0Venda de energia elétrica para o exterior\n\
0Prestação de serviço de comunicação para execução de serviço da mesma natureza\n\
otransporte\n\
0Exportação de mercadorias recebidas com fim específico de exportação\n\
o que foi objeto de formação de lote de exportação\n\
0Venda de bem do ativo imobilizado\n\
0Saída de produto destinado para uso ou consumo de bordo, em embarcações ou aeronaves exclusivamente em tráfego internacional com destino ao exterior\n\
0Devolução de compra de bem para o ativo imobilizado\n\
nmaterial para uso ou consumo\n\
0Venda de combustíveis ou lubrificantes de produção do estabelecimento\n\
ztes adquiridos ou recebidos de terceiros\n\
0Saída de combustíveis ou lubrificantes a consumidor ou usuário final\n\
0Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária\n\
0Outra saída de mercadoria ou prestação de serviço não especificada";
