import { IBGE_UF_CODES } from "../_internals/constants/ibge-uf-codes";
import {
	CHECK_DIGIT_INDEX,
	CODE_START,
	CPF_PADDING,
	GENERATOR_ENVIRONMENTS,
	GENERATOR_ENVIRONMENT_INDEX,
	MONTH_START,
	NUMBER_START,
	TAX_ID_START,
	TAX_ID_TYPES,
	TAX_ID_TYPE_INDEX,
	YEAR_START,
} from "../_internals/constants/nfse-key";
import { type StateCode } from "../_internals/constants/states";
import { readNfseKey } from "../_internals/read-nfse-key/read-nfse-key";
import { isValidNfseKey } from "../is-valid-nfse-key/is-valid-nfse-key";

export type { StateCode } from "../_internals/constants/states";

/**
 * The system that generated the NFS-e (`ambGer`): `1` the system of the municipality
 * (Prefeitura), `2` the Sistema Nacional NFS-e (Sefin Nacional). Spelled out instead of derived
 * from `GENERATOR_ENVIRONMENTS` because the allowlist is internal and API Extractor cannot name
 * it in the public report; the type test of `get-nfse-key-info.test.ts` pins the two together.
 */
export type NfseKeyGeneratorEnvironment = 1 | 2;

/** The kind of federal registration ("Tipo de Inscrição Federal") the key carries. */
export type NfseKeyTaxIdType = "cpf" | "cnpj";

/** The fields `getNfseKeyInfo` reads out of a national NFS-e access key (chave de acesso). */
export type NfseKeyInfo = {
	/** Seven digit IBGE code of the municipality of the issuer's address. */
	municipalityCode: string;
	/** Two letter code of the state (UF) of that municipality, read from its first two digits. */
	stateCode: StateCode;
	/** The system that generated the NFS-e (`ambGer`): 1 municipality, 2 Sistema Nacional NFS-e. */
	generatorEnvironment: NfseKeyGeneratorEnvironment;
	/** Whether the issuer is identified by a CPF or by a CNPJ. */
	taxIdType: NfseKeyTaxIdType;
	/**
	 * The 11 digit CPF (without the `000` padding of the key) or the 14 character CNPJ of the
	 * issuer, numeric or alphanumeric, its letters in upper case.
	 */
	taxId: string;
	/** NFS-e number (`nNFSe`), sequential by issuer, 1 to 9999999999999. */
	number: number;
	/** Four digit issue year. */
	year: number;
	/** Issue month, 1 to 12. */
	month: number;
	/** The 9 digit random numeric code drawn by the system that generated the NFS-e. */
	code: string;
	/** The modulo 11 check digit of the key. */
	checkDigit: number;
};

/**
 * Parses the access key (chave de acesso) of a national NFS-e, the Nota Fiscal de Serviço
 * eletrônica of the Sistema Nacional NFS-e, into its fields.
 *
 * The key is one block of 50 characters: `Cód.Mun.(7) Amb.Ger.(1) Tipo de Inscrição Federal(1)
 * Inscrição Federal(14) nNFSe(13) AAMM(4) Cód.Num.(9) DV(1)`, all digits except an alphanumeric
 * CNPJ in the "Inscrição Federal". It is accepted as it is written in the documents (`chNFSe`,
 * `chSubstda`, the DANFSe, which prints it as a single block) or with the `NFS` literal the `Id`
 * attribute of `infNFSe` puts in front of it, surrounding whitespace aside. The DANFSe prints the
 * key as a single block, so it has no printed mask; the boundaries between its 8 fields accept the
 * mask characters `isValidCpf` reads (whitespace, `.`, `-` or `/`, alone or in a run), while a
 * separator inside a field makes the value invalid. The keys of the municipal NFS-e models that are
 * not the national standard are out of scope.
 *
 * The key is checked by `isValidNfseKey`, and `null` comes back exactly when it returns false. What
 * it checks: the first two digits of the municipality code are an IBGE UF code, `ambGer` is 1 or 2,
 * the registration type is 1 (CPF, the 11 digits left padded with `000`) or 2 (CNPJ, numeric or
 * alphanumeric, as `isValidCnpj` with version 2 reads it) and the CPF or CNPJ has valid check
 * digits of its own (rules E1280 and E1284 of the ANEXO I reject an NFS-e whose issuer fails them),
 * `nNFSe` is not all zeros, the month is 01 to 12 and the check digit matches. The municipality
 * code is not looked up in the IBGE table.
 *
 * The check digit is a modulus 11 over the first 49 characters, weights 2 to 9 cycling from the
 * right, where a remainder of 0 or 1 gives 0. The official text only says "algoritmo do módulo
 * 11"; the weights and the remainder rule are the ones of the DF-e access key and were
 * confirmed against more than a hundred NFS-e keys found in public repositories, generated by
 * both environments, remainders 0, 1 and 10 included.
 *
 * An alphanumeric CNPJ is accepted since the restricted-production (RTC) schema bundle of
 * 2026-07-27 widened `TSIdNFSe` to letters in the registration; the service handles it in
 * production since 2026-08-10, while the production bundle of 2026-02-09 is still digits only. Lower case input is read in
 * upper case, as `isValidCnpj` with version 2 reads it, and `taxId` comes back upper cased. No
 * official document states how a letter enters the check digit of the key: the NFS-e technical
 * notes 001 to 009, the Anexo I and the Perguntas e Respostas of 08/09/2026 do not, and Nota
 * Técnica Conjunta 2025.001 lists the DF-e it covers without the NFS-e. By analogy with that NT
 * and the CNPJ's own check digits, each character counts as its ASCII code minus 48 (`A` is
 * 17). `isValidNfseKey` cites the sources.
 *
 * @param {string} value - The access key value to be parsed.
 * @returns {NfseKeyInfo | null} The parsed access key, or `null` when `isValidNfseKey` rejects it.
 *
 * @see Official: https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/documentacao-atual
 * Sistema Nacional NFS-e, current technical documentation: `NFSe-ESQUEMAS_XSD-v1.01`
 * (`tiposSimples_v1.01.xsd`: `TSIdNFSe`, `TSChaveNFSe`, `TSAmbGeradorNFSe`, `TSNNFSe`) and
 * `ANEXO_I-SEFIN_ADN-DPS_NFSe-SNNFSe` v1.01 (field `NFSe/infNFSe/id`, rules E1263, E1280, E1284
 * and E0042).
 * @see Official: https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/documentacao-atual/manual-contribuintes-emissor-publico-api-emissao-decisao-administrativa-e-judicial.pdf
 * Manual de Contribuintes, Emissão por Decisão Administrativa ou Judicial, field `id`: "O dígito
 * verificador deve ser calculado segundo o algoritmo do módulo 11".
 * @see Official: https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/rtc/nt-008-se-cgnfse-danfse-20260714-v1-02.pdf
 * Nota Técnica SE/CGNFS-e 008 (DANFSe), item 2.1.1: the key is printed as a single block of 50
 * digits.
 * @see Based on: https://github.com/nfse-nacional/nfse-php
 * Test fixtures with NFS-e keys used to confirm the check digit rule; none of them is reproduced
 * in the tests of this package, whose keys are synthetic.
 * @see Based on: https://github.com/Unimake/DFe
 * Example and test XMLs of the NACIONAL standard, second source of keys for the same check.
 *
 * @example
 * ```typescript
 * getNfseKeyInfo("35503082258716523000119000000000001226011357924683");
 * // { municipalityCode: "3550308", stateCode: "SP", generatorEnvironment: 2, taxIdType: "cnpj",
 * //   taxId: "58716523000119", number: 12, year: 2026, month: 1, code: "135792468", checkDigit: 3 }
 *
 * getNfseKeyInfo("35503082212abc34501de35000000000001226091357924682");
 * // { municipalityCode: "3550308", stateCode: "SP", generatorEnvironment: 2, taxIdType: "cnpj",
 * //   taxId: "12ABC34501DE35", number: 12, year: 2026, month: 9, code: "135792468",
 * //   checkDigit: 2 }
 *
 * getNfseKeyInfo("invalid"); // null
 * ```
 */
export const getNfseKeyInfo = (value: string): NfseKeyInfo | null => {
	const key = typeof value === "string" ? readNfseKey(value) : null;

	// Stryker disable next-line ConditionalExpression: the null check only narrows the type; a value `readNfseKey` cannot read is one `isValidNfseKey` turns down as well.
	if (key === null || !isValidNfseKey(key)) return null;
	const taxIdType = TAX_ID_TYPES[key[TAX_ID_TYPE_INDEX]];
	const taxIdStart = taxIdType === "cpf" ? TAX_ID_START + CPF_PADDING.length : TAX_ID_START;

	return {
		municipalityCode: key.slice(0, GENERATOR_ENVIRONMENT_INDEX),
		stateCode: IBGE_UF_CODES[key.slice(0, 2)],
		generatorEnvironment: GENERATOR_ENVIRONMENTS[Number(key[GENERATOR_ENVIRONMENT_INDEX]) - 1],
		taxIdType,
		taxId: key.slice(taxIdStart, NUMBER_START),
		number: Number(key.slice(NUMBER_START, YEAR_START)),
		year: 2000 + Number(key.slice(YEAR_START, MONTH_START)),
		month: Number(key.slice(MONTH_START, CODE_START)),
		code: key.slice(CODE_START, CHECK_DIGIT_INDEX),
		checkDigit: Number(key[CHECK_DIGIT_INDEX]),
	};
};
