/**
 * Turns the recorded vectors into a table every target can read, and writes the small driver
 * each language uses to replay it.
 *
 * A tab separated file rather than JSON: every target can split a line without a parser, and
 * the escaping rules are the same everywhere, which keeps the drivers honest and tiny.
 *
 * Usage: `node spec/bridge/conformance/drivers.ts`
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Case } from "./vectors.ts";

const bridge = resolve(import.meta.dirname, "..");
const vectors = JSON.parse(readFileSync(resolve(bridge, "conformance/vectors.json"), "utf8")) as {
	cases: Case[];
};

/** Escapes the three characters the table format reserves. */
const cell = (value: string): string =>
	value.replaceAll("\\", "\\\\").replaceAll("\t", "\\t").replaceAll("\n", "\\n");

const columns = ["fn", "input", "kind", "version", "pad", "obfuscate", "expected"];
const lines = [columns.join("\t")];

for (const entry of vectors.cases) {
	const options = entry.options as { version?: number; pad?: boolean; obfuscate?: boolean };

	lines.push(
		[
			entry.fn,
			cell(String(entry.input)),
			typeof entry.input === "number" ? "number" : "string",
			options.version === undefined ? "" : String(options.version),
			options.pad === true ? "1" : "",
			options.obfuscate === true ? "1" : "",
			cell(entry.expected),
		].join("\t"),
	);
}

const tablePath = resolve(bridge, "conformance/vectors.tsv");

writeFileSync(tablePath, `${lines.join("\n")}\n`);

const files: Record<string, string> = {
	"out/typescript/conformance.ts": `// Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { formatCnpj, isValidCnpj } from "./_bridge/cnpj.ts";
import { type StateCode, getMunicipalities } from "./_bridge/municipalities.ts";

const table = readFileSync(resolve(import.meta.dirname, "../../conformance/vectors.tsv"), "utf8");
const unescape = (value: string): string =>
	value.replaceAll("\\\\t", "\\t").replaceAll("\\\\n", "\\n").replaceAll("\\\\\\\\", "\\\\");

let passed = 0;
let failed = 0;

for (const line of table.split("\\n").slice(1)) {
	if (line === "") continue;

	const [fn, rawInput, kind, version, pad, obfuscate, rawExpected] = line.split("\\t");
	const input = unescape(rawInput);
	const expected = unescape(rawExpected);
	const options: Record<string, unknown> = {};

	if (version !== "") options["version"] = Number(version);
	if (pad === "1") options["pad"] = true;
	if (obfuscate === "1") options["obfuscate"] = true;

	const value = kind === "number" ? Number(input) : input;
	const actual =
		fn === "isValidCnpj"
			? String(isValidCnpj(value as string, options))
			: formatCnpj(value as string, options);

	if (actual === expected) passed++;
	else {
		failed++;

		if (failed <= 5)
			console.error(\`FAIL \${fn}(\${JSON.stringify(input)}) expected \${JSON.stringify(expected)} got \${JSON.stringify(actual)}\`);
	}
}

console.log(\`typescript: \${passed}/\${passed + failed} conformance checks passed\`);

const dump: string[] = [];

for (const key of readFileSync(resolve(import.meta.dirname, "../../conformance/municipalities.keys.txt"), "utf8").trimEnd().split("\\n")) {
	const found = key === "*" ? getMunicipalities() : getMunicipalities(key as StateCode);

	dump.push(\`\${key}\\t\${found.length}\`);

	for (const municipality of found)
		dump.push(\`\${municipality.code}|\${municipality.name}|\${municipality.stateCode}\`);
}

const expectedDump = readFileSync(resolve(import.meta.dirname, "../../conformance/municipalities.expected.txt"), "utf8").trimEnd().split("\\n");
let dumpFailed = 0;

for (let index = 0; index < Math.max(dump.length, expectedDump.length); index++) {
	if (dump[index] === expectedDump[index]) continue;

	dumpFailed++;

	if (dumpFailed <= 5)
		console.error(\`FAIL municipalities line \${index + 1}: expected \${JSON.stringify(expectedDump[index])} got \${JSON.stringify(dump[index])}\`);
}

console.log(\`typescript: \${expectedDump.length - dumpFailed}/\${expectedDump.length} municipality lines matched\`);
process.exit(failed === 0 && dumpFailed === 0 ? 0 : 1);
`,

	"out/python/conformance.py": `# Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.
"""Replays the vectors recorded from the JavaScript package against the generated Python."""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from brutils_bridge.cnpj import (  # noqa: E402
    FormatCnpjOptions,
    IsValidCnpjOptions,
    format_cnpj,
    is_valid_cnpj,
)
from brutils_bridge.municipalities import get_municipalities  # noqa: E402


def unescape(value):
    return value.replace("\\\\t", "\\t").replace("\\\\n", "\\n").replace("\\\\\\\\", "\\\\")


passed = 0
failed = 0

with (HERE.parent.parent / "conformance/vectors.tsv").open(encoding="utf-8") as handle:
    next(handle)

    for line in handle:
        if line.strip("\\n") == "":
            continue

        fn, raw_input, kind, version, pad, obfuscate, raw_expected = line.rstrip("\\n").split("\\t")
        value = unescape(raw_input)
        expected = unescape(raw_expected)
        number = float(value) if kind == "number" else None

        if kind == "number":
            value = int(number) if number.is_integer() else number

        if fn == "isValidCnpj":
            options = IsValidCnpjOptions(version=int(version) if version else None)
            actual = str(is_valid_cnpj(value, options)).lower()
        else:
            options = FormatCnpjOptions(
                version=int(version) if version else None,
                pad=True if pad == "1" else None,
                obfuscate=True if obfuscate == "1" else None,
            )
            actual = format_cnpj(value, options)

        if actual == expected:
            passed += 1
        else:
            failed += 1

            if failed <= 5:
                print(f"FAIL {fn}({value!r}) expected {expected!r} got {actual!r}", file=sys.stderr)

print(f"python: {passed}/{passed + failed} conformance checks passed")

CONFORMANCE = HERE.parent.parent / "conformance"
dump = []

for key in (CONFORMANCE / "municipalities.keys.txt").read_text(encoding="utf-8").rstrip("\\n").split("\\n"):
    found = get_municipalities(None) if key == "*" else get_municipalities(key)
    dump.append(f"{key}\\t{len(found)}")

    for municipality in found:
        dump.append(f"{municipality.code}|{municipality.name}|{municipality.state_code}")

expected_dump = (
    (CONFORMANCE / "municipalities.expected.txt").read_text(encoding="utf-8").rstrip("\\n").split("\\n")
)
dump_failed = 0

for index in range(max(len(dump), len(expected_dump))):
    got = dump[index] if index < len(dump) else None
    want = expected_dump[index] if index < len(expected_dump) else None

    if got == want:
        continue

    dump_failed += 1

    if dump_failed <= 5:
        print(f"FAIL municipalities line {index + 1}: expected {want!r} got {got!r}", file=sys.stderr)

print(f"python: {len(expected_dump) - dump_failed}/{len(expected_dump)} municipality lines matched")
sys.exit(0 if failed == 0 and dump_failed == 0 else 1)
`,

	"out/go/conformance/main.go": `// Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.

package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"

	"brazilianutils/bridge/cnpj"
	"brazilianutils/bridge/municipalities"
)

func unescape(value string) string {
	value = strings.ReplaceAll(value, "\\\\t", "\\t")
	value = strings.ReplaceAll(value, "\\\\n", "\\n")

	return strings.ReplaceAll(value, "\\\\\\\\", "\\\\")
}

func intPtr(value int64) *int64 { return &value }
func boolPtr(value bool) *bool  { return &value }

func main() {
	file, err := os.Open("../../conformance/vectors.tsv")

	if err != nil {
		panic(err)
	}

	defer file.Close()

	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	scanner.Scan()

	passed := 0
	failed := 0
	skipped := 0

	for scanner.Scan() {
		line := scanner.Text()

		if line == "" {
			continue
		}

		parts := strings.Split(line, "\\t")
		fn, input, kind, version, pad, obfuscate, expected := parts[0], unescape(parts[1]), parts[2], parts[3], parts[4], parts[5], unescape(parts[6])

		// A number input to a validator cannot be written in Go: the parameter is a string, so
		// the JavaScript quirk "a number is never a valid CNPJ" has no Go equivalent.
		if kind == "number" && fn == "isValidCnpj" {
			skipped++

			continue
		}

		var actual string

		if fn == "isValidCnpj" {
			options := &cnpj.IsValidCnpjOptions{}

			if version != "" {
				parsed, _ := strconv.ParseInt(version, 10, 64)
				options.Version = intPtr(parsed)
			}

			actual = strconv.FormatBool(cnpj.IsValidCnpj(input, options))
		} else {
			options := &cnpj.FormatCnpjOptions{}

			if version != "" {
				parsed, _ := strconv.ParseInt(version, 10, 64)
				options.Version = intPtr(parsed)
			}

			if pad == "1" {
				options.Pad = boolPtr(true)
			}

			if obfuscate == "1" {
				options.Obfuscate = boolPtr(true)
			}

			actual = cnpj.FormatCnpj(input, options)
		}

		if actual == expected {
			passed++
		} else {
			failed++

			if failed <= 5 {
				fmt.Fprintf(os.Stderr, "FAIL %s(%q) expected %q got %q\\n", fn, input, expected, actual)
			}
		}
	}

	fmt.Printf("go: %d/%d conformance checks passed (%d not expressible)\\n", passed, passed+failed, skipped)

	keys, err := os.ReadFile("../../conformance/municipalities.keys.txt")

	if err != nil {
		panic(err)
	}

	dump := []string{}

	for _, key := range strings.Split(strings.TrimRight(string(keys), "\\n"), "\\n") {
		var found []*municipalities.Municipality

		if key == "*" {
			found = municipalities.GetMunicipalities(nil)
		} else {
			asked := key
			found = municipalities.GetMunicipalities(&asked)
		}

		dump = append(dump, fmt.Sprintf("%s\\t%d", key, len(found)))

		for _, municipality := range found {
			dump = append(dump, fmt.Sprintf("%s|%s|%s", municipality.Code, municipality.Name, municipality.StateCode))
		}
	}

	raw, err := os.ReadFile("../../conformance/municipalities.expected.txt")

	if err != nil {
		panic(err)
	}

	expectedDump := strings.Split(strings.TrimRight(string(raw), "\\n"), "\\n")
	dumpFailed := 0
	longest := len(dump)

	if len(expectedDump) > longest {
		longest = len(expectedDump)
	}

	for index := 0; index < longest; index++ {
		got := ""
		want := ""

		if index < len(dump) {
			got = dump[index]
		}

		if index < len(expectedDump) {
			want = expectedDump[index]
		}

		if got == want {
			continue
		}

		dumpFailed++

		if dumpFailed <= 5 {
			fmt.Fprintf(os.Stderr, "FAIL municipalities line %d: expected %q got %q\\n", index+1, want, got)
		}
	}

	fmt.Printf("go: %d/%d municipality lines matched\\n", len(expectedDump)-dumpFailed, len(expectedDump))

	if failed > 0 || dumpFailed > 0 {
		os.Exit(1)
	}
}
`,

	"out/rust/src/bin/conformance.rs": `// Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.

use brazilian_utils_bridge::cnpj;
use brazilian_utils_bridge::municipalities;

fn unescape(value: &str) -> String {
    value.replace("\\\\t", "\\t").replace("\\\\n", "\\n").replace("\\\\\\\\", "\\\\")
}

fn main() {
    let table = std::fs::read_to_string("../../conformance/vectors.tsv").expect("vectors");
    let mut passed = 0;
    let mut failed = 0;
    let mut skipped = 0;

    for line in table.lines().skip(1) {
        if line.is_empty() {
            continue;
        }

        let parts: Vec<&str> = line.split('\\t').collect();
        let (fn_name, input, kind) = (parts[0], unescape(parts[1]), parts[2]);
        let (version, pad, obfuscate, expected) = (parts[3], parts[4], parts[5], unescape(parts[6]));

        // A number input to a validator cannot be written in Rust: the parameter is a \`&str\`.
        if kind == "number" && fn_name == "isValidCnpj" {
            skipped += 1;

            continue;
        }

        let actual = if fn_name == "isValidCnpj" {
            let options = cnpj::IsValidCnpjOptions {
                version: if version.is_empty() { None } else { Some(version.parse().unwrap()) },
            };

            cnpj::is_valid_cnpj(&input, Some(&options)).to_string()
        } else {
            let options = cnpj::FormatCnpjOptions {
                version: if version.is_empty() { None } else { Some(version.parse().unwrap()) },
                pad: if pad == "1" { Some(true) } else { None },
                obfuscate: if obfuscate == "1" { Some(true) } else { None },
            };

            cnpj::format_cnpj(&input, Some(&options))
        };

        if actual == expected {
            passed += 1;
        } else {
            failed += 1;

            if failed <= 5 {
                eprintln!("FAIL {}({:?}) expected {:?} got {:?}", fn_name, input, expected, actual);
            }
        }
    }

    println!("rust: {}/{} conformance checks passed ({} not expressible)", passed, passed + failed, skipped);

    let keys = std::fs::read_to_string("../../conformance/municipalities.keys.txt").expect("keys");
    let mut dump: Vec<String> = Vec::new();

    for key in keys.trim_end_matches('\\n').split('\\n') {
        let found = if key == "*" {
            municipalities::get_municipalities(None)
        } else {
            municipalities::get_municipalities(Some(key))
        };

        dump.push(format!("{}\\t{}", key, found.len()));

        for municipality in &found {
            dump.push(format!("{}|{}|{}", municipality.code, municipality.name, municipality.state_code));
        }
    }

    let raw = std::fs::read_to_string("../../conformance/municipalities.expected.txt").expect("dump");
    let expected_dump: Vec<&str> = raw.trim_end_matches('\\n').split('\\n').collect();
    let mut dump_failed = 0;

    for index in 0..std::cmp::max(dump.len(), expected_dump.len()) {
        let got = dump.get(index).map(String::as_str).unwrap_or("");
        let want = *expected_dump.get(index).unwrap_or(&"");

        if got == want {
            continue;
        }

        dump_failed += 1;

        if dump_failed <= 5 {
            eprintln!("FAIL municipalities line {}: expected {:?} got {:?}", index + 1, want, got);
        }
    }

    println!("rust: {}/{} municipality lines matched", expected_dump.len() - dump_failed, expected_dump.len());

    if failed > 0 || dump_failed > 0 {
        std::process::exit(1);
    }
}
`,
	"out/ruby/conformance.rb": `# frozen_string_literal: true

# Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.

require_relative 'lib/brazilian_utils_bridge/cnpj'
require_relative 'lib/brazilian_utils_bridge/municipalities'

def unescape(value)
  value.gsub('\\\\t', "\\t").gsub('\\\\n', "\\n").gsub('\\\\\\\\', '\\\\')
end

passed = 0
failed = 0

lines = File.readlines(File.expand_path('../../conformance/vectors.tsv', __dir__), encoding: 'UTF-8')

lines.drop(1).each do |line|
  next if line.strip.empty?

  fn, raw_input, kind, version, pad, obfuscate, raw_expected = line.chomp("\\n").split("\\t", -1)
  value = unescape(raw_input)
  expected = unescape(raw_expected)
  value = value.to_i if kind == 'number'

  actual =
    if fn == 'isValidCnpj'
      options = BrazilianUtilsBridge::Cnpj::IsValidCnpjOptions.new(
        version: version.empty? ? nil : version.to_i
      )
      BrazilianUtilsBridge::Cnpj.is_valid_cnpj(value, options).to_s
    else
      options = BrazilianUtilsBridge::Cnpj::FormatCnpjOptions.new(
        version: version.empty? ? nil : version.to_i,
        pad: pad == '1' ? true : nil,
        obfuscate: obfuscate == '1' ? true : nil
      )
      BrazilianUtilsBridge::Cnpj.format_cnpj(value, options)
    end

  if actual == expected
    passed += 1
  else
    failed += 1
    warn "FAIL #{fn}(#{value.inspect}) expected #{expected.inspect} got #{actual.inspect}" if failed <= 5
  end
end

puts "ruby: #{passed}/#{passed + failed} conformance checks passed"

conformance = File.expand_path('../../conformance', __dir__)
keys = File.read(File.join(conformance, 'municipalities.keys.txt'), encoding: 'UTF-8')
dump = []

keys.chomp("\n").split("\n", -1).each do |key|
  found =
    if key == '*'
      BrazilianUtilsBridge::Municipalities.get_municipalities(nil)
    else
      BrazilianUtilsBridge::Municipalities.get_municipalities(key)
    end

  dump.push("#{key}\t#{found.length}")
  found.each { |m| dump.push("#{m.code}|#{m.name}|#{m.state_code}") }
end

expected_dump = File.read(File.join(conformance, 'municipalities.expected.txt'), encoding: 'UTF-8')
                    .chomp("\n").split("\n", -1)
dump_failed = 0

[dump.length, expected_dump.length].max.times do |index|
  next if dump[index] == expected_dump[index]

  dump_failed += 1
  warn "FAIL municipalities line #{index + 1}: expected #{expected_dump[index].inspect} got #{dump[index].inspect}" if dump_failed <= 5
end

puts "ruby: #{expected_dump.length - dump_failed}/#{expected_dump.length} municipality lines matched"
exit(failed.zero? && dump_failed.zero? ? 0 : 1)
`,

	"out/java/Conformance.java": `// Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/** Replays the vectors recorded from the JavaScript package against the generated Java. */
public final class Conformance {
    private Conformance() {}

    private static String unescape(String value) {
        return value.replace("\\\\t", "\\t").replace("\\\\n", "\\n").replace("\\\\\\\\", "\\\\");
    }

    public static void main(String[] args) throws Exception {
        List<String> lines = Files.readAllLines(Path.of(args[0]));
        int passed = 0;
        int failed = 0;
        int skipped = 0;

        for (String line : lines.subList(1, lines.size())) {
            if (line.isEmpty()) {
                continue;
            }

            String[] parts = line.split("\\t", -1);
            String fn = parts[0];
            String input = unescape(parts[1]);
            String kind = parts[2];
            String version = parts[3];
            String expected = unescape(parts[6]);

            // A number input to a validator cannot be written in Java: the parameter is a String.
            if (kind.equals("number") && fn.equals("isValidCnpj")) {
                skipped++;

                continue;
            }

            String actual;

            if (fn.equals("isValidCnpj")) {
                IsValidCnpjOptions options = new IsValidCnpjOptions();

                if (!version.isEmpty()) {
                    options.version = Long.parseLong(version);
                }

                actual = String.valueOf(Cnpj.isValidCnpj(input, options));
            } else {
                FormatCnpjOptions options = new FormatCnpjOptions();

                if (!version.isEmpty()) {
                    options.version = Long.parseLong(version);
                }

                options.pad = parts[4].equals("1") ? Boolean.TRUE : null;
                options.obfuscate = parts[5].equals("1") ? Boolean.TRUE : null;
                actual = Cnpj.formatCnpj(input, options);
            }

            if (actual.equals(expected)) {
                passed++;
            } else {
                failed++;

                if (failed <= 5) {
                    System.err.printf("FAIL %s(%s) expected %s got %s%n", fn, input, expected, actual);
                }
            }
        }

        System.out.printf("java: %d/%d conformance checks passed (%d not expressible)%n", passed, passed + failed, skipped);

        Path conformance = Path.of(args[0]).getParent();
        java.util.List<String> dump = new java.util.ArrayList<>();

        for (String key : Files.readString(conformance.resolve("municipalities.keys.txt")).stripTrailing().split("\\n", -1)) {
            java.util.List<Municipality> found =
                key.equals("*") ? Municipalities.getMunicipalities(null) : Municipalities.getMunicipalities(key);

            dump.add(key + "\\t" + found.size());

            for (Municipality municipality : found) {
                dump.add(municipality.code + "|" + municipality.name + "|" + municipality.stateCode);
            }
        }

        String[] expectedDump =
            Files.readString(conformance.resolve("municipalities.expected.txt")).stripTrailing().split("\\n", -1);
        int dumpFailed = 0;

        for (int index = 0; index < Math.max(dump.size(), expectedDump.length); index++) {
            String got = index < dump.size() ? dump.get(index) : "";
            String want = index < expectedDump.length ? expectedDump[index] : "";

            if (got.equals(want)) {
                continue;
            }

            dumpFailed++;

            if (dumpFailed <= 5) {
                System.err.printf("FAIL municipalities line %d: expected %s got %s%n", index + 1, want, got);
            }
        }

        System.out.printf("java: %d/%d municipality lines matched%n", expectedDump.length - dumpFailed, expectedDump.length);

        if (failed > 0 || dumpFailed > 0) {
            System.exit(1);
        }
    }
}
`,

	"out/csharp/Conformance.cs": `// Code generated by spec/bridge/conformance/drivers.ts. DO NOT EDIT.

using System;
using System.IO;
using BrazilianUtils.Bridge;

/// <summary>Replays the vectors recorded from the JavaScript package against the generated C#.</summary>
public static class Conformance
{
    private static string Unescape(string value)
    {
        return value.Replace("\\\\t", "\\t").Replace("\\\\n", "\\n").Replace("\\\\\\\\", "\\\\");
    }

    public static int Main(string[] args)
    {
        var lines = File.ReadAllLines(args[0]);
        var passed = 0;
        var failed = 0;
        var skipped = 0;

        for (var row = 1; row < lines.Length; row++)
        {
            if (lines[row].Length == 0)
            {
                continue;
            }

            var parts = lines[row].Split('\\t');
            var fn = parts[0];
            var input = Unescape(parts[1]);
            var kind = parts[2];
            var version = parts[3];
            var expected = Unescape(parts[6]);

            // A number input to a validator cannot be written in C#: the parameter is a string.
            if (kind == "number" && fn == "isValidCnpj")
            {
                skipped++;

                continue;
            }

            string actual;

            if (fn == "isValidCnpj")
            {
                var options = new IsValidCnpjOptions();

                if (version.Length > 0)
                {
                    options.Version = long.Parse(version);
                }

                actual = Cnpj.IsValidCnpj(input, options) ? "true" : "false";
            }
            else
            {
                var options = new FormatCnpjOptions();

                if (version.Length > 0)
                {
                    options.Version = long.Parse(version);
                }

                options.Pad = parts[4] == "1" ? true : (bool?)null;
                options.Obfuscate = parts[5] == "1" ? true : (bool?)null;
                actual = Cnpj.FormatCnpj(input, options);
            }

            if (actual == expected)
            {
                passed++;
            }
            else
            {
                failed++;

                if (failed <= 5)
                {
                    Console.Error.WriteLine($"FAIL {fn}({input}) expected {expected} got {actual}");
                }
            }
        }

        Console.WriteLine($"csharp: {passed}/{passed + failed} conformance checks passed ({skipped} not expressible)");

        var conformance = Path.GetDirectoryName(Path.GetFullPath(args[0]));
        var dump = new System.Collections.Generic.List<string>();

        foreach (var key in File.ReadAllText(Path.Combine(conformance, "municipalities.keys.txt")).TrimEnd('\\n').Split('\\n'))
        {
            var found = key == "*" ? Municipalities.GetMunicipalities() : Municipalities.GetMunicipalities(key);

            dump.Add(key + "\\t" + found.Count);

            foreach (var municipality in found)
            {
                dump.Add(municipality.Code + "|" + municipality.Name + "|" + municipality.StateCode);
            }
        }

        var expectedDump = File.ReadAllText(Path.Combine(conformance, "municipalities.expected.txt")).TrimEnd('\\n').Split('\\n');
        var dumpFailed = 0;

        for (var index = 0; index < Math.Max(dump.Count, expectedDump.Length); index++)
        {
            var got = index < dump.Count ? dump[index] : "";
            var want = index < expectedDump.Length ? expectedDump[index] : "";

            if (got == want)
            {
                continue;
            }

            dumpFailed++;

            if (dumpFailed <= 5)
            {
                Console.Error.WriteLine($"FAIL municipalities line {index + 1}: expected {want} got {got}");
            }
        }

        Console.WriteLine($"csharp: {expectedDump.Length - dumpFailed}/{expectedDump.Length} municipality lines matched");

        return failed == 0 && dumpFailed == 0 ? 0 : 1;
    }
}
`,
};

for (const [path, contents] of Object.entries(files)) {
	const full = resolve(bridge, path);

	mkdirSync(dirname(full), { recursive: true });
	writeFileSync(full, contents);
}

console.log(`wrote ${tablePath} (${lines.length - 1} rows) and ${Object.keys(files).length} drivers`);
