#!/usr/bin/env node

import { DATA as STATES } from "../src/_internals/constants/states.ts";
import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";
import { runAsEntryPoint, writeGeneratedFiles } from "./lookup-table.ts";
import { readZipFile } from "./read-xlsx-sheet.ts";

const PGCN_URL = "https://www.anatel.gov.br/dadosabertos/paineis_de_dados/areastarifarias/pgcn.zip";

const PGCN_CSV = "Codigos_Nacionais.csv";

const PGCN_HEADER = [
	"CO_MUNICIPIO",
	"SG_UF",
	"NO_UF",
	"NO_MUNICIPIO",
	"CN",
	"DT_INICIO_VIGENCIA",
	"DT_FIM_VIGENCIA",
	"DE_ALTERACAO_REGULAMENTAR",
	"VIGENTE",
];

const MUNICIPALITY_CODE_REGEX = /^\d{7}$/;

const AREA_CODE_REGEX = /^[1-9][1-9]$/;

const STATE_CODES = new Set<string>(STATES.map((state) => state.code));

/**
 * Splits one `;` separated row of the Anatel CSV, whose fields may be quoted (`"Alta Floresta
 * D'Oeste"`), a quote inside a quoted field being written twice.
 * @param {string} row - The row.
 * @returns {string[]} The fields of the row.
 */
const splitRow = (row: string): string[] => {
	const fields: string[] = [];
	let field = "";
	let quoted = false;

	for (let index = 0; index < row.length; index++) {
		const character = row[index];

		if (quoted) {
			if (character === '"' && row[index + 1] === '"') {
				field += '"';
				index++;
			} else if (character === '"') {
				quoted = false;
			} else {
				field += character;
			}
		} else if (character === '"') {
			quoted = true;
		} else if (character === ";") {
			fields.push(field);
			field = "";
		} else {
			field += character;
		}
	}

	fields.push(field);

	return fields;
};

/**
 * Reads the Código Nacional (DDD) in force for every municipality of the Anatel
 * `Codigos_Nacionais.csv`. A municipality's earlier codes stay in the file with `VIGENTE` set to
 * `Não`, so only the rows in force are kept, and a municipality with more than one of them is an
 * error.
 * @param {string} csv - The decoded CSV.
 * @returns {Record<string, Record<string, number>>} The DDD of every municipality, by state and
 * by 7 digit IBGE municipality code.
 */
export const parseAreaCodes = (csv: string): Record<string, Record<string, number>> => {
	const [header, ...rows] = csv.replace(/^﻿/, "").split(/\r?\n/);

	if (header === undefined || splitRow(header).join(";") !== PGCN_HEADER.join(";")) {
		throw new Error(`${PGCN_CSV} header is not "${PGCN_HEADER.join(";")}"`);
	}

	const areaCodes: Record<string, Record<string, number>> = {};

	for (const row of rows) {
		if (row.trim() === "") continue;

		const fields = splitRow(row);
		const code = fields[0] ?? "";
		const stateCode = fields[1] ?? "";
		const areaCode = fields[4] ?? "";
		const inForce = fields[8] ?? "";

		if (inForce !== "Sim") continue;

		if (
			!MUNICIPALITY_CODE_REGEX.test(code) ||
			!STATE_CODES.has(stateCode) ||
			!AREA_CODE_REGEX.test(areaCode)
		) {
			throw new Error(`${PGCN_CSV} has an unexpected row: ${row}`);
		}

		const state = areaCodes[stateCode] ?? {};

		areaCodes[stateCode] = state;

		if (Object.hasOwn(state, code)) {
			throw new Error(`${PGCN_CSV} has two codes in force for the municipality ${code}`);
		}

		state[code] = Number(areaCode);
	}

	return areaCodes;
};

/**
 * Renders the module the DDD of every municipality is shipped as: for each state, one string
 * holding the two digits of each municipality's DDD, in ascending order of the municipality code.
 * @param {Record<string, Record<string, number>>} areaCodes - What `parseAreaCodes` returns.
 * @returns {Record<string, string>} The content of the generated file, by its path.
 */
export const renderAreaCodes = (
	areaCodes: Record<string, Record<string, number>>,
): Record<string, string> => {
	const entries = [...STATE_CODES].sort().map((stateCode) => {
		const state = areaCodes[stateCode];

		if (state === undefined) throw new Error(`${PGCN_CSV} has no municipality of ${stateCode}`);

		const digits = Object.keys(state)
			.sort()
			.map((code) => String(state[code]))
			.join("");

		return `\t${stateCode}: "${digits}",`;
	});

	return {
		"./src/_internals/constants/municipality-area-codes.ts": `import { type StateCode } from "./states";

/**
 * The DDD (Código Nacional) in force for every Brazilian municipality. For each state, the two
 * digits of each municipality's DDD follow one another in ascending order of the 7 digit IBGE
 * municipality code, so the municipality with the n-th smallest code of the state has its DDD at
 * characters \`2n\` and \`2n + 1\`. The municipalities are the same 5,571 as \`DATA\` in
 * \`municipalities.ts\`, which a test checks.
 *
 * Generated by \`node ./scripts/area-codes.ts\` from the \`Codigos_Nacionais.csv\` Anatel
 * publishes, keeping only the rows in force (\`VIGENTE\` is \`Sim\`). Do not edit by hand.
 *
 * @see Official: https://informacoes.anatel.gov.br/paineis/areas-tarifarias/codigos-nacionais
 * Anatel, Painel de Dados de Áreas Tarifárias, "Códigos Nacionais".
 * @see Official: ${PGCN_URL}
 * \`Codigos_Nacionais.csv\`, the Código Nacional of every municipality.
 */
export const MUNICIPALITY_AREA_CODES: Record<StateCode, string> = {
${entries.join("\n")}
};
`,
	};
};

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(PGCN_URL);

	if (!response.ok) throw new Error(`Anatel PGCN request failed with status ${response.status}`);

	const archive = Buffer.from(await response.arrayBuffer());

	const areaCodes = parseAreaCodes(readZipFile(archive, PGCN_CSV));

	await writeGeneratedFiles(renderAreaCodes(areaCodes));
};

await runAsEntryPoint(import.meta.filename, main);
