#!/usr/bin/env node

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";
import {
	runAsEntryPoint,
	serializeCodes,
	serializeFixedWidth,
	serializeLines,
	writeGeneratedFiles,
} from "./lookup-table.ts";

const ISPB_LENGTH = 8;

const BACEN_CSV_URL =
	"https://www.bcb.gov.br/content/estabilidadefinanceira/str1/ParticipantesSTR.csv";

const BRASIL_API_URL = "https://brasilapi.com.br/api/banks/v1";

type BankRow = {
	code: string;
	ispb: string;
	name: string;
};

type BrasilApiBank = {
	ispb?: string;
	code?: number;
	name?: string;
	fullName?: string;
};

const isBrasilApiBank = (value: unknown): value is BrasilApiBank =>
	typeof value === "object" &&
	value !== null &&
	(!("ispb" in value) || typeof value.ispb === "string") &&
	(!("code" in value) || typeof value.code === "number") &&
	(!("name" in value) || typeof value.name === "string") &&
	(!("fullName" in value) || typeof value.fullName === "string");

const parseCsvLine = (line: string): string[] => {
	const fields: string[] = [];
	let current = "";
	let inQuotes = false;

	for (let i = 0; i < line.length; i++) {
		const character = line[i];

		if (inQuotes) {
			if (character === '"' && line[i + 1] === '"') {
				current += '"';
				i++;
			} else if (character === '"') {
				inQuotes = false;
			} else {
				current += character;
			}
		} else if (character === '"') {
			inQuotes = true;
		} else if (character === ",") {
			fields.push(current);
			current = "";
		} else {
			current += character;
		}
	}

	fields.push(current);

	return fields;
};

const fetchFromBacen = async (): Promise<BankRow[]> => {
	const response = await fetchWithRetry(BACEN_CSV_URL);

	if (!response.ok) {
		throw new Error(`Bacen STR participants request failed with status ${response.status}`);
	}

	const body = await response.text();
	const text = body.replace(/^\uFEFF/, "");
	const [, ...rows] = text.split(/\r\n|\n/).filter((line) => line.length > 0);

	const banks: BankRow[] = [];

	for (const row of rows) {
		const fields = parseCsvLine(row);
		const [ispb] = fields;
		const code = fields[2];
		const name = fields[5];

		if (
			ispb === undefined ||
			ispb === "" ||
			code === undefined ||
			code === "" ||
			name === undefined ||
			name === "" ||
			!/^\d{1,3}$/.test(code) ||
			Number(code) === 0
		) {
			continue;
		}

		banks.push({ code: code.padStart(3, "0"), ispb, name: name.trim() });
	}

	return banks;
};

const fetchFromBrasilApi = async (): Promise<BankRow[]> => {
	const response = await fetchWithRetry(BRASIL_API_URL);

	if (!response.ok) {
		throw new Error(`BrasilAPI banks request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!Array.isArray(json)) {
		throw new TypeError("BrasilAPI banks payload is not an array");
	}

	const banks: BankRow[] = [];

	for (const entry of json) {
		if (!isBrasilApiBank(entry) || typeof entry.code !== "number") continue;
		if (!Number.isInteger(entry.code) || entry.code <= 0 || entry.code > 999) continue;

		const ispb = entry.ispb;

		if (ispb === undefined || ispb === "") continue;

		const name = (entry.fullName ?? entry.name ?? "").trim();

		if (name === "") continue;

		banks.push({ code: String(entry.code).padStart(3, "0"), ispb, name });
	}

	return banks;
};

/**
 * Renders the modules the banks are shipped as: the compensation codes, which a validator bundles
 * on their own, and the ISPBs and names, which only a getter bundles.
 * @param {BankRow[]} banks - The banks, sorted by code.
 * @param {string} source - The URL the banks were read from.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderBanks = (banks: BankRow[], source: string): Record<string, string> => {
	if (banks.some((bank) => bank.ispb.length !== ISPB_LENGTH || bank.name.includes("\n"))) {
		throw new Error(`An ISPB is not ${ISPB_LENGTH} characters or a name has a line break`);
	}

	return {
		"./src/_internals/constants/bank-codes.ts": `/**
 * The compensation code (COMPE) of every Brazilian STR participant that has one, in ascending
 * order, packed as base 36 differences by \`packCodes\` (scripts/lookup-table.ts), which
 * \`findCodeIndex\` reads. The ISPB and the name of each bank are at the same index of
 * \`BANK_ISPBS\` and \`BANK_NAMES\` (\`banks.ts\`), a module of its own so that checking a bank
 * code does not bundle them.
 *
 * Generated by \`node ./scripts/banks.ts\`. Do not edit by hand.
 *
 * @see Official: ${BACEN_CSV_URL}
 */
export const COMPE_CODES =
	${serializeCodes(banks.map((bank) => bank.code))};
`,
		"./src/_internals/constants/banks.ts": `/**
 * Brazilian STR (Sistema de Transferência de Reservas) participants that have a compensation
 * code (commonly known as COMPE), published by Banco Central do Brasil. Generated by
 * \`scripts/banks.ts\`.
 * @see Official: ${BACEN_CSV_URL}
 */
export type Bank = {
	/** Compensation code (COMPE), 3 digits, zero-padded. */
	code: string;
	/** Identificador do Sistema de Pagamentos Brasileiro (ISPB), 8 digits, zero-padded. */
	ispb: string;
	/** Institution name, as published by Banco Central do Brasil. */
	name: string;
};

/**
 * The ISPB of each bank, 8 characters each, one after the other, in the order of \`COMPE_CODES\`
 * (\`bank-codes.ts\`). Each sits on a line of its own, ended by a line continuation that adds
 * nothing to the value, so a refresh diffs to the banks that changed.
 *
 * Generated by \`node ./scripts/banks.ts\` from ${source}. Do not edit by hand.
 */
export const BANK_ISPBS = ${serializeFixedWidth(banks.map((bank) => bank.ispb))};

/**
 * The name of each bank, one per line, in the order of \`COMPE_CODES\` (\`bank-codes.ts\`).
 *
 * Generated by \`node ./scripts/banks.ts\` from ${source}. Do not edit by hand.
 */
export const BANK_NAMES = ${serializeLines(banks.map((bank) => bank.name))};
`,
	};
};

const main = async (): Promise<void> => {
	let banks: BankRow[];
	let source: string;

	try {
		banks = await fetchFromBacen();
		source = BACEN_CSV_URL;
	} catch (error) {
		console.error(
			`Bacen STR participants request failed, falling back to BrasilAPI: ${error instanceof Error ? error.message : String(error)}`,
		);
		banks = await fetchFromBrasilApi();
		source = BRASIL_API_URL;
	}

	const uniqueBanks = new Map<string, BankRow>();

	for (const bank of banks) {
		uniqueBanks.set(bank.code, bank);
	}

	const sorted = [...uniqueBanks.values()].sort((bankA, bankB) =>
		bankA.code > bankB.code ? 1 : -1,
	);

	if (sorted.length === 0) {
		throw new Error("Refusing to write an empty bank dataset");
	}

	console.log(`Generated ${sorted.length} banks from ${source}`);

	await writeGeneratedFiles(renderBanks(sorted, source));
};

await runAsEntryPoint(import.meta.filename, main);
