#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
	runAsEntryPoint,
	serializeCodes,
	splitRecord,
	writeGeneratedFiles,
} from "./lookup-table.ts";
import { sortRecord } from "./sort-record.ts";

/**
 * The official occupation table, `CBO2002 - Ocupacao.csv` of the "Estrutura CBO (CSV)" archive the
 * Ministério do Trabalho e Emprego serves at https://cbo.mte.gov.br/cbosite/pages/downloads.jsf
 * (files dated 10/07/2026, 2,725 occupations), kept byte for byte in the repository. That archive
 * is only served after a reCAPTCHA, so no script can download it; the CSVs gov.br serves without
 * one are an older release (updated 06/06/2025, 2,694 occupations). A new release is downloaded by
 * hand, reviewed, and its digest put in `CBO_CSV_SHA256`.
 */
const CBO_CSV_PATH = resolve(import.meta.dirname, "data", "cbo2002-ocupacao.csv");

const CBO_CSV_SHA256 = "ad775f2f0b662cf1b702a9c610ed168a8dbf3a407fc67c81cc3b012e447f9893";

/** The official CSV is published in ISO-8859-1, not UTF-8. */
const CBO_CSV_DECODER = new TextDecoder("iso-8859-1");

const CBO_CSV_HEADER = "CODIGO;TITULO";

const CBO_CODE_REGEX = /^\d{6}$/;

/**
 * Reads the `CODIGO;TITULO` rows of the official CBO 2002 occupation CSV.
 * @param {string} csv - The decoded CSV.
 * @returns {Record<string, string>} One entry per 6 digit occupation code.
 */
const parseCsv = (csv: string): Record<string, string> => {
	const [header, ...rows] = csv.split(/\r?\n/);

	if (header?.trim() !== CBO_CSV_HEADER) {
		throw new Error(`CBO CSV header is not "${CBO_CSV_HEADER}"`);
	}

	const data: Record<string, string> = {};

	for (const row of rows) {
		const separator = row.indexOf(";");

		if (separator === -1) continue;

		const code = row.slice(0, separator).trim();
		const title = row.slice(separator + 1).trim();

		if (!CBO_CODE_REGEX.test(code) || title === "") continue;

		data[code] = title;
	}

	return data;
};

/**
 * Renders the two modules the CBO table is shipped as.
 * @param {Record<string, string>} titles - The occupation titles, keyed by the 6 digit code.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderCbo = (titles: Record<string, string>): Record<string, string> => {
	const { codes, descriptions } = splitRecord(titles);

	return {
		"./src/_internals/constants/cbo.ts": `/**
 * CBO 2002 (Classificação Brasileira de Ocupações) occupation codes: the raw 6 digits of every
 * code, in ascending order, packed as base 36 differences by \`packCodes\`
 * (scripts/lookup-table.ts), which \`findCodeIndex\` reads. The title of a code is at the same
 * index of \`CBO_DESCRIPTIONS\`, a module of its own (\`cbo-descriptions.ts\`) so that checking a
 * code does not bundle the titles.
 *
 * Built from \`CBO2002 - Ocupacao.csv\` of the "Estrutura CBO (CSV)" archive the Ministério do
 * Trabalho e Emprego serves on the CBO site (files dated 10/07/2026), a plain \`CODIGO;TITULO\`
 * CSV in ISO-8859-1 whose codes are already the 6 digit form \`Cbo.code\` accepts, so no
 * normalization is applied to them. The site serves it only after a reCAPTCHA, so the file is
 * kept in the repository (\`scripts/data/cbo2002-ocupacao.csv\`) and checked against a reviewed
 * SHA-256. The \`cbo2002-ocupacao.csv\` gov.br serves is an older release (updated 06/06/2025): it
 * lacks 37 occupations of this one and still lists 6 it no longer does.
 *
 * Generated by \`node ./scripts/cbo.ts\`. Do not edit by hand.
 *
 * @see Official: https://cbo.mte.gov.br/cbosite/pages/downloads.jsf
 * "Estrutura CBO (CSV)", the CBO 2002 tables as published by the Ministério do Trabalho e Emprego.
 * @see Official: https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/cbo2002-ocupacao.csv
 * The older release of the same table on gov.br, used up to 2.4.0.
 */
export const CBO_CODES = ${serializeCodes(codes)};

/**
 * Shape a CBO code has to be written in: the 6 digits, optionally split into the printed
 * groups of 4 and 2 by a single whitespace or mask character.
 */
export const CBO_FORMAT_REGEX = /^\\d{4}[\\s.\\-/]?\\d{2}$/;
`,
		"./src/_internals/constants/cbo-descriptions.ts": `/**
 * CBO 2002 occupation titles, the official sentence case spelling, each at the index of its code
 * in \`CBO_CODES\` (\`cbo.ts\`).
 *
 * Generated by \`node ./scripts/cbo.ts\`. Do not edit by hand.
 *
 * @see Official: https://cbo.mte.gov.br/cbosite/pages/downloads.jsf
 * "Estrutura CBO (CSV)", the CBO 2002 tables as published by the Ministério do Trabalho e Emprego.
 */
export const CBO_DESCRIPTIONS: readonly string[] = ${JSON.stringify(descriptions)};
`,
	};
};

const main = async (): Promise<void> => {
	const csv = await readFile(CBO_CSV_PATH);
	const digest = createHash("sha256").update(csv).digest("hex");

	if (digest !== CBO_CSV_SHA256) {
		throw new Error(
			`${CBO_CSV_PATH} has SHA-256 ${digest}, not the reviewed ${CBO_CSV_SHA256}: review the new file and update CBO_CSV_SHA256`,
		);
	}

	const data = parseCsv(CBO_CSV_DECODER.decode(csv));

	if (Object.keys(data).length === 0) throw new Error("CBO CSV holds no occupation");

	await writeGeneratedFiles(renderCbo(sortRecord(data)));
};

await runAsEntryPoint(import.meta.filename, main);
