#!/usr/bin/env node

import { fetchSortedRecord } from "./fetch-sorted-record.ts";
import {
	runAsEntryPoint,
	serializeCodes,
	splitRecord,
	writeGeneratedFiles,
} from "./lookup-table.ts";

/** The official CSV is published in ISO-8859-1, not UTF-8. */
const CBO_CSV_DECODER = new TextDecoder("iso-8859-1");

const CBO_CSV_HEADER = "CODIGO;TITULO";

const CBO_CODE_REGEX = /^\d{6}$/;

/**
 * Reads the `CODIGO;TITULO` rows of the official CBO 2002 occupation CSV.
 * @param {string} csv - The decoded CSV.
 * @returns {Record<string, string>} One entry per 6 digit occupation code.
 */
const parseCsv = (csv: string): Record<string, string> => {
	const [header, ...rows] = csv.split(/\r?\n/);

	if (header?.trim() !== CBO_CSV_HEADER) {
		throw new Error(`CBO CSV header is not "${CBO_CSV_HEADER}"`);
	}

	const data: Record<string, string> = {};

	for (const row of rows) {
		const separator = row.indexOf(";");

		if (separator === -1) continue;

		const code = row.slice(0, separator).trim();
		const title = row.slice(separator + 1).trim();

		if (!CBO_CODE_REGEX.test(code) || title === "") continue;

		data[code] = title;
	}

	return data;
};

/**
 * Renders the two modules the CBO table is shipped as.
 * @param {Record<string, string>} titles - The occupation titles, keyed by the 6 digit code.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderCbo = (titles: Record<string, string>): Record<string, string> => {
	const { codes, descriptions } = splitRecord(titles);

	return {
		"./src/_internals/constants/cbo.ts": `/**
 * CBO 2002 (Classificação Brasileira de Ocupações) occupation codes: the raw 6 digits of every
 * code, back to back in ascending order, which \`findCodeIndex\` reads. The title of a code is at
 * the same index of \`CBO_DESCRIPTIONS\`, a module of its own (\`cbo-descriptions.ts\`) so that
 * checking a code does not bundle the titles.
 *
 * Built from the official \`cbo2002-ocupacao.csv\` the Ministério do Trabalho e Emprego publishes
 * on gov.br, a plain \`CODIGO;TITULO\` CSV in ISO-8859-1 whose codes are already the 6 digit
 * form \`Cbo.code\` accepts, so no normalization is applied to them.
 *
 * Generated by \`node ./scripts/cbo.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/cbo2002-ocupacao.csv
 * The CBO 2002 occupation table, as published by the Ministério do Trabalho e Emprego.
 * @see Based on: https://raw.githubusercontent.com/lucaashoff/lista-cbo-json/main/cbos.json
 * Community mirror of the same table, the fallback this script was generated from before the
 * official CSV was used.
 */
export const CBO_CODES = ${serializeCodes(codes)};

/**
 * Shape a CBO code has to be written in: the 6 digits, optionally split into the printed
 * groups of 4 and 2 by a single whitespace or mask character.
 */
export const CBO_FORMAT_REGEX = /^\\d{4}[\\s.\\-/]?\\d{2}$/;
`,
		"./src/_internals/constants/cbo-descriptions.ts": `/**
 * CBO 2002 occupation titles, the official sentence case spelling, each at the index of its code
 * in \`CBO_CODES\` (\`cbo.ts\`).
 *
 * Generated by \`node ./scripts/cbo.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/cbo2002-ocupacao.csv
 * The CBO 2002 occupation table, as published by the Ministério do Trabalho e Emprego.
 */
export const CBO_DESCRIPTIONS: readonly string[] = ${JSON.stringify(descriptions)};
`,
	};
};

const main = async (): Promise<void> => {
	const sorted = await fetchSortedRecord(
		"https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/cbo2002-ocupacao.csv",
		"CBO CSV",
		async (response) => {
			const data = parseCsv(CBO_CSV_DECODER.decode(await response.arrayBuffer()));

			if (Object.keys(data).length === 0) {
				throw new Error("CBO CSV holds no occupation");
			}

			return data;
		},
	);

	await writeGeneratedFiles(renderCbo(sorted));
};

await runAsEntryPoint(import.meta.filename, main);
