#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { decodeEntities } from "./decode-entities.ts";
import { fetchSortedRecord } from "./fetch-sorted-record.ts";

const scriptsDir = import.meta.dirname;

/**
 * CONFAZ prints the text in force with the `A5-1TextoAcordo` class and keeps every superseded
 * wording alongside it under `A8-3RedacaoAnt`, with the amendment notes under `Remisso`,
 * `A8-1Remissao` and `A8-2RemissaoAnt`. Reading only the first class is what keeps the previous
 * redaction of a re-worded code (7.667, re-worded by Ajuste SINIEF 39/25) out of the table.
 */
const CURRENT_TEXT_PARAGRAPH_REGEX = /<p class="A5-1TextoAcordo">([^<]*)<\/p>/g;

/**
 * Smallest number of operable codes a complete annex yields. The consolidated text carries 619
 * today and CONFAZ only adds or replaces codes, so a result far below it means the markup changed
 * and the paragraph pattern above stopped matching, not that codes were revoked.
 */
const MINIMUM_OPERABLE_CODES = 600;

/** A code line, e.g. `1.101 - Compra para industrialização ou produção rural.`. */
const CODE_LINE_REGEX = /^(\d)\.(\d{3})\s*[-–]\s*(.+)$/;

/**
 * The sentence that opens the body of every operable code. Group and subgroup headings
 * (1.000, 1.100, 1.150, ...) are printed in upper case and followed by "Classificam-se neste
 * grupo" instead, so they carry no such body and are left out of the table.
 */
const OPERABLE_BODY = "Classificam-se neste código";

const TRAILING_PUNCTUATION_REGEX = /[.\s]+$/;

/**
 * Reads the consolidated Anexo II out of the CONFAZ page.
 *
 * A handful of rows glue the body into the same paragraph as the code line, e.g.
 * `1.255 - Compra de energia elétrica ... Classificam-se neste código as compras ...`, so the
 * body sentence is looked for inside the code line first and only then in the paragraph that
 * follows it.
 * @param {string} html - The annex page.
 * @returns {Record<string, string>} One entry per operable code, keyed by the 4 digits.
 */
const parseAnnex = (html: string): Record<string, string> => {
	const paragraphs = [...html.matchAll(CURRENT_TEXT_PARAGRAPH_REGEX)].map((match) =>
		decodeEntities(match[1] ?? "")
			.replaceAll(/\s+/g, " ")
			.trim(),
	);

	const data: Record<string, string> = {};

	for (const [index, paragraph] of paragraphs.entries()) {
		const match = CODE_LINE_REGEX.exec(paragraph);

		if (!match) continue;

		const [, series, code, line] = match;

		if (series === undefined || code === undefined || line === undefined) continue;

		const bodyIndex = line.indexOf(OPERABLE_BODY);
		const isOperable = bodyIndex !== -1 || (paragraphs[index + 1] ?? "").startsWith(OPERABLE_BODY);

		if (!isOperable) continue;

		const description = (bodyIndex === -1 ? line : line.slice(0, bodyIndex))
			.trim()
			.replace(TRAILING_PUNCTUATION_REGEX, "");

		data[`${series}${code}`] = description;
	}

	return data;
};

const main = async (): Promise<void> => {
	const sorted = await fetchSortedRecord(
		"https://www.confaz.fazenda.gov.br/legislacao/ajustes/sinief/cfop_cvsn_1-6.24",
		"CFOP annex",
		async (response) => {
			const data = parseAnnex(await response.text());

			const count = Object.keys(data).length;

			if (count < MINIMUM_OPERABLE_CODES) {
				throw new Error(
					`CFOP annex page yielded ${count} operable codes, below the ${MINIMUM_OPERABLE_CODES} a complete annex holds; the markup probably changed`,
				);
			}

			return data;
		},
	);

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cfop.ts"),
		`/**
 * CFOP (Código Fiscal de Operações e Prestações) table, indexed by the 4 digit code.
 *
 * Built from the consolidated Anexo II of Convênio SINIEF s/nº of 15 December 1970, the text in
 * force (given its current wording by Ajuste SINIEF 03/24 and last amended by Ajuste SINIEF
 * 39/25), not from the frozen 2001 text of Ajuste SINIEF 07/01.
 *
 * Group and subgroup headers (codes ending in "00" or "50", e.g. "1000", "1100", "1150")
 * are section titles from the official nomenclature rather than operable codes, so they
 * are excluded: the annex prints them in upper case with no "Classificam-se neste código"
 * body, unlike the operable codes they head (1151, 1152, ...).
 *
 * Generated by \`node ./scripts/cfop.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/ajustes/sinief/cfop_cvsn_1-6.24
 * Anexo II of Convênio SINIEF s/nº 1970, the CFOP table in force.
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/ajustes/sinief/cvsn_70
 * Convênio SINIEF s/nº 1970, the consolidated text the annex belongs to.
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/ajustes/2025/AJ039_25
 * Ajuste SINIEF 39/25, the last amendment the annex carries (CFOP 7.667, from 01.02.26).
 * @see Official: https://www.confaz.fazenda.gov.br/legislacao/ajustes/2001/AJ_007_01
 * Ajuste SINIEF 07/01, the historical text that gave the CFOP its 4 digit form.
 */
export const CFOP_TABLE: Record<string, string> = ${JSON.stringify(sorted)};

/**
 * Shape a CFOP code has to be written in: the 4 digits, optionally split after the series
 * digit by a single whitespace or mask character, the way the annex prints them ("1.101").
 */
export const CFOP_FORMAT_REGEX = /^\\d[\\s.\\-/]?\\d{3}$/;
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
