#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { DATA as STATES } from "../src/_internals/constants/states.ts";
import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = import.meta.dirname;

const STATE_CODES = STATES.map((state) => state.code);

type City = {
	id: number;
	nome: string;
	microrregiao: {
		id: number;
		nome: string;
		mesorregiao: {
			id: number;
			nome: string;
			UF: {
				id: number;
				sigla: string;
				nome: string;
				regiao: {
					id: number;
					sigla: string;
					nome: string;
				};
			};
		};
	} | null;
	"regiao-imediata": {
		id: number;
		nome: string;
		"regiao-intermediaria": {
			id: number;
			nome: string;
			UF: {
				id: number;
				sigla: string;
				nome: string;
			};
		};
	};
};

const isCity = (value: unknown): value is City =>
	typeof value === "object" &&
	value !== null &&
	"id" in value &&
	typeof value.id === "number" &&
	"nome" in value &&
	typeof value.nome === "string" &&
	"microrregiao" in value &&
	"regiao-imediata" in value;

/**
 * Alternative spellings the Correios CEP range mirror uses for a handful of municipalities,
 * mostly hyphen and accent variants and a couple of older names, keyed by the 7-digit IBGE code. Curated by hand from the mismatches found joining
 * https://gist.githubusercontent.com/hugosenari/ec1a7d88f5bdd01844424dbc9aff9590/raw/9aeb90ef777131ffaf1a6f5381d1f163c9c79b09/ceps.csv
 * against the IBGE municipalities below (see `scripts/municipality-cep-ranges.ts`); `main`
 * below fails the build if a code here stops matching a real municipality, so a future IBGE
 * refresh can never leave a stale entry silently in place.
 */
const OTHER_NAMES: Record<string, readonly string[]> = {
	"1400605": ["São Luiz"],
	"1502954": ["Eldorado dos Carajás"],
	"1708254": ["Fortaleza do Tabocão"],
	"2108504": ["Pindaré Mirim"],
	"2400208": ["Açu"],
	"2401206": ["Ares"],
	"2401305": ["Augusto Severo"],
	"2405306": ["Boa Saúde"],
	"2408409": ["Olho-D'Água do Borges"],
	"2606903": ["Iguaraci"],
	"2608503": ["Lagoa do Itaenga"],
	"2800100": ["Amparo de São Francisco"],
	"2922250": ["Muquém de São Francisco"],
	"2928505": ["Santa Teresinha"],
	"3105509": ["Barão de Monte Alto"],
	"3122900": ["Dona Eusébia"],
	"3145455": ["Olhos D'Água"],
	"3165206": ["São Thomé das Letras"],
	"3165560": ["Sem Peixe"],
	"3506607": ["Biritiba-Mirim"],
	"3516101": ["Florínia"],
	"3550001": ["São Luis do Paraitinga"],
	"4206108": ["Grão Pará"],
	"5107800": ["Santo Antônio do Leverger"],
};

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(
		"https://servicodados.ibge.gov.br/api/v1/localidades/municipios",
	);

	if (!response.ok) {
		throw new Error(`IBGE municipalities request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!Array.isArray(json) || !json.every((entry) => isCity(entry))) {
		throw new Error("IBGE municipalities payload is not an array of city entries");
	}

	const byState: Record<string, [string, string][]> = {};

	for (const city of json) {
		const stateInitials =
			city.microrregiao?.mesorregiao?.UF?.sigla ??
			city["regiao-imediata"]?.["regiao-intermediaria"]?.UF?.sigla;

		if (stateInitials === undefined || stateInitials === "") continue;

		byState[stateInitials] ??= [];
		byState[stateInitials].push([city.nome, String(city.id)]);
	}

	const sortedEntries = Object.entries(byState)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([state, tuples]) => [state, tuples.sort(([a], [b]) => a.localeCompare(b, "pt-BR"))] as const,
		);

	const body = sortedEntries
		.map(([state, tuples]) => {
			const rows = tuples.map(([name, code]) => `\t\t[${JSON.stringify(name)}, "${code}"],`);

			return `\t${state}: [\n${rows.join("\n")}\n\t],`;
		})
		.join("\n");

	const missingStates = STATE_CODES.filter((code) => !Object.hasOwn(byState, code));

	if (missingStates.length > 0) {
		throw new Error(`IBGE response is missing municipalities for: ${missingStates.join(", ")}`);
	}

	const knownCodes = new Set(json.map((city) => String(city.id)));
	const staleOtherNames = Object.keys(OTHER_NAMES).filter((code) => !knownCodes.has(code));

	if (staleOtherNames.length > 0) {
		throw new Error(`OTHER_NAMES has codes IBGE no longer lists: ${staleOtherNames.join(", ")}`);
	}

	const otherNamesBody = Object.entries(OTHER_NAMES)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([code, names]) =>
				`\t${JSON.stringify(code)}: [${names.map((name) => JSON.stringify(name)).join(", ")}],`,
		)
		.join("\n");

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/municipalities.ts"),
		`import { type StateCode } from "./states";

/**
 * Brazilian municipalities by state, published by the IBGE. \`DATA\` holds, for each state, a
 * \`[name, ibgeCode]\` tuple per municipality, sorted by name with \`localeCompare\` in the
 * "pt-BR" locale. Generated by \`scripts/cities.ts\`.
 *
 * @see Official: https://servicodados.ibge.gov.br/api/docs/localidades
 */
export type Municipality = {
	/** The 7-digit IBGE municipality code. */
	code: string;
	/** The municipality name. */
	name: string;
	/** The two-letter code of the state the municipality belongs to. */
	stateCode: StateCode;
};

export const DATA: Record<StateCode, readonly (readonly [string, string])[]> = {
${body}
};

/**
 * Alternative spellings of a municipality name, keyed by its 7-digit IBGE code: the spellings
 * the Correios CEP range mirror uses where it differs from the IBGE, mostly hyphen and accent
 * variants (Biritiba Mirim, Grão-Pará) and a couple of older names. A municipality with no
 * variant is simply absent, at no extra cost. Curated by \`scripts/cities.ts\`.
 *
 * @see Based on: https://gist.github.com/hugosenari/ec1a7d88f5bdd01844424dbc9aff9590
 */
export const OTHER_NAMES: Readonly<Record<string, readonly string[]>> = {
${otherNamesBody}
};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
