#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = import.meta.dirname;

type CnaeSubclass = {
	id: string;
	descricao: string;
};

const isCnaeSubclass = (value: unknown): value is CnaeSubclass =>
	typeof value === "object" &&
	value !== null &&
	"id" in value &&
	typeof value.id === "string" &&
	"descricao" in value &&
	typeof value.descricao === "string";

const main = async (): Promise<void> => {
	const response = await fetchWithRetry("https://servicodados.ibge.gov.br/api/v2/cnae/subclasses");

	if (!response.ok) {
		throw new Error(`IBGE CNAE request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!Array.isArray(json) || !json.every((entry) => isCnaeSubclass(entry))) {
		throw new Error("IBGE CNAE payload is not an array of subclass entries");
	}

	const entries = json
		.filter((subclass) => /^\d{7}$/.test(subclass.id))
		.sort((subclassA, subclassB) => (subclassA.id > subclassB.id ? 1 : -1))
		.map((subclass) => [subclass.id, subclass.descricao] as const);

	const data: Record<string, string> = {};
	for (const [id, descricao] of entries) {
		data[id] = descricao;
	}

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cnae.ts"),
		`/**
 * CNAE 2.3 (Classificação Nacional de Atividades Econômicas) subclasses, indexed by the
 * raw 7 digit code, mapping to the official subclass description.
 *
 * Generated by \`node ./scripts/cnae.ts\`. Do not edit by hand.
 *
 * @see Official: https://servicodados.ibge.gov.br/api/v2/cnae/subclasses
 * @see Official: https://concla.ibge.gov.br/classificacoes/por-tema/atividades-economicas/classificacao-nacional-de-atividades-economicas
 */
export const CNAE_SUBCLASSES: Record<string, string> = ${JSON.stringify(data)};

/**
 * Shape a CNAE subclass code has to be written in: the 7 digits, optionally split into the
 * printed \`NNNN-N/NN\` groups by whitespace or the usual mask characters.
 */
export const CNAE_FORMAT_REGEX = /^\\d{4}[\\s.\\-/]*\\d[\\s.\\-/]*\\d{2}$/;
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
