#!/usr/bin/env node

import { fetchSortedRecord } from "./fetch-sorted-record.ts";
import {
	runAsEntryPoint,
	serializeCodes,
	splitRecord,
	writeGeneratedFiles,
} from "./lookup-table.ts";

type CnaeSubclass = {
	id: string;
	descricao: string;
};

const isCnaeSubclass = (value: unknown): value is CnaeSubclass =>
	typeof value === "object" &&
	value !== null &&
	"id" in value &&
	typeof value.id === "string" &&
	"descricao" in value &&
	typeof value.descricao === "string";

/**
 * Renders the two modules the CNAE table is shipped as.
 * @param {Record<string, string>} subclasses - The subclass descriptions, keyed by the 7 digits.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderCnae = (subclasses: Record<string, string>): Record<string, string> => {
	const { codes, descriptions } = splitRecord(subclasses);

	return {
		"./src/_internals/constants/cnae.ts": `/**
 * CNAE-Subclasses 2.3 (Classificação Nacional de Atividades Econômicas) subclass codes: the raw
 * 7 digits of every subclass, back to back in ascending order, which \`findCodeIndex\` reads. The
 * official description of a subclass is at the same index of \`CNAE_DESCRIPTIONS\`, a module of
 * its own (\`cnae-descriptions.ts\`) so that checking a code does not bundle the descriptions.
 *
 * 2.3 is the current subclass revision of CNAE 2.0: CONCLA's own CNAE browser lists it as
 * "CNAE-Subclasses 2.3" under "CNAE 2.0 (Res 02/2010)" and tells anyone opening an older table
 * that the "Versões atuais da CNAE" are "CNAE 2.0 (Res 02/2010)" and "CNAE-Subclasses 2.3". The
 * classification's landing page still describes the parent CNAE 2.0 itself ("Base Legal:
 * Resolução Concla 01/2006", 1301 subclasses); the 1332 subclasses below are the ones the IBGE
 * data service publishes for the 2.3 revision.
 *
 * Generated by \`node ./scripts/cnae.ts\`. Do not edit by hand.
 *
 * @see Official: https://servicodados.ibge.gov.br/api/v2/cnae/subclasses
 * @see Official: https://concla.ibge.gov.br/busca-online-cnae.html
 * CONCLA's CNAE search and structure browser, which publishes CNAE-Subclasses 2.3.
 * @see Official: https://concla.ibge.gov.br/classificacoes/por-tema/atividades-economicas/classificacao-nacional-de-atividades-economicas
 * CNAE 2.0, the parent classification the 2.3 subclass revision belongs to.
 */
export const CNAE_CODES = ${serializeCodes(codes)};

/**
 * Shape a CNAE subclass code has to be written in: the 7 digits, optionally split into the
 * printed \`NNNN-N/NN\` groups by a single whitespace or mask character.
 */
export const CNAE_FORMAT_REGEX = /^\\d{4}[\\s.\\-/]?\\d[\\s.\\-/]?\\d{2}$/;
`,
		"./src/_internals/constants/cnae-descriptions.ts": `/**
 * CNAE-Subclasses 2.3 official subclass descriptions, each at the index of its code in
 * \`CNAE_CODES\` (\`cnae.ts\`).
 *
 * Generated by \`node ./scripts/cnae.ts\`. Do not edit by hand.
 *
 * @see Official: https://servicodados.ibge.gov.br/api/v2/cnae/subclasses
 */
export const CNAE_DESCRIPTIONS: readonly string[] = ${JSON.stringify(descriptions)};
`,
	};
};

const main = async (): Promise<void> => {
	const data = await fetchSortedRecord(
		"https://servicodados.ibge.gov.br/api/v2/cnae/subclasses",
		"IBGE CNAE",
		async (response) => {
			const json: unknown = await response.json();

			if (!Array.isArray(json) || !json.every((entry) => isCnaeSubclass(entry))) {
				throw new Error("IBGE CNAE payload is not an array of subclass entries");
			}

			return Object.fromEntries(
				json
					.filter((subclass) => /^\d{7}$/.test(subclass.id))
					.map((subclass) => [subclass.id, subclass.descricao]),
			);
		},
	);

	await writeGeneratedFiles(renderCnae(data));
};

await runAsEntryPoint(import.meta.filename, main);
