#!/usr/bin/env node

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";
import { decodeXml } from "./decode-xml.ts";
import { runAsEntryPoint, writeGeneratedFiles } from "./lookup-table.ts";

const RANGE_MESSAGE_URL = "https://www.isbn-international.org/export_rangemessage.xml";

const LAST_RANGE_END = 9_999_999;

const RANGE_DIGITS = 7;

const RANGE_REGEX = /^(\d{7})-(\d{7})$/;

/** One `<Rule>` of the RangeMessage: the 7 digit range it covers and the element length it gives. */
type RangeRule = { start: number; end: number; length: number };

/** One `<EAN.UCC>` or `<Group>` of the RangeMessage. */
type RangeEntry = { prefix: string; agency: string; rules: RangeRule[] };

const readTag = (xml: string, tag: string): string => {
	const match = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`).exec(xml);

	if (match === null) throw new Error(`RangeMessage has no <${tag}> where one is expected`);

	return decodeXml(match[1].trim());
};

const readEntries = (xml: string, tag: string): RangeEntry[] =>
	[...xml.matchAll(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, "g"))].map(([, body]) => ({
		prefix: readTag(body, "Prefix"),
		agency: readTag(body, "Agency"),
		rules: [...body.matchAll(/<Rule>([\s\S]*?)<\/Rule>/g)].map(([, rule]) => {
			const range = RANGE_REGEX.exec(readTag(rule, "Range"));

			if (range === null) throw new Error(`RangeMessage has an unexpected range: ${rule}`);

			return {
				start: Number(range[1]),
				end: Number(range[2]),
				length: Number(readTag(rule, "Length")),
			};
		}),
	}));

/**
 * Writes one rule as the end of its range without the 9s it ends in (`9999999` is nothing left),
 * followed by its length, one digit: `1999999` and a length of 2 is `12`.
 * @param {number} end - The last value of the range.
 * @param {number | string} length - The length of the element the range gives.
 * @returns {string} The rule.
 */
const serializeRule = (end: number, length: number | string): string =>
	`${String(end).padStart(RANGE_DIGITS, "0").replace(/9+$/, "")}${length}`;

/**
 * Writes the rules of one entry as `end` and `length` pairs, each range starting where the one
 * before it ended. A span the RangeMessage leaves out is not assigned, the same as a rule of
 * length 0, so it is written as one.
 * @param {RangeEntry} entry - The entry.
 * @returns {string} The rules, comma separated.
 */
const serializeRules = ({ prefix, rules }: RangeEntry): string => {
	const pairs: string[] = [];
	let next = 0;

	for (const { start, end, length } of rules) {
		if (start < next || end < start) throw new Error(`RangeMessage ranges of ${prefix} overlap`);
		if (start > next) pairs.push(serializeRule(start - 1, 0));

		pairs.push(serializeRule(end, length));
		next = end + 1;
	}

	if (next <= LAST_RANGE_END) pairs.push(serializeRule(LAST_RANGE_END, 0));

	return pairs.join(",");
};

/**
 * Renders the module the ISBN ranges are shipped as.
 * @param {string} xml - The RangeMessage.
 * @returns {Record<string, string>} The content of the generated file, by its path.
 */
export const renderIsbnRanges = (xml: string): Record<string, string> => {
	const date = readTag(xml, "MessageDate");
	const prefixes = readEntries(xml, "EAN.UCC");
	const groups = readEntries(xml, "Group");

	if (prefixes.length === 0 || groups.length === 0) throw new Error("RangeMessage holds no range");

	const prefixLines = prefixes.map((entry) => `\t"${entry.prefix}": "${serializeRules(entry)}",`);
	const groupLines = groups.map(
		(entry) =>
			`\t"${entry.prefix}": [${JSON.stringify(entry.agency)}, "${serializeRules(entry)}"],`,
	);

	return {
		"./src/_internals/constants/isbn-ranges.ts": `/**
 * The ISBN ranges of the International ISBN Agency RangeMessage, which say how long each element
 * of an ISBN-13 is. Each value lists ranges over the 7 digits that follow the part already read, a
 * range starting where the one before it ended, from \`0000000\` to \`9999999\`, each written as
 * its last value without the 9s it ends in, then the length as one digit (\`12\` is a length of 2
 * up to \`1999999\`); a length of 0 marks a range not assigned yet.
 *
 * RangeMessage of ${date}.
 *
 * \`ISBN_PREFIX_RULES\` gives, for each GS1 prefix (978, 979), the length of the registration
 * group; \`ISBN_GROUP_RULES\` gives, for each prefix and group, the agency that manages it and
 * the length of the registrant element. The publication element is what is left before the
 * check digit.
 *
 * Generated by \`node ./scripts/isbn.ts\`. Do not edit by hand.
 *
 * @see Official: ${RANGE_MESSAGE_URL}
 * International ISBN Agency, ISBN Ranges, "Range Message (xml)".
 */
export const ISBN_PREFIX_RULES: Record<string, string> = {
${prefixLines.join("\n")}
};

export const ISBN_GROUP_RULES: Record<string, readonly [agency: string, rules: string]> = {
${groupLines.join("\n")}
};
`,
	};
};

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(RANGE_MESSAGE_URL);

	if (!response.ok)
		throw new Error(`ISBN RangeMessage request failed with status ${response.status}`);

	await writeGeneratedFiles(renderIsbnRanges(await response.text()));
};

await runAsEntryPoint(import.meta.filename, main);
