#!/usr/bin/env node

import { fetchSortedRecord } from "./fetch-sorted-record.ts";
import {
	runAsEntryPoint,
	serializeCodes,
	splitRecord,
	writeGeneratedFiles,
} from "./lookup-table.ts";

/** The official CSV is published in ISO-8859-1, not UTF-8. */
const NBS_CSV_DECODER = new TextDecoder("iso-8859-1");

const NBS_CSV_HEADER = "NBS 2.0;DESCRIÇÃO";

/**
 * A complete code, e.g. `1.0101.11.00`. The CSV also carries the chapter (`1.01`), position
 * (`1.0101`) and subposition (`1.0101.1`) headings, which classify nothing by themselves and are
 * left out of the table.
 */
const NBS_CODE_REGEX = /^\d\.\d{4}\.\d{2}\.\d{2}$/;

/**
 * Smallest number of complete codes the table yields. NBS 2.0 carries 920 and only a new version
 * of the nomenclature changes that, so a result far below it means the CSV layout changed.
 */
const MINIMUM_CODES = 900;

/**
 * Splits a CSV into records. A line break inside a quoted field does not end a record, so a
 * description written over two lines stays in one piece.
 * @param {string} csv - The decoded CSV.
 * @returns {string[]} One string per record, the line breaks between records removed.
 */
const splitRecords = (csv: string): string[] => {
	const records: string[] = [];
	let record = "";
	let quoted = false;

	for (const character of csv) {
		if (character === '"') quoted = !quoted;

		if (character === "\n" && !quoted) {
			records.push(record);
			record = "";
		} else if (character !== "\r" || quoted) {
			record += character;
		}
	}

	return [...records, record];
};

/**
 * Reads a field the way RFC 4180 writes it: a quoted field loses its outer quotes and every
 * doubled quote inside it becomes one.
 * @param {string} field - The raw field, quotes included.
 * @returns {string} The text of the field, whitespace collapsed.
 */
const readField = (field: string): string => {
	const trimmed = field.trim();

	if (!trimmed.startsWith('"')) return trimmed.replaceAll(/\s+/g, " ");

	if (trimmed.length < 2 || !trimmed.endsWith('"')) {
		throw new Error(`NBS CSV field ${trimmed} opens a quote it never closes`);
	}

	return trimmed.slice(1, -1).replaceAll('""', '"').replaceAll(/\s+/g, " ");
};

/**
 * Reads the `NBS 2.0;DESCRIÇÃO` rows of the official NBS 2.0 CSV.
 * @param {string} csv - The decoded CSV.
 * @returns {Record<string, string>} One entry per complete code, keyed by its 9 digits.
 */
const parseCsv = (csv: string): Record<string, string> => {
	const [header, ...rows] = splitRecords(csv);

	if (header?.trim() !== NBS_CSV_HEADER) {
		throw new Error(`NBS CSV header is not "${NBS_CSV_HEADER}"`);
	}

	const data: Record<string, string> = {};

	for (const row of rows) {
		const separator = row.indexOf(";");
		const code = row.slice(0, Math.max(separator, 0)).trim();
		const description = readField(row.slice(separator + 1));

		if (!NBS_CODE_REGEX.test(code) || description === "") continue;

		data[code.replaceAll(".", "")] = description;
	}

	return data;
};

/**
 * Renders the two modules the NBS table is shipped as.
 * @param {Record<string, string>} table - The descriptions, keyed by the 9 digit code.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderNbs = (table: Record<string, string>): Record<string, string> => {
	const { codes, descriptions } = splitRecord(table);

	return {
		"./src/_internals/constants/nbs.ts": `/**
 * NBS 2.0 (Nomenclatura Brasileira de Serviços, Intangíveis e Outras Operações que Produzam
 * Variações no Patrimônio) codes: the raw 9 digits of every complete code, back to back in
 * ascending order, which \`findCodeIndex\` reads. The official description of a code is at the
 * same index of \`NBS_DESCRIPTIONS\`, a module of its own (\`nbs-descriptions.ts\`) so that
 * checking a code does not bundle the descriptions.
 *
 * Built from the official \`NBSa_2-0.csv\` the MDIC publishes on gov.br, a plain
 * \`NBS 2.0;DESCRIÇÃO\` CSV in ISO-8859-1, the version 2.0 as amended by the Portaria Conjunta
 * RFB/SCS 2.000 of 18 December 2018. Only the complete codes are kept: the chapter, position and
 * subposition headings of the CSV classify nothing by themselves.
 *
 * Generated by \`node ./scripts/nbs.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.gov.br/mdic/pt-br/assuntos/sdic/comercio-e-servicos/nbs-nomenclatura-brasileira-de-servicos
 * The NBS page of the MDIC, which links the CSV and the Anexo I of the Portaria.
 * @see Official: https://www.gov.br/mdic/pt-br/images/REPOSITORIO/scs/decos/NBS/NBSa_2-0.csv
 * The NBS 2.0 table in CSV.
 */
export const NBS_CODES = ${serializeCodes(codes)};

/**
 * Shape an NBS code has to be written in: the 9 digits, optionally split into the printed
 * groups of 1, 4, 2 and 2 by a single whitespace or mask character.
 */
export const NBS_FORMAT_REGEX = /^\\d[\\s.\\-/]?\\d{4}[\\s.\\-/]?\\d{2}[\\s.\\-/]?\\d{2}$/;
`,
		"./src/_internals/constants/nbs-descriptions.ts": `/**
 * NBS 2.0 official descriptions, each at the index of its code in \`NBS_CODES\` (\`nbs.ts\`).
 *
 * Generated by \`node ./scripts/nbs.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.gov.br/mdic/pt-br/images/REPOSITORIO/scs/decos/NBS/NBSa_2-0.csv
 * The NBS 2.0 table in CSV.
 */
export const NBS_DESCRIPTIONS: readonly string[] = ${JSON.stringify(descriptions)};
`,
	};
};

const main = async (): Promise<void> => {
	const sorted = await fetchSortedRecord(
		"https://www.gov.br/mdic/pt-br/images/REPOSITORIO/scs/decos/NBS/NBSa_2-0.csv",
		"NBS CSV",
		async (response) => {
			const data = parseCsv(NBS_CSV_DECODER.decode(await response.arrayBuffer()));

			if (Object.keys(data).length < MINIMUM_CODES) {
				throw new Error(`NBS CSV holds fewer than ${MINIMUM_CODES} codes`);
			}

			return data;
		},
	);

	await writeGeneratedFiles(renderNbs(sorted));
};

await runAsEntryPoint(import.meta.filename, main);
