#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchSortedRecord } from "./fetch-sorted-record.ts";

const scriptsDir = import.meta.dirname;

/** The official CSV is published in ISO-8859-1, not UTF-8. */
const NBS_CSV_DECODER = new TextDecoder("iso-8859-1");

const NBS_CSV_HEADER = "NBS 2.0;DESCRIÇÃO";

/**
 * A complete code, e.g. `1.0101.11.00`. The CSV also carries the chapter (`1.01`), position
 * (`1.0101`) and subposition (`1.0101.1`) headings, which classify nothing by themselves and are
 * left out of the table.
 */
const NBS_CODE_REGEX = /^\d\.\d{4}\.\d{2}\.\d{2}$/;

/**
 * Smallest number of complete codes the table yields. NBS 2.0 carries 920 and only a new version
 * of the nomenclature changes that, so a result far below it means the CSV layout changed.
 */
const MINIMUM_CODES = 900;

/**
 * Reads the `NBS 2.0;DESCRIÇÃO` rows of the official NBS 2.0 CSV.
 * @param {string} csv - The decoded CSV.
 * @returns {Record<string, string>} One entry per complete code, keyed by its 9 digits.
 */
const parseCsv = (csv: string): Record<string, string> => {
	const [header, ...rows] = csv.split(/\r?\n/);

	if (header?.trim() !== NBS_CSV_HEADER) {
		throw new Error(`NBS CSV header is not "${NBS_CSV_HEADER}"`);
	}

	const data: Record<string, string> = {};

	for (const row of rows) {
		const separator = row.indexOf(";");
		const code = row.slice(0, Math.max(separator, 0)).trim();
		const description = row
			.slice(separator + 1)
			.trim()
			.replaceAll(/\s+/g, " ");

		if (!NBS_CODE_REGEX.test(code) || description === "") continue;

		data[code.replaceAll(".", "")] = description;
	}

	return data;
};

const main = async (): Promise<void> => {
	const sorted = await fetchSortedRecord(
		"https://www.gov.br/mdic/pt-br/images/REPOSITORIO/scs/decos/NBS/NBSa_2-0.csv",
		"NBS CSV",
		async (response) => {
			const data = parseCsv(NBS_CSV_DECODER.decode(await response.arrayBuffer()));

			if (Object.keys(data).length < MINIMUM_CODES) {
				throw new Error(`NBS CSV holds fewer than ${MINIMUM_CODES} codes`);
			}

			return data;
		},
	);

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/nbs.ts"),
		`/**
 * NBS 2.0 (Nomenclatura Brasileira de Serviços, Intangíveis e Outras Operações que Produzam
 * Variações no Patrimônio) descriptions, indexed by the raw 9 digit code.
 *
 * Built from the official \`NBSa_2-0.csv\` the MDIC publishes on gov.br, a plain
 * \`NBS 2.0;DESCRIÇÃO\` CSV in ISO-8859-1, the version 2.0 as amended by the Portaria Conjunta
 * RFB/SCS 2.000 of 18 December 2018. Only the complete codes are kept: the chapter, position and
 * subposition headings of the CSV classify nothing by themselves.
 *
 * Generated by \`node ./scripts/nbs.ts\`. Do not edit by hand.
 *
 * @see Official: https://www.gov.br/mdic/pt-br/assuntos/sdic/comercio-e-servicos/nbs-nomenclatura-brasileira-de-servicos
 * The NBS page of the MDIC, which links the CSV and the Anexo I of the Portaria.
 * @see Official: https://www.gov.br/mdic/pt-br/images/REPOSITORIO/scs/decos/NBS/NBSa_2-0.csv
 * The NBS 2.0 table in CSV.
 */
export const NBS_DESCRIPTIONS: Record<string, string> = ${JSON.stringify(sorted)};

/**
 * Shape an NBS code has to be written in: the 9 digits, optionally split into the printed
 * groups of 1, 4, 2 and 2 by a single whitespace or mask character.
 */
export const NBS_FORMAT_REGEX = /^\\d[\\s.\\-/]?\\d{4}[\\s.\\-/]?\\d{2}[\\s.\\-/]?\\d{2}$/;
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
