#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = import.meta.dirname;

type NcmEntry = {
	Codigo: string;
	Data_Inicio: string;
	Data_Fim: string;
};

type NcmResponse = {
	Nomenclaturas: NcmEntry[];
};

const isNcmEntry = (value: unknown): value is NcmEntry =>
	typeof value === "object" &&
	value !== null &&
	"Codigo" in value &&
	typeof value.Codigo === "string" &&
	"Data_Inicio" in value &&
	typeof value.Data_Inicio === "string" &&
	"Data_Fim" in value &&
	typeof value.Data_Fim === "string";

const isNcmResponse = (value: unknown): value is NcmResponse =>
	typeof value === "object" &&
	value !== null &&
	"Nomenclaturas" in value &&
	Array.isArray(value.Nomenclaturas) &&
	value.Nomenclaturas.every((entry) => isNcmEntry(entry));

/**
 * Parses a Siscomex `dd/mm/yyyy` date into a `Date` at UTC midnight.
 *
 * @param {string} date - A date string in `dd/mm/yyyy` format.
 * @returns {Date} The parsed date.
 */
const parseBrDate = (date: string): Date => {
	const [day, month, year] = date.split("/").map(Number);
	return new Date(Date.UTC(year, month - 1, day));
};

/**
 * Whether `today` falls within `[Data_Inicio, Data_Fim]` (both inclusive).
 *
 * @param {NcmEntry} entry - The Siscomex NCM entry to check.
 * @param {Date} today - The reference date.
 * @returns {boolean} `true` when `entry` is in force on `today`.
 */
const isInForce = (entry: NcmEntry, today: Date): boolean =>
	parseBrDate(entry.Data_Inicio) <= today && today <= parseBrDate(entry.Data_Fim);

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(
		"https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json?perfil=PUBLICO",
	);

	if (!response.ok) {
		throw new Error(`Siscomex NCM request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!isNcmResponse(json)) {
		throw new Error("Siscomex NCM payload is not a Nomenclaturas response");
	}

	const today = new Date(
		Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth(), new Date().getUTCDate()),
	);

	const codes = json.Nomenclaturas.filter(
		(entry) => /^[\d.]{10}$/.test(entry.Codigo) && isInForce(entry, today),
	)
		.map((entry) => entry.Codigo.replaceAll(/\D/g, ""))
		.filter((code) => code.length === 8);

	const uniqueSortedCodes = [...new Set(codes)].sort();

	await writeFile(
		resolve(scriptsDir, "..", "./src/is-valid-ncm/constants.ts"),
		`/**
 * NCM (Nomenclatura Comum do Mercosul) 8 digit codes in force on the generation date, sorted
 * ascending. A code is included when the generation date falls within its Siscomex
 * \`Data_Inicio\`/\`Data_Fim\` range (both inclusive) — this also keeps codes that are valid
 * today but carry a scheduled future end date, not only the ones with no end date
 * (\`Data_Fim: "31/12/9999"\`).
 *
 * Generated by \`node ./scripts/ncm.ts\`. Do not edit by hand.
 *
 * @see Official: https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json
 */
export const NCM_CODES: readonly string[] = ${JSON.stringify(uniqueSortedCodes)};

/**
 * Shape a complete NCM code has to be written in: the 8 digits, optionally split into the
 * printed \`NNNN.NN.NN\` groups by a single whitespace or mask character.
 */
export const NCM_FORMAT_REGEX = /^\\d{4}[\\s.\\-/]?\\d{2}[\\s.\\-/]?\\d{2}$/;
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
