#!/usr/bin/env node

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";
import { decodeXml } from "./decode-xml.ts";
import {
	runAsEntryPoint,
	serializeCodes,
	splitRecord,
	writeGeneratedFiles,
} from "./lookup-table.ts";
import { readXlsxSheet } from "./read-xlsx-sheet.ts";

const DOCUMENTATION_URL =
	"https://www.gov.br/nfse/pt-br/biblioteca/documentacao-tecnica/documentacao-atual";

/**
 * The ANEXO B is published under a file name that carries its version and date, e.g.
 * `anexo_b-nbs2-lista_servico_nacional-snnfse-v1-01-20260122.xlsx`, so the link is read from the
 * documentation page instead of being pinned here: a new version is picked up by the next run.
 * The `href` is read as the page writes it, so it is decoded and resolved against the page before
 * it is fetched, the way `scripts/ibs-cbs.ts` reads the links of the Portal da NF-e.
 */
const ANNEX_LINK_REGEX = /href="([^"]*anexo_b-nbs2-lista_servico_nacional[^"]*\.xlsx)"/i;

const SHEET_NAME = "LISTA.SERV.NAC.";

const SHEET_HEADER = "CÓDIGO DE TRIBUTAÇÃO NACIONAL|ITEM|SUBITEM|DESDOBRO NACIONAL|DESCRIÇÃO";

/**
 * Item 99, "Serviços sem a incidência de ISSQN e ICMS", is an addition of the national list: the
 * list annexed to the Lei Complementar 116/2003 ends at item 40.
 */
const LAST_LAW_ITEM = 40;

/**
 * Smallest number of subitems a complete list yields. The law carries 200 in force today and is
 * only ever amended by another lei complementar, so a result far below it means the sheet
 * changed, not that subitems were revoked.
 */
const MINIMUM_SUBITEMS = 190;

const fetchOk = async (url: string, label: string): Promise<Response> => {
	const response = await fetchWithRetry(url);

	if (!response.ok) throw new Error(`${label} request failed with status ${response.status}`);

	return response;
};

/**
 * Reads the subitems of the law out of the national service list. The sheet prints three levels:
 * the item (`SUBITEM` 0), the subitem of the law (`DESDOBRO NACIONAL` 0) and the national codes
 * the Comitê Gestor splits a subitem into. Only the second level is the list annexed to the law.
 * @param {string[][]} rows - The rows of the sheet, header included.
 * @returns {Record<string, string>} One entry per subitem, keyed by the 4 digits (`0101`).
 */
const parseSheet = (rows: string[][]): Record<string, string> => {
	const [header, ...body] = rows;

	if (header?.join("|") !== SHEET_HEADER) {
		throw new Error(`the ${SHEET_NAME} header is not "${SHEET_HEADER}"`);
	}

	const data: Record<string, string> = {};

	for (const [, item, subitem, split, description] of body) {
		const isLawSubitem = Number(item) <= LAST_LAW_ITEM && Number(subitem) > 0 && split === "0";
		const text = (description ?? "").trim().replaceAll(/\s+/g, " ");

		if (!isLawSubitem || text === "") continue;

		data[`${item.padStart(2, "0")}${subitem.padStart(2, "0")}`] = text;
	}

	return data;
};

/**
 * Renders the two modules the service list is shipped as.
 * @param {Record<string, string>} subitems - The subitem descriptions, keyed by the 4 digits.
 * @param {string} workbook - The file name of the ANEXO B workbook they were read from.
 * @returns {Record<string, string>} The content of each generated file, by its path.
 */
export const renderServiceItems = (
	subitems: Record<string, string>,
	workbook: string,
): Record<string, string> => {
	const { codes, descriptions } = splitRecord(subitems);

	return {
		"./src/_internals/constants/service-items.ts": `/**
 * The subitems in force of the service list annexed to the Lei Complementar 116/2003: the raw 4
 * digits of every subitem (\`0101\` for \`1.01\`, the first four digits of the national
 * \`cTribNac\` code), back to back in ascending order, which \`findCodeIndex\` reads. The
 * description of a subitem is at the same index of \`SERVICE_ITEM_DESCRIPTIONS\`, a module of its
 * own (\`service-item-descriptions.ts\`) so that checking a subitem does not bundle the
 * descriptions.
 *
 * Built from the sheet \`${SHEET_NAME}\` of the \`ANEXO_B-NBS2-LISTA_SERVICO_NACIONAL\` workbook
 * of the Sistema Nacional NFS-e, which prints the list in force, vetoed subitems left out and
 * the amendments of later leis complementares applied. The item headings, the national codes a
 * subitem is split into and item 99, an addition of the national list, are not part of the law
 * and are left out.
 *
 * Generated by \`node ./scripts/service-items.ts\` from \`${workbook}\`.
 * Do not edit by hand.
 *
 * @see Official: https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp116.htm
 * Lei Complementar 116/2003, "Lista de serviços anexa".
 * @see Official: ${DOCUMENTATION_URL}
 * Sistema Nacional NFS-e, current technical documentation, ANEXO B.
 */
export const SERVICE_ITEM_CODES = ${serializeCodes(codes)};

/**
 * Shape a subitem has to be written in: one or two digits of the item and the two of the
 * subitem, with the dot the law prints between them or without it.
 */
export const SERVICE_ITEM_FORMAT_REGEX = /^\\d{1,2}\\.?\\d{2}$/;

/** Digits of a subitem the table is keyed by: two of the item and two of the subitem. */
export const SERVICE_ITEM_LENGTH = 4;
`,
		"./src/_internals/constants/service-item-descriptions.ts": `/**
 * The descriptions of the subitems in force of the service list annexed to the Lei Complementar
 * 116/2003, each at the index of its subitem in \`SERVICE_ITEM_CODES\` (\`service-items.ts\`).
 *
 * Generated by \`node ./scripts/service-items.ts\` from \`${workbook}\`.
 * Do not edit by hand.
 *
 * @see Official: ${DOCUMENTATION_URL}
 * Sistema Nacional NFS-e, current technical documentation, ANEXO B.
 */
export const SERVICE_ITEM_DESCRIPTIONS: readonly string[] = ${JSON.stringify(descriptions)};
`,
	};
};

const main = async (): Promise<void> => {
	const pageResponse = await fetchOk(DOCUMENTATION_URL, "NFS-e documentation page");
	const page = await pageResponse.text();
	const link = ANNEX_LINK_REGEX.exec(page)?.[1];

	if (link === undefined) throw new Error("the NFS-e documentation page links no ANEXO B");

	const annex = new URL(decodeXml(link), DOCUMENTATION_URL).href;
	const workbookResponse = await fetchOk(annex, "NFS-e ANEXO B");
	const workbook = await workbookResponse.arrayBuffer();
	const data = parseSheet(readXlsxSheet(Buffer.from(workbook), SHEET_NAME));

	if (Object.keys(data).length < MINIMUM_SUBITEMS) {
		throw new Error(`the national service list holds fewer than ${MINIMUM_SUBITEMS} subitems`);
	}

	const workbookName = link.slice(link.lastIndexOf("/") + 1);

	await writeGeneratedFiles(renderServiceItems(data, workbookName));
};

await runAsEntryPoint(import.meta.filename, main);
