#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDirectory = import.meta.dirname;

type State = {
	id: number;
	sigla: string;
	nome: string;
	regiao: {
		id: number;
		sigla: string;
		nome: string;
	};
};

const isState = (value: unknown): value is State =>
	typeof value === "object" &&
	value !== null &&
	"id" in value &&
	typeof value.id === "number" &&
	"sigla" in value &&
	typeof value.sigla === "string" &&
	"nome" in value &&
	typeof value.nome === "string" &&
	"regiao" in value &&
	typeof value.regiao === "object" &&
	value.regiao !== null &&
	"sigla" in value.regiao &&
	typeof value.regiao.sigla === "string" &&
	"nome" in value.regiao &&
	typeof value.regiao.nome === "string";

type GeneratedState = {
	code: string;
	name: string;
	regionCode: string;
	regionName: string;
	ibgeCode: number;
};

const member = (state: GeneratedState): string =>
	`| { readonly code: ${JSON.stringify(state.code)}; readonly name: ${JSON.stringify(state.name)}; readonly regionCode: ${JSON.stringify(state.regionCode)}; readonly regionName: ${JSON.stringify(state.regionName)}; readonly ibgeCode: ${state.ibgeCode} }`;

const union = (states: GeneratedState[]): string => states.map((state) => member(state)).join(" ");

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(
		"https://servicodados.ibge.gov.br/api/v1/localidades/estados",
	);

	if (!response.ok) {
		throw new Error(`IBGE states request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!Array.isArray(json) || json.length === 0 || !json.every((entry) => isState(entry))) {
		throw new Error(
			"IBGE states payload is not an array of states with id, sigla, nome and regiao",
		);
	}

	const states = json
		.sort((stateA, stateB) => stateA.nome.localeCompare(stateB.nome, "pt-BR"))
		.map((state) => ({
			code: state.sigla,
			name: state.nome,
			regionCode: state.regiao.sigla,
			regionName: state.regiao.nome,
			ibgeCode: state.id,
		}));

	await writeFile(
		resolve(scriptsDirectory, "..", "./src/_internals/constants/states.ts"),
		`/**
 * One Brazilian state, as returned by \`getStates\`, \`getStateByIbgeCode\` and the other state
 * utils. Every state is its own member of the union, so the fields of a state are tied to each
 * other: \`Extract<State, { code: "SP" }>["name"]\` is \`"São Paulo"\`, and narrowing a \`State\` by
 * \`code\` narrows its \`name\`, \`regionCode\`, \`regionName\` and \`ibgeCode\` too. An impossible
 * combination such as \`{ code: "SP", name: "Acre" }\` is not a \`State\`.
 *
 * Each member has the two letter code of the state (\`code\`, e.g. \`"SP"\`), its full name
 * (\`name\`, e.g. \`"São Paulo"\`), the code and the full name of the region it belongs to
 * (\`regionCode\` and \`regionName\`, e.g. \`"SE"\` and \`"Sudeste"\`) and the 2 digit IBGE code of the
 * Federative Unit (\`ibgeCode\`, the "cUF", e.g. \`35\`).
 */
export type State = ${union(states)};

/** The two letter code of each Brazilian state, as published by the IBGE. */
export type StateCode = State["code"];

/** The name of each Brazilian state, as published by the IBGE. */
export type StateName = State["name"];

/**
 * Brazilian states published by the IBGE, sorted by name with \`localeCompare\` in the "pt-BR"
 * locale. \`ibgeCode\` is the 2-digit IBGE code of the Federative Unit ("cUF"), the same code
 * found in the first field of every DF-e access key (chave de acesso).
 *
 * @see Official: https://servicodados.ibge.gov.br/api/docs/localidades
 */
export const DATA: readonly State[] = ${JSON.stringify(states)};`,
	);

	await writeFile(
		resolve(scriptsDirectory, "..", "./src/_internals/constants/state-codes.ts"),
		`import { type StateCode } from "./states";

/**
 * The two letter code of each Brazilian state published by the IBGE, in the order of \`DATA\` in
 * \`./states\` (sorted by state name in the "pt-BR" locale), on its own so that a util which only
 * needs the codes does not carry the whole states table into a consumer's bundle.
 *
 * Generated by \`node ./scripts/states.ts\`. Do not edit by hand.
 *
 * @see Official: https://servicodados.ibge.gov.br/api/docs/localidades
 */
export const STATE_CODES: readonly StateCode[] = ${JSON.stringify(states.map((state) => state.code))};`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
