#!/usr/bin/env node
/**
 * Classifies every utility of the published package by the feature it needs from the engine, so
 * "how many utilities can be authored once" has a measured answer rather than an opinion.
 *
 * The classification is syntactic and deliberately conservative: it reads the utility and
 * everything it imports from `src/_internals`, and reports what it finds.
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";

const PACKAGE_SRC = resolve(import.meta.dirname, "..", "..", "src");

type Feature =
	| "strings"
	| "ascii"
	| "regex"
	| "ranges"
	| "dataset"
	| "collation"
	| "dates"
	| "decimal"
	| "float"
	| "random"
	| "http"
	| "unicode"
	| "recursion"
	| "maps"
	| "unions";

const DETECTORS: { feature: Feature; test: RegExp }[] = [
	{ feature: "regex", test: /\/\^|RegExp|\.test\(|replaceAll\(\//u },
	{ feature: "ascii", test: /charCodeAt|charAt|padStart|toUpperCase|toLowerCase/u },
	{ feature: "dates", test: /new Date|getFullYear|getMonth|getDay\(/u },
	{ feature: "float", test: /Number\(|parseFloat|Math\.(round|floor|ceil|abs|pow)/u },
	{ feature: "decimal", test: /toFixed|Intl\.NumberFormat|precision/u },
	{ feature: "random", test: /Math\.random|randomInt|pickRandom/u },
	{ feature: "http", test: /fetch\(|fetchWithRetry/u },
	{ feature: "unicode", test: /normalize\(|localeCompare|\\p\{/u },
	{ feature: "maps", test: /new Map\(|new Set\(|Object\.entries|Object\.keys/u },
	{ feature: "dataset", test: /from "\.\.\/_internals\/constants|constants"|CITIES|BANKS|CNAE/u },
	{ feature: "collation", test: /\.sort\(|localeCompare/u },
	{ feature: "unions", test: /kind:|type:\s*"/u },
];

const utilities = readdirSync(PACKAGE_SRC)
	.filter((entry) => statSync(join(PACKAGE_SRC, entry)).isDirectory() && entry !== "_internals")
	.sort();

const rows: { name: string; features: Feature[]; lines: number }[] = [];

for (const utility of utilities) {
	const file = join(PACKAGE_SRC, utility, `${utility}.ts`);
	if (!existsSync(file)) continue;
	const source = readFileSync(file, "utf8");
	const constants = join(PACKAGE_SRC, utility, "constants.ts");
	const combined = source + (existsSync(constants) ? readFileSync(constants, "utf8") : "");
	const features = DETECTORS.filter((detector) => detector.test.test(combined)).map((detector) => detector.feature);
	if (existsSync(constants)) features.push("dataset");
	rows.push({
		name: utility,
		features: [...new Set(["strings" as Feature, ...features])].sort(),
		lines: source.split("\n").filter((line) => line.trim() !== "" && !line.trim().startsWith("*")).length,
	});
}

const counts = new Map<Feature, number>();
for (const row of rows) {
	for (const feature of row.features) counts.set(feature, (counts.get(feature) ?? 0) + 1);
}

/** What the engine supports today, and what a utility needing it is blocked by. */
const SUPPORT: Record<Feature, string> = {
	strings: "supported",
	ascii: "supported",
	regex: "supported (explicit classes only)",
	ranges: "supported",
	dataset: "supported as constant tables; a baked dataset type is not admitted yet",
	collation: "supported (scalar order); locale collation is not admitted",
	dates: "supported (CivilDate)",
	decimal: "supported (fixed scale)",
	float: "supported",
	random: "supported (PCG32 in source over random.nextU32)",
	http: "supported",
	unicode: "blocked: normalization and locale case mapping are out of scope",
	recursion: "blocked: not admitted in this phase",
	maps: "blocked: Map and Set are not admitted yet",
	unions: "blocked: discriminated unions are not admitted yet",
};

const blocked = rows.filter((row) => row.features.some((feature) => SUPPORT[feature].startsWith("blocked")));

const lines = [
	"# Survey of the published package",
	"",
	"Generated by `node scripts/survey.ts`. The classification is syntactic and conservative: it",
	"reads each utility and reports the features it appears to need. It answers the question the",
	"engine exists to answer — how many utilities could be authored once — with a number rather",
	"than a feeling.",
	"",
	`**${rows.length} utilities.** ${rows.length - blocked.length} use only features the engine supports today;`,
	`${blocked.length} touch something that is not admitted yet.`,
	"",
	"## Features by utility count",
	"",
	"| feature | utilities | status |",
	"| --- | --- | --- |",
	...[...counts.entries()]
		.sort(([, left], [, right]) => right - left)
		.map(([feature, count]) => `| ${feature} | ${count} | ${SUPPORT[feature]} |`),
	"",
	"## Blocked utilities",
	"",
	"| utility | blocked by |",
	"| --- | --- |",
	...blocked.map(
		(row) =>
			`| \`${row.name}\` | ${row.features.filter((feature) => SUPPORT[feature].startsWith("blocked")).join(", ")} |`,
	),
	"",
	"## Every utility",
	"",
	"| utility | lines | features |",
	"| --- | --- | --- |",
	...rows.map((row) => `| \`${row.name}\` | ${row.lines} | ${row.features.join(", ")} |`),
	"",
];

process.stdout.write(`${lines.join("\n")}\n`);
