import { anyText, anyValue, digits } from "../_internals/test/arbitraries";
import { expectAlwaysReturnsType, expectRejected } from "../_internals/test/properties";
import { describe, expect, expectTypeOf, test } from "../_internals/test/runtime";
import { isValidNfseKey } from "./is-valid-nfse-key";

const KEY_CNPJ = "35503082258716523000119000000000001226011357924683";
const KEY_CPF = "43149021100040364478829000000000105725120484407255";
// Receita Federal's example alphanumeric CNPJ 12.ABC.345/01DE-35, September 2026; the key check
// digit worked out by hand with every character worth its ASCII code minus 48 (sum 1164,
// remainder 9, DV 2).
const KEY_ALPHANUMERIC = "35503082212ABC34501DE35000000000001226091357924682";

describe("isValidNfseKey", () => {
	describe("should return true", () => {
		test("for a synthetic key of a CNPJ issuer generated by the Sistema Nacional NFS-e", () => {
			expect(isValidNfseKey(KEY_CNPJ)).toBe(true);
		});

		test("for a synthetic key of a CPF issuer generated by the municipality", () => {
			expect(isValidNfseKey(KEY_CPF)).toBe(true);
		});

		test("when it has the NFS prefix found in the XML Id attribute, in any case", () => {
			expect(isValidNfseKey(`NFS${KEY_CNPJ}`)).toBe(true);
			expect(isValidNfseKey(`nfs${KEY_CPF}`)).toBe(true);
		});

		test("when it has surrounding whitespace", () => {
			expect(isValidNfseKey(` ${KEY_CNPJ}\n`)).toBe(true);
		});

		test("for a key of an alphanumeric CNPJ issuer, the letters worth their ASCII code minus 48", () => {
			expect(isValidNfseKey(KEY_ALPHANUMERIC)).toBe(true);
			expect(isValidNfseKey(`NFS${KEY_ALPHANUMERIC}`)).toBe(true);
		});

		test("for a key of an alphanumeric CNPJ written in lower case, read in upper case as isValidCnpj reads it", () => {
			expect(isValidNfseKey(KEY_ALPHANUMERIC.toLowerCase())).toBe(true);
		});

		test("for an alphanumeric CNPJ key generated by the municipality, with the check digit recalculated", () => {
			expect(isValidNfseKey("35503081212ABC34501DE35000000000001226091357924685")).toBe(true);
		});
	});

	describe("should return false", () => {
		test("when it is null", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(null)).toBe(false);
		});

		test("when it is undefined", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey()).toBe(false);
		});

		test("when it is a number, a boolean, an object or an array", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(123)).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(true)).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey({})).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey([KEY_CNPJ])).toBe(false);
		});

		test("when it is an empty string", () => {
			expect(isValidNfseKey("")).toBe(false);
		});

		test("when the check digit does not match", () => {
			expect(isValidNfseKey("35503082258716523000119000000000001226011357924684")).toBe(false);
		});

		test("when it does not have 50 digits", () => {
			expect(isValidNfseKey(KEY_CNPJ.slice(0, 49))).toBe(false);
			expect(isValidNfseKey(`${KEY_CNPJ}3`)).toBe(false);
		});

		test("when a separator sits inside a field", () => {
			expect(isValidNfseKey("355030 82258716523000119000000000001226011357924683")).toBe(false);
			expect(isValidNfseKey("35503082258716523000119000000000001226011357924 683")).toBe(false);
		});

		test("should accept the mask characters isValidCpf reads at the boundaries of its fields", () => {
			expect(isValidNfseKey("3550308 2 2 58716523000119 0000000000012 2601 135792468 3")).toBe(
				true,
			);
			expect(isValidNfseKey("3550308.2.2.58716523000119.0000000000012.2601.135792468-3")).toBe(
				true,
			);
		});

		test("for the 44 digit key of an NF-e", () => {
			expect(isValidNfseKey("35170458716523000119550010000000121000123458")).toBe(false);
		});

		test("for the example of the Guia do Emissor Público Nacional Web v1.2, item 9.1, an illustrative key whose check digit does not match and whose issuer CNPJ 51235800000112 is not valid either", () => {
			expect(isValidNfseKey("31062001251235800000112230000000173023019580208160")).toBe(false);
		});

		test("when the month is 13, even with a matching check digit", () => {
			expect(isValidNfseKey("35503082258716523000119000000000001226131357924684")).toBe(false);
		});

		test("when the issuer CNPJ has wrong check digits, even with a matching key check digit", () => {
			expect(isValidNfseKey("35503082258716523000110000000000001226011357924686")).toBe(false);
			expect(isValidNfseKey("35503082212ABC34501DE36000000000001226091357924689")).toBe(false);
		});

		test("when the check digit of an alphanumeric key reads a letter as its base 36 value (A = 10) instead of its ASCII code minus 48", () => {
			expect(isValidNfseKey("35503082212ABC34501DE35000000000001226091357924680")).toBe(false);
		});

		test("when the registration type says CPF and the registration carries letters, even with a matching key check digit", () => {
			expect(isValidNfseKey("35503082112ABC34501DE35000000000001226091357924684")).toBe(false);
			expect(isValidNfseKey("355030821000ABC4478829000000000001226091357924685")).toBe(false);
		});

		test("when a letter stands outside the registration, even with a matching key check digit", () => {
			expect(isValidNfseKey("35503082212ABC34501DE3500000000000A226091357924686")).toBe(false);
			expect(isValidNfseKey("355030A2258716523000119000000000001226011357924680")).toBe(false);
		});
	});

	describe("properties", () => {
		test("should reject any text that is not a key", () => {
			expectRejected(isValidNfseKey, anyText);
		});

		test("should reject digits of the NF-e key length", () => {
			expectRejected(isValidNfseKey, digits(44));
		});

		test("should never throw and always return a boolean", () => {
			expectAlwaysReturnsType(isValidNfseKey, "boolean", anyValue);
		});
	});
});

describe("isValidNfseKey types", () => {
	test("should take a string and return a boolean", () => {
		expectTypeOf(isValidNfseKey).parameter(0).toEqualTypeOf<string>();
		expectTypeOf(isValidNfseKey).returns.toEqualTypeOf<boolean>();
	});
});
