import { anyText, anyValue, digits } from "../_internals/test/arbitraries";
import { expectAlwaysReturnsType, expectRejected } from "../_internals/test/properties";
import { describe, expect, expectTypeOf, test } from "../_internals/test/runtime";
import { isValidNfseKey } from "./is-valid-nfse-key";

const KEY_CNPJ = "35503082258716523000119000000000001226011357924683";
const KEY_CPF = "43149021100040364478829000000000105725120484407255";

describe("isValidNfseKey", () => {
	describe("should return true", () => {
		test("for a synthetic key of a CNPJ issuer generated by the Sistema Nacional NFS-e", () => {
			expect(isValidNfseKey(KEY_CNPJ)).toBe(true);
		});

		test("for a synthetic key of a CPF issuer generated by the municipality", () => {
			expect(isValidNfseKey(KEY_CPF)).toBe(true);
		});

		test("when it has the NFS prefix found in the XML Id attribute, in any case", () => {
			expect(isValidNfseKey(`NFS${KEY_CNPJ}`)).toBe(true);
			expect(isValidNfseKey(`nfs${KEY_CPF}`)).toBe(true);
		});

		test("when it has surrounding whitespace", () => {
			expect(isValidNfseKey(` ${KEY_CNPJ}\n`)).toBe(true);
		});
	});

	describe("should return false", () => {
		test("when it is null", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(null)).toBe(false);
		});

		test("when it is undefined", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey()).toBe(false);
		});

		test("when it is a number, a boolean, an object or an array", () => {
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(123)).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey(true)).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey({})).toBe(false);
			// @ts-expect-error: intentionally invalid input
			expect(isValidNfseKey([KEY_CNPJ])).toBe(false);
		});

		test("when it is an empty string", () => {
			expect(isValidNfseKey("")).toBe(false);
		});

		test("when the check digit does not match", () => {
			expect(isValidNfseKey("35503082258716523000119000000000001226011357924684")).toBe(false);
		});

		test("when it does not have 50 digits", () => {
			expect(isValidNfseKey(KEY_CNPJ.slice(0, 49))).toBe(false);
			expect(isValidNfseKey(`${KEY_CNPJ}3`)).toBe(false);
		});

		test("when it is split by separators, since the key has no mask", () => {
			expect(isValidNfseKey("3550308 2 2 58716523000119 0000000000012 2601 135792468 3")).toBe(
				false,
			);
			expect(isValidNfseKey("3550308.2.2.58716523000119.0000000000012.2601.135792468-3")).toBe(
				false,
			);
		});

		test("for the 44 digit key of an NF-e", () => {
			expect(isValidNfseKey("35170458716523000119550010000000121000123458")).toBe(false);
		});

		test("for the example of the Guia do Emissor Público Nacional Web v1.2, item 9.1, an illustrative key whose check digit does not match", () => {
			expect(isValidNfseKey("31062001251235800000112230000000173023019580208160")).toBe(false);
		});

		test("when the month is 13, even with a matching check digit", () => {
			expect(isValidNfseKey("35503082258716523000119000000000001226131357924684")).toBe(false);
		});

		test("when the issuer CNPJ has wrong check digits, even with a matching key check digit", () => {
			expect(isValidNfseKey("35503082258716523000110000000000001226011357924686")).toBe(false);
		});
	});

	describe("properties", () => {
		test("should reject any text that is not a key", () => {
			expectRejected(isValidNfseKey, anyText);
		});

		test("should reject digits of the NF-e key length", () => {
			expectRejected(isValidNfseKey, digits(44));
		});

		test("should never throw and always return a boolean", () => {
			expectAlwaysReturnsType(isValidNfseKey, "boolean", anyValue);
		});
	});
});

describe("isValidNfseKey types", () => {
	test("should take a string and return a boolean", () => {
		expectTypeOf(isValidNfseKey).parameter(0).toEqualTypeOf<string>();
		expectTypeOf(isValidNfseKey).returns.toEqualTypeOf<boolean>();
	});
});
